
services:
  auth_rpc:
    image: wsrh8888/auth_rpc:1.0.0
    container_name: auth_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./authrpc.yaml:/etc/authrpc.yaml:ro
    restart: "no"
    pull_policy: always
