// Code generated by goctl. DO NOT EDIT.
// Source: chat_rpc.proto

package chat

import (
	"context"

	"beaver/app/chat/chat_rpc/types/chat_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchUpdateConversationReq = chat_rpc.BatchUpdateConversationReq
	BatchUpdateConversationRes = chat_rpc.BatchUpdateConversationRes
	FileMsg                    = chat_rpc.FileMsg
	ImageMsg                   = chat_rpc.ImageMsg
	Msg                        = chat_rpc.Msg
	SendMsgReq                 = chat_rpc.SendMsgReq
	SendMsgRes                 = chat_rpc.SendMsgRes
	Sender                     = chat_rpc.Sender
	TextMsg                    = chat_rpc.TextMsg
	UpdateConversationReq      = chat_rpc.UpdateConversationReq
	UpdateConversationRes      = chat_rpc.UpdateConversationRes
	VideoMsg                   = chat_rpc.VideoMsg
	VoiceMsg                   = chat_rpc.VoiceMsg

	Chat interface {
		SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error)
		UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationRes, error)
		BatchUpdateConversation(ctx context.Context, in *BatchUpdateConversationReq, opts ...grpc.CallOption) (*BatchUpdateConversationRes, error)
	}

	defaultChat struct {
		cli zrpc.Client
	}
)

func NewChat(cli zrpc.Client) Chat {
	return &defaultChat{
		cli: cli,
	}
}

func (m *defaultChat) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.SendMsg(ctx, in, opts...)
}

func (m *defaultChat) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.UpdateConversation(ctx, in, opts...)
}

func (m *defaultChat) BatchUpdateConversation(ctx context.Context, in *BatchUpdateConversationReq, opts ...grpc.CallOption) (*BatchUpdateConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.BatchUpdateConversation(ctx, in, opts...)
}
