// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: chat_rpc.proto

package chat

import (
	"context"

	"beaver/app/chat/chat_rpc/types/chat_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddConversationMembersReq               = chat_rpc.AddConversationMembersReq
	AddConversationMembersRes               = chat_rpc.AddConversationMembersRes
	AudioFileMsg                            = chat_rpc.AudioFileMsg
	BatchUpdateConversationReq              = chat_rpc.BatchUpdateConversationReq
	BatchUpdateConversationRes              = chat_rpc.BatchUpdateConversationRes
	ConversationItem                        = chat_rpc.ConversationItem
	ConversationListById                    = chat_rpc.ConversationListById
	DissolveConversationReq                 = chat_rpc.DissolveConversationReq
	DissolveConversationRes                 = chat_rpc.DissolveConversationRes
	EmojiMsg                                = chat_rpc.EmojiMsg
	FileMsg                                 = chat_rpc.FileMsg
	GetConversationsListByIdsReq            = chat_rpc.GetConversationsListByIdsReq
	GetConversationsListByIdsRes            = chat_rpc.GetConversationsListByIdsRes
	GetUserConversationSettingsListByIdsReq = chat_rpc.GetUserConversationSettingsListByIdsReq
	GetUserConversationSettingsListByIdsRes = chat_rpc.GetUserConversationSettingsListByIdsRes
	GetUserConversationVersionsReq          = chat_rpc.GetUserConversationVersionsReq
	GetUserConversationVersionsRes          = chat_rpc.GetUserConversationVersionsRes
	GetUserConversationsReq                 = chat_rpc.GetUserConversationsReq
	GetUserConversationsRes                 = chat_rpc.GetUserConversationsRes
	ImageMsg                                = chat_rpc.ImageMsg
	InitializeConversationReq               = chat_rpc.InitializeConversationReq
	InitializeConversationRes               = chat_rpc.InitializeConversationRes
	Msg                                     = chat_rpc.Msg
	NotificationMsg                         = chat_rpc.NotificationMsg
	RemoveConversationMembersReq            = chat_rpc.RemoveConversationMembersReq
	RemoveConversationMembersRes            = chat_rpc.RemoveConversationMembersRes
	SendMsgReq                              = chat_rpc.SendMsgReq
	SendMsgRes                              = chat_rpc.SendMsgRes
	SendNotificationMessageReq              = chat_rpc.SendNotificationMessageReq
	SendNotificationMessageRes              = chat_rpc.SendNotificationMessageRes
	Sender                                  = chat_rpc.Sender
	TextMsg                                 = chat_rpc.TextMsg
	UpdateConversationReq                   = chat_rpc.UpdateConversationReq
	UpdateConversationRes                   = chat_rpc.UpdateConversationRes
	UserConversationSettingListById         = chat_rpc.UserConversationSettingListById
	UserConversationVersion                 = chat_rpc.UserConversationVersion
	VideoMsg                                = chat_rpc.VideoMsg
	VoiceMsg                                = chat_rpc.VoiceMsg

	Chat interface {
		SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error)
		UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationRes, error)
		BatchUpdateConversation(ctx context.Context, in *BatchUpdateConversationReq, opts ...grpc.CallOption) (*BatchUpdateConversationRes, error)
		GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsRes, error)
		GetConversationsListByIds(ctx context.Context, in *GetConversationsListByIdsReq, opts ...grpc.CallOption) (*GetConversationsListByIdsRes, error)
		GetUserConversationSettingsListByIds(ctx context.Context, in *GetUserConversationSettingsListByIdsReq, opts ...grpc.CallOption) (*GetUserConversationSettingsListByIdsRes, error)
		GetUserConversationVersions(ctx context.Context, in *GetUserConversationVersionsReq, opts ...grpc.CallOption) (*GetUserConversationVersionsRes, error)
		InitializeConversation(ctx context.Context, in *InitializeConversationReq, opts ...grpc.CallOption) (*InitializeConversationRes, error)
		AddConversationMembers(ctx context.Context, in *AddConversationMembersReq, opts ...grpc.CallOption) (*AddConversationMembersRes, error)
		RemoveConversationMembers(ctx context.Context, in *RemoveConversationMembersReq, opts ...grpc.CallOption) (*RemoveConversationMembersRes, error)
		DissolveConversation(ctx context.Context, in *DissolveConversationReq, opts ...grpc.CallOption) (*DissolveConversationRes, error)
		SendNotificationMessage(ctx context.Context, in *SendNotificationMessageReq, opts ...grpc.CallOption) (*SendNotificationMessageRes, error)
	}

	defaultChat struct {
		cli zrpc.Client
	}
)

func NewChat(cli zrpc.Client) Chat {
	return &defaultChat{
		cli: cli,
	}
}

func (m *defaultChat) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.SendMsg(ctx, in, opts...)
}

func (m *defaultChat) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.UpdateConversation(ctx, in, opts...)
}

func (m *defaultChat) BatchUpdateConversation(ctx context.Context, in *BatchUpdateConversationReq, opts ...grpc.CallOption) (*BatchUpdateConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.BatchUpdateConversation(ctx, in, opts...)
}

func (m *defaultChat) GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.GetUserConversations(ctx, in, opts...)
}

func (m *defaultChat) GetConversationsListByIds(ctx context.Context, in *GetConversationsListByIdsReq, opts ...grpc.CallOption) (*GetConversationsListByIdsRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.GetConversationsListByIds(ctx, in, opts...)
}

func (m *defaultChat) GetUserConversationSettingsListByIds(ctx context.Context, in *GetUserConversationSettingsListByIdsReq, opts ...grpc.CallOption) (*GetUserConversationSettingsListByIdsRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.GetUserConversationSettingsListByIds(ctx, in, opts...)
}

func (m *defaultChat) GetUserConversationVersions(ctx context.Context, in *GetUserConversationVersionsReq, opts ...grpc.CallOption) (*GetUserConversationVersionsRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.GetUserConversationVersions(ctx, in, opts...)
}

func (m *defaultChat) InitializeConversation(ctx context.Context, in *InitializeConversationReq, opts ...grpc.CallOption) (*InitializeConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.InitializeConversation(ctx, in, opts...)
}

func (m *defaultChat) AddConversationMembers(ctx context.Context, in *AddConversationMembersReq, opts ...grpc.CallOption) (*AddConversationMembersRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.AddConversationMembers(ctx, in, opts...)
}

func (m *defaultChat) RemoveConversationMembers(ctx context.Context, in *RemoveConversationMembersReq, opts ...grpc.CallOption) (*RemoveConversationMembersRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.RemoveConversationMembers(ctx, in, opts...)
}

func (m *defaultChat) DissolveConversation(ctx context.Context, in *DissolveConversationReq, opts ...grpc.CallOption) (*DissolveConversationRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.DissolveConversation(ctx, in, opts...)
}

func (m *defaultChat) SendNotificationMessage(ctx context.Context, in *SendNotificationMessageReq, opts ...grpc.CallOption) (*SendNotificationMessageRes, error) {
	client := chat_rpc.NewChatClient(m.cli.Conn())
	return client.SendNotificationMessage(ctx, in, opts...)
}
