// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"beaver/app/group/group_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/group/create",
				Handler: groupCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/group/delete/:id",
				Handler: groupDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/group/group_mine",
				Handler: group_mineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/group/memberAdd",
				Handler: groupMemberAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/group/memberRemove",
				Handler: groupMemberRemoveHandler(serverCtx),
			},
		},
	)
}
