// Code generated by goctl. DO NOT EDIT.
package types

type CreateDocumentReq struct {
	UserID   string `header:"Beaver-User-Id"`  // 当前用户ID
	Title    string `json:"title,optional"`    // 名称，可选；文件夹默认「新建文件夹」，文档按类型默认「未命名xxx」
	DocType  *int   `json:"docType,optional"`  // 类型：0文件夹 1文档 2表格 3幻灯片 4思维笔记，省略默认1
	SpaceID  string `json:"spaceId,optional"`  // 空间ID，默认个人空间 user:{userId}
	ParentID string `json:"parentId,optional"` // 父文件夹 docId，空为空间根目录
	FileKey  string `json:"fileKey,optional"`  // 初始正文文件 key，仅文档类型可用
}

type CreateDocumentRes struct {
	DocID    string `json:"docId"`    // 节点唯一标识
	Title    string `json:"title"`    // 名称
	DocType  int    `json:"docType"`  // 类型：0文件夹 1文档 2表格 3幻灯片 4思维笔记
	Revision int64  `json:"revision"` // 版本号，初始为1
}

type GetDocumentReq struct {
	UserID string `header:"Beaver-User-Id"` // 当前用户ID
	DocID  string `json:"docId"`            // 文档唯一标识
}

type GetDocumentRes struct {
	DocID     string `json:"docId"`            // 文档唯一标识
	OwnerID   string `json:"ownerId"`          // 文档所有者用户ID
	Title     string `json:"title"`            // 文档标题
	DocType   int    `json:"docType"`          // 文档类型
	FileKey   string `json:"fileKey"`          // 正文文件 key
	FileSize  int64  `json:"fileSize"`         // 正文字节数，来自 file 服务
	FileMd5   string `json:"fileMd5,optional"` // 正文 md5，来自 file 服务
	Revision  int64  `json:"revision"`         // 当前版本号
	Perm      int    `json:"perm"`             // 当前用户权限：1可阅读 2可编辑 3可管理
	UpdatedAt string `json:"updatedAt"`        // 最后更新时间
}

type ListDocumentChildrenItem struct {
	DocID     string `json:"docId"`     // 节点业务 ID
	Title     string `json:"title"`     // 名称
	DocType   int    `json:"docType"`   // 类型：0文件夹 1文档 2表格 3幻灯片 4思维笔记
	SortOrder int    `json:"sortOrder"` // 同级排序权重
	UpdatedAt string `json:"updatedAt"` // 最后更新时间
}

type ListDocumentChildrenReq struct {
	UserID   string `header:"Beaver-User-Id"`  // 当前用户ID
	SpaceID  string `json:"spaceId,optional"`  // 空间ID，默认个人空间 user:{userId}
	ParentID string `json:"parentId,optional"` // 父文件夹 docId，空为空间根目录
}

type ListDocumentChildrenRes struct {
	SpaceID  string                     `json:"spaceId"`  // 空间 ID
	ParentID string                     `json:"parentId"` // 父文件夹 docId，空为根目录
	List     []ListDocumentChildrenItem `json:"list"`     // 子节点列表
}

type MoveDocumentReq struct {
	UserID   string `header:"Beaver-User-Id"`  // 当前用户ID
	DocID    string `json:"docId"`             // 要移动的节点 docId
	ParentID string `json:"parentId,optional"` // 目标父文件夹 docId，空为根目录
}

type MoveDocumentRes struct {
	DocID    string `json:"docId"`    // 节点 docId
	ParentID string `json:"parentId"` // 移动后的父文件夹 docId
}

type RenameDocumentReq struct {
	UserID string `header:"Beaver-User-Id"` // 当前用户ID
	DocID  string `json:"docId"`            // 节点 docId
	Title  string `json:"title"`            // 新名称
}

type RenameDocumentRes struct {
	DocID string `json:"docId"` // 节点 docId
	Title string `json:"title"` // 新名称
}

type SaveDocumentContentReq struct {
	UserID   string `header:"Beaver-User-Id"`  // 当前用户ID
	DocID    string `json:"docId"`             // 文档唯一标识
	FileKey  string `json:"fileKey"`           // 正文文件 key
	Revision int64  `json:"revision,optional"` // 客户端持有的版本号，用于乐观锁
}

type SaveDocumentContentRes struct {
	Revision  int64  `json:"revision"`  // 保存后的新版本号
	UpdatedAt string `json:"updatedAt"` // 最后更新时间
}

type ShareDocumentReq struct {
	UserID         string `header:"Beaver-User-Id"` // 当前用户ID
	DocID          string `json:"docId"`            // 文档唯一标识
	ConversationID string `json:"conversationId"`   // 目标会话ID
	MessageID      string `json:"messageId"`        // 客户端生成的消息ID
}

type ShareDocumentRes struct {
	MessageID string `json:"messageId"` // 发送到会话的消息ID
	Seq       int64  `json:"seq"`       // 消息在会话内的序列号
}
