// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group_rpc.proto

package group

import (
	"context"

	"beaver/app/group/group_rpc/types/group_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGroupMemberReq                = group_rpc.AddGroupMemberReq
	AddGroupMemberRes                = group_rpc.AddGroupMemberRes
	CanSendGroupMessageReq           = group_rpc.CanSendGroupMessageReq
	CanSendGroupMessageRes           = group_rpc.CanSendGroupMessageRes
	GetGroupJoinRequestsListByIdsReq = group_rpc.GetGroupJoinRequestsListByIdsReq
	GetGroupJoinRequestsListByIdsRes = group_rpc.GetGroupJoinRequestsListByIdsRes
	GetGroupMembersListByIdsReq      = group_rpc.GetGroupMembersListByIdsReq
	GetGroupMembersListByIdsRes      = group_rpc.GetGroupMembersListByIdsRes
	GetGroupMembersReq               = group_rpc.GetGroupMembersReq
	GetGroupMembersRes               = group_rpc.GetGroupMembersRes
	GetGroupsListByIdsReq            = group_rpc.GetGroupsListByIdsReq
	GetGroupsListByIdsRes            = group_rpc.GetGroupsListByIdsRes
	GetUserGroupIDsReq               = group_rpc.GetUserGroupIDsReq
	GetUserGroupIDsRes               = group_rpc.GetUserGroupIDsRes
	GetUserGroupMembersReq           = group_rpc.GetUserGroupMembersReq
	GetUserGroupMembersRes           = group_rpc.GetUserGroupMembersRes
	GetUserGroupRequestVersionsReq   = group_rpc.GetUserGroupRequestVersionsReq
	GetUserGroupRequestVersionsRes   = group_rpc.GetUserGroupRequestVersionsRes
	GroupItem                        = group_rpc.GroupItem
	GroupJoinRequestListById         = group_rpc.GroupJoinRequestListById
	GroupListById                    = group_rpc.GroupListById
	GroupMemberInfo                  = group_rpc.GroupMemberInfo
	GroupMemberItem                  = group_rpc.GroupMemberItem
	GroupMemberListById              = group_rpc.GroupMemberListById
	GroupRequestVersionItem          = group_rpc.GroupRequestVersionItem
	ListGroupMembersReq              = group_rpc.ListGroupMembersReq
	ListGroupMembersRes              = group_rpc.ListGroupMembersRes
	ListGroupsReq                    = group_rpc.ListGroupsReq
	ListGroupsRes                    = group_rpc.ListGroupsRes
	RemoveGroupMemberReq             = group_rpc.RemoveGroupMemberReq
	RemoveGroupMemberRes             = group_rpc.RemoveGroupMemberRes
	UpdateGroupMemberReq             = group_rpc.UpdateGroupMemberReq
	UpdateGroupMemberRes             = group_rpc.UpdateGroupMemberRes
	UpdateGroupReq                   = group_rpc.UpdateGroupReq
	UpdateGroupRes                   = group_rpc.UpdateGroupRes

	Group interface {
		GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersRes, error)
		GetUserGroupMembers(ctx context.Context, in *GetUserGroupMembersReq, opts ...grpc.CallOption) (*GetUserGroupMembersRes, error)
		GetUserGroupIDs(ctx context.Context, in *GetUserGroupIDsReq, opts ...grpc.CallOption) (*GetUserGroupIDsRes, error)
		GetGroupsListByIds(ctx context.Context, in *GetGroupsListByIdsReq, opts ...grpc.CallOption) (*GetGroupsListByIdsRes, error)
		GetGroupMembersListByIds(ctx context.Context, in *GetGroupMembersListByIdsReq, opts ...grpc.CallOption) (*GetGroupMembersListByIdsRes, error)
		GetGroupJoinRequestsListByIds(ctx context.Context, in *GetGroupJoinRequestsListByIdsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsListByIdsRes, error)
		GetUserGroupRequestVersions(ctx context.Context, in *GetUserGroupRequestVersionsReq, opts ...grpc.CallOption) (*GetUserGroupRequestVersionsRes, error)
		CanSendGroupMessage(ctx context.Context, in *CanSendGroupMessageReq, opts ...grpc.CallOption) (*CanSendGroupMessageRes, error)
		AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberRes, error)
		RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*RemoveGroupMemberRes, error)
		ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsRes, error)
		UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupRes, error)
		ListGroupMembers(ctx context.Context, in *ListGroupMembersReq, opts ...grpc.CallOption) (*ListGroupMembersRes, error)
		UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberRes, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

func (m *defaultGroup) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}

func (m *defaultGroup) GetUserGroupMembers(ctx context.Context, in *GetUserGroupMembersReq, opts ...grpc.CallOption) (*GetUserGroupMembersRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetUserGroupMembers(ctx, in, opts...)
}

func (m *defaultGroup) GetUserGroupIDs(ctx context.Context, in *GetUserGroupIDsReq, opts ...grpc.CallOption) (*GetUserGroupIDsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetUserGroupIDs(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupsListByIds(ctx context.Context, in *GetGroupsListByIdsReq, opts ...grpc.CallOption) (*GetGroupsListByIdsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetGroupsListByIds(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupMembersListByIds(ctx context.Context, in *GetGroupMembersListByIdsReq, opts ...grpc.CallOption) (*GetGroupMembersListByIdsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetGroupMembersListByIds(ctx, in, opts...)
}

func (m *defaultGroup) GetGroupJoinRequestsListByIds(ctx context.Context, in *GetGroupJoinRequestsListByIdsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsListByIdsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetGroupJoinRequestsListByIds(ctx, in, opts...)
}

func (m *defaultGroup) GetUserGroupRequestVersions(ctx context.Context, in *GetUserGroupRequestVersionsReq, opts ...grpc.CallOption) (*GetUserGroupRequestVersionsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.GetUserGroupRequestVersions(ctx, in, opts...)
}

func (m *defaultGroup) CanSendGroupMessage(ctx context.Context, in *CanSendGroupMessageReq, opts ...grpc.CallOption) (*CanSendGroupMessageRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.CanSendGroupMessage(ctx, in, opts...)
}

func (m *defaultGroup) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.AddGroupMember(ctx, in, opts...)
}

func (m *defaultGroup) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*RemoveGroupMemberRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.RemoveGroupMember(ctx, in, opts...)
}

func (m *defaultGroup) ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.ListGroups(ctx, in, opts...)
}

func (m *defaultGroup) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.UpdateGroup(ctx, in, opts...)
}

func (m *defaultGroup) ListGroupMembers(ctx context.Context, in *ListGroupMembersReq, opts ...grpc.CallOption) (*ListGroupMembersRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.ListGroupMembers(ctx, in, opts...)
}

func (m *defaultGroup) UpdateGroupMember(ctx context.Context, in *UpdateGroupMemberReq, opts ...grpc.CallOption) (*UpdateGroupMemberRes, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.UpdateGroupMember(ctx, in, opts...)
}
