// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"beaver/app/auth/auth_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户认证
				Method:  http.MethodGet,
				Path:    "/api/auth/authentication",
				Handler: authenticationHandler(serverCtx),
			},
			{
				// 邮箱登录
				Method:  http.MethodPost,
				Path:    "/api/auth/email_login",
				Handler: emailLoginHandler(serverCtx),
			},
			{
				// 邮箱密码登录
				Method:  http.MethodPost,
				Path:    "/api/auth/email_password_login",
				Handler: emailPasswordLoginHandler(serverCtx),
			},
			{
				// 邮箱注册
				Method:  http.MethodPost,
				Path:    "/api/auth/email_register",
				Handler: emailRegisterHandler(serverCtx),
			},
			{
				// 获取邮箱验证码
				Method:  http.MethodPost,
				Path:    "/api/auth/emailcode",
				Handler: getEmailCodeHandler(serverCtx),
			},
			{
				// 用户登出
				Method:  http.MethodPost,
				Path:    "/api/auth/logout",
				Handler: logoutHandler(serverCtx),
			},
			{
				// 手机号登录
				Method:  http.MethodPost,
				Path:    "/api/auth/phone_login",
				Handler: phoneLoginHandler(serverCtx),
			},
			{
				// 手机号注册
				Method:  http.MethodPost,
				Path:    "/api/auth/phone_register",
				Handler: phoneRegisterHandler(serverCtx),
			},
			{
				// 获取手机验证码
				Method:  http.MethodPost,
				Path:    "/api/auth/phonecode",
				Handler: getPhoneCodeHandler(serverCtx),
			},
			{
				// 找回密码（通过邮箱验证码重置密码）
				Method:  http.MethodPost,
				Path:    "/api/auth/reset_password",
				Handler: resetPasswordHandler(serverCtx),
			},
		},
	)
}
