// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: platform_rpc.proto

package platform_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Platform_AdminQueryLogs_FullMethodName           = "/platform_rpc.platform/AdminQueryLogs"
	Platform_CreateApp_FullMethodName                = "/platform_rpc.platform/CreateApp"
	Platform_ListApps_FullMethodName                 = "/platform_rpc.platform/ListApps"
	Platform_CreateArchitecture_FullMethodName       = "/platform_rpc.platform/CreateArchitecture"
	Platform_UpdateArchitecture_FullMethodName       = "/platform_rpc.platform/UpdateArchitecture"
	Platform_ListArchitectures_FullMethodName        = "/platform_rpc.platform/ListArchitectures"
	Platform_CreateVersion_FullMethodName            = "/platform_rpc.platform/CreateVersion"
	Platform_DeleteVersion_FullMethodName            = "/platform_rpc.platform/DeleteVersion"
	Platform_ListVersions_FullMethodName             = "/platform_rpc.platform/ListVersions"
	Platform_ListAppVersions_FullMethodName          = "/platform_rpc.platform/ListAppVersions"
	Platform_UpsertReleasePolicy_FullMethodName      = "/platform_rpc.platform/UpsertReleasePolicy"
	Platform_ListReleasePolicies_FullMethodName      = "/platform_rpc.platform/ListReleasePolicies"
	Platform_SubmitFeedback_FullMethodName           = "/platform_rpc.platform/SubmitFeedback"
	Platform_ListFeedback_FullMethodName             = "/platform_rpc.platform/ListFeedback"
	Platform_GetFeedback_FullMethodName              = "/platform_rpc.platform/GetFeedback"
	Platform_HandleFeedback_FullMethodName           = "/platform_rpc.platform/HandleFeedback"
	Platform_DeleteFeedback_FullMethodName           = "/platform_rpc.platform/DeleteFeedback"
	Platform_SubmitContentReport_FullMethodName      = "/platform_rpc.platform/SubmitContentReport"
	Platform_ListContentReports_FullMethodName       = "/platform_rpc.platform/ListContentReports"
	Platform_GetContentReport_FullMethodName         = "/platform_rpc.platform/GetContentReport"
	Platform_UpdateContentReports_FullMethodName     = "/platform_rpc.platform/UpdateContentReports"
	Platform_CreateWorkbenchApp_FullMethodName       = "/platform_rpc.platform/CreateWorkbenchApp"
	Platform_UpdateWorkbenchApp_FullMethodName       = "/platform_rpc.platform/UpdateWorkbenchApp"
	Platform_DeleteWorkbenchApp_FullMethodName       = "/platform_rpc.platform/DeleteWorkbenchApp"
	Platform_GetWorkbenchApp_FullMethodName          = "/platform_rpc.platform/GetWorkbenchApp"
	Platform_ListWorkbenchApps_FullMethodName        = "/platform_rpc.platform/ListWorkbenchApps"
	Platform_ListEnabledWorkbenchApps_FullMethodName = "/platform_rpc.platform/ListEnabledWorkbenchApps"
)

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformClient interface {
	AdminQueryLogs(ctx context.Context, in *AdminQueryLogsReq, opts ...grpc.CallOption) (*AdminQueryLogsRes, error)
	CreateApp(ctx context.Context, in *CreateAppReq, opts ...grpc.CallOption) (*CreateAppRes, error)
	ListApps(ctx context.Context, in *ListAppsReq, opts ...grpc.CallOption) (*ListAppsRes, error)
	CreateArchitecture(ctx context.Context, in *CreateArchitectureReq, opts ...grpc.CallOption) (*CreateArchitectureRes, error)
	UpdateArchitecture(ctx context.Context, in *UpdateArchitectureReq, opts ...grpc.CallOption) (*UpdateArchitectureRes, error)
	ListArchitectures(ctx context.Context, in *ListArchitecturesReq, opts ...grpc.CallOption) (*ListArchitecturesRes, error)
	CreateVersion(ctx context.Context, in *CreateVersionReq, opts ...grpc.CallOption) (*CreateVersionRes, error)
	DeleteVersion(ctx context.Context, in *DeleteVersionReq, opts ...grpc.CallOption) (*DeleteVersionRes, error)
	ListVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsRes, error)
	ListAppVersions(ctx context.Context, in *ListAppVersionsReq, opts ...grpc.CallOption) (*ListAppVersionsRes, error)
	UpsertReleasePolicy(ctx context.Context, in *UpsertReleasePolicyReq, opts ...grpc.CallOption) (*UpsertReleasePolicyRes, error)
	ListReleasePolicies(ctx context.Context, in *ListReleasePoliciesReq, opts ...grpc.CallOption) (*ListReleasePoliciesRes, error)
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackRes, error)
	ListFeedback(ctx context.Context, in *ListFeedbackReq, opts ...grpc.CallOption) (*ListFeedbackRes, error)
	GetFeedback(ctx context.Context, in *GetFeedbackReq, opts ...grpc.CallOption) (*GetFeedbackRes, error)
	HandleFeedback(ctx context.Context, in *HandleFeedbackReq, opts ...grpc.CallOption) (*HandleFeedbackRes, error)
	DeleteFeedback(ctx context.Context, in *DeleteFeedbackReq, opts ...grpc.CallOption) (*DeleteFeedbackRes, error)
	SubmitContentReport(ctx context.Context, in *SubmitContentReportReq, opts ...grpc.CallOption) (*SubmitContentReportRes, error)
	ListContentReports(ctx context.Context, in *ListContentReportsReq, opts ...grpc.CallOption) (*ListContentReportsRes, error)
	GetContentReport(ctx context.Context, in *GetContentReportReq, opts ...grpc.CallOption) (*GetContentReportRes, error)
	UpdateContentReports(ctx context.Context, in *UpdateContentReportsReq, opts ...grpc.CallOption) (*UpdateContentReportsRes, error)
	CreateWorkbenchApp(ctx context.Context, in *CreateWorkbenchAppReq, opts ...grpc.CallOption) (*CreateWorkbenchAppRes, error)
	UpdateWorkbenchApp(ctx context.Context, in *UpdateWorkbenchAppReq, opts ...grpc.CallOption) (*UpdateWorkbenchAppRes, error)
	DeleteWorkbenchApp(ctx context.Context, in *DeleteWorkbenchAppReq, opts ...grpc.CallOption) (*DeleteWorkbenchAppRes, error)
	GetWorkbenchApp(ctx context.Context, in *GetWorkbenchAppReq, opts ...grpc.CallOption) (*GetWorkbenchAppRes, error)
	ListWorkbenchApps(ctx context.Context, in *ListWorkbenchAppsReq, opts ...grpc.CallOption) (*ListWorkbenchAppsRes, error)
	ListEnabledWorkbenchApps(ctx context.Context, in *ListEnabledWorkbenchAppsReq, opts ...grpc.CallOption) (*ListEnabledWorkbenchAppsRes, error)
}

type platformClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformClient(cc grpc.ClientConnInterface) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) AdminQueryLogs(ctx context.Context, in *AdminQueryLogsReq, opts ...grpc.CallOption) (*AdminQueryLogsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminQueryLogsRes)
	err := c.cc.Invoke(ctx, Platform_AdminQueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) CreateApp(ctx context.Context, in *CreateAppReq, opts ...grpc.CallOption) (*CreateAppRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppRes)
	err := c.cc.Invoke(ctx, Platform_CreateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListApps(ctx context.Context, in *ListAppsReq, opts ...grpc.CallOption) (*ListAppsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsRes)
	err := c.cc.Invoke(ctx, Platform_ListApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) CreateArchitecture(ctx context.Context, in *CreateArchitectureReq, opts ...grpc.CallOption) (*CreateArchitectureRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArchitectureRes)
	err := c.cc.Invoke(ctx, Platform_CreateArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) UpdateArchitecture(ctx context.Context, in *UpdateArchitectureReq, opts ...grpc.CallOption) (*UpdateArchitectureRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArchitectureRes)
	err := c.cc.Invoke(ctx, Platform_UpdateArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListArchitectures(ctx context.Context, in *ListArchitecturesReq, opts ...grpc.CallOption) (*ListArchitecturesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchitecturesRes)
	err := c.cc.Invoke(ctx, Platform_ListArchitectures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) CreateVersion(ctx context.Context, in *CreateVersionReq, opts ...grpc.CallOption) (*CreateVersionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVersionRes)
	err := c.cc.Invoke(ctx, Platform_CreateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) DeleteVersion(ctx context.Context, in *DeleteVersionReq, opts ...grpc.CallOption) (*DeleteVersionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVersionRes)
	err := c.cc.Invoke(ctx, Platform_DeleteVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsRes)
	err := c.cc.Invoke(ctx, Platform_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListAppVersions(ctx context.Context, in *ListAppVersionsReq, opts ...grpc.CallOption) (*ListAppVersionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppVersionsRes)
	err := c.cc.Invoke(ctx, Platform_ListAppVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) UpsertReleasePolicy(ctx context.Context, in *UpsertReleasePolicyReq, opts ...grpc.CallOption) (*UpsertReleasePolicyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertReleasePolicyRes)
	err := c.cc.Invoke(ctx, Platform_UpsertReleasePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListReleasePolicies(ctx context.Context, in *ListReleasePoliciesReq, opts ...grpc.CallOption) (*ListReleasePoliciesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReleasePoliciesRes)
	err := c.cc.Invoke(ctx, Platform_ListReleasePolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFeedbackRes)
	err := c.cc.Invoke(ctx, Platform_SubmitFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListFeedback(ctx context.Context, in *ListFeedbackReq, opts ...grpc.CallOption) (*ListFeedbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedbackRes)
	err := c.cc.Invoke(ctx, Platform_ListFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetFeedback(ctx context.Context, in *GetFeedbackReq, opts ...grpc.CallOption) (*GetFeedbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedbackRes)
	err := c.cc.Invoke(ctx, Platform_GetFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) HandleFeedback(ctx context.Context, in *HandleFeedbackReq, opts ...grpc.CallOption) (*HandleFeedbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleFeedbackRes)
	err := c.cc.Invoke(ctx, Platform_HandleFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) DeleteFeedback(ctx context.Context, in *DeleteFeedbackReq, opts ...grpc.CallOption) (*DeleteFeedbackRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeedbackRes)
	err := c.cc.Invoke(ctx, Platform_DeleteFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) SubmitContentReport(ctx context.Context, in *SubmitContentReportReq, opts ...grpc.CallOption) (*SubmitContentReportRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitContentReportRes)
	err := c.cc.Invoke(ctx, Platform_SubmitContentReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListContentReports(ctx context.Context, in *ListContentReportsReq, opts ...grpc.CallOption) (*ListContentReportsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentReportsRes)
	err := c.cc.Invoke(ctx, Platform_ListContentReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetContentReport(ctx context.Context, in *GetContentReportReq, opts ...grpc.CallOption) (*GetContentReportRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentReportRes)
	err := c.cc.Invoke(ctx, Platform_GetContentReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) UpdateContentReports(ctx context.Context, in *UpdateContentReportsReq, opts ...grpc.CallOption) (*UpdateContentReportsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContentReportsRes)
	err := c.cc.Invoke(ctx, Platform_UpdateContentReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) CreateWorkbenchApp(ctx context.Context, in *CreateWorkbenchAppReq, opts ...grpc.CallOption) (*CreateWorkbenchAppRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkbenchAppRes)
	err := c.cc.Invoke(ctx, Platform_CreateWorkbenchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) UpdateWorkbenchApp(ctx context.Context, in *UpdateWorkbenchAppReq, opts ...grpc.CallOption) (*UpdateWorkbenchAppRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkbenchAppRes)
	err := c.cc.Invoke(ctx, Platform_UpdateWorkbenchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) DeleteWorkbenchApp(ctx context.Context, in *DeleteWorkbenchAppReq, opts ...grpc.CallOption) (*DeleteWorkbenchAppRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkbenchAppRes)
	err := c.cc.Invoke(ctx, Platform_DeleteWorkbenchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetWorkbenchApp(ctx context.Context, in *GetWorkbenchAppReq, opts ...grpc.CallOption) (*GetWorkbenchAppRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkbenchAppRes)
	err := c.cc.Invoke(ctx, Platform_GetWorkbenchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListWorkbenchApps(ctx context.Context, in *ListWorkbenchAppsReq, opts ...grpc.CallOption) (*ListWorkbenchAppsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkbenchAppsRes)
	err := c.cc.Invoke(ctx, Platform_ListWorkbenchApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListEnabledWorkbenchApps(ctx context.Context, in *ListEnabledWorkbenchAppsReq, opts ...grpc.CallOption) (*ListEnabledWorkbenchAppsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnabledWorkbenchAppsRes)
	err := c.cc.Invoke(ctx, Platform_ListEnabledWorkbenchApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
// All implementations must embed UnimplementedPlatformServer
// for forward compatibility.
type PlatformServer interface {
	AdminQueryLogs(context.Context, *AdminQueryLogsReq) (*AdminQueryLogsRes, error)
	CreateApp(context.Context, *CreateAppReq) (*CreateAppRes, error)
	ListApps(context.Context, *ListAppsReq) (*ListAppsRes, error)
	CreateArchitecture(context.Context, *CreateArchitectureReq) (*CreateArchitectureRes, error)
	UpdateArchitecture(context.Context, *UpdateArchitectureReq) (*UpdateArchitectureRes, error)
	ListArchitectures(context.Context, *ListArchitecturesReq) (*ListArchitecturesRes, error)
	CreateVersion(context.Context, *CreateVersionReq) (*CreateVersionRes, error)
	DeleteVersion(context.Context, *DeleteVersionReq) (*DeleteVersionRes, error)
	ListVersions(context.Context, *ListVersionsReq) (*ListVersionsRes, error)
	ListAppVersions(context.Context, *ListAppVersionsReq) (*ListAppVersionsRes, error)
	UpsertReleasePolicy(context.Context, *UpsertReleasePolicyReq) (*UpsertReleasePolicyRes, error)
	ListReleasePolicies(context.Context, *ListReleasePoliciesReq) (*ListReleasePoliciesRes, error)
	SubmitFeedback(context.Context, *SubmitFeedbackReq) (*SubmitFeedbackRes, error)
	ListFeedback(context.Context, *ListFeedbackReq) (*ListFeedbackRes, error)
	GetFeedback(context.Context, *GetFeedbackReq) (*GetFeedbackRes, error)
	HandleFeedback(context.Context, *HandleFeedbackReq) (*HandleFeedbackRes, error)
	DeleteFeedback(context.Context, *DeleteFeedbackReq) (*DeleteFeedbackRes, error)
	SubmitContentReport(context.Context, *SubmitContentReportReq) (*SubmitContentReportRes, error)
	ListContentReports(context.Context, *ListContentReportsReq) (*ListContentReportsRes, error)
	GetContentReport(context.Context, *GetContentReportReq) (*GetContentReportRes, error)
	UpdateContentReports(context.Context, *UpdateContentReportsReq) (*UpdateContentReportsRes, error)
	CreateWorkbenchApp(context.Context, *CreateWorkbenchAppReq) (*CreateWorkbenchAppRes, error)
	UpdateWorkbenchApp(context.Context, *UpdateWorkbenchAppReq) (*UpdateWorkbenchAppRes, error)
	DeleteWorkbenchApp(context.Context, *DeleteWorkbenchAppReq) (*DeleteWorkbenchAppRes, error)
	GetWorkbenchApp(context.Context, *GetWorkbenchAppReq) (*GetWorkbenchAppRes, error)
	ListWorkbenchApps(context.Context, *ListWorkbenchAppsReq) (*ListWorkbenchAppsRes, error)
	ListEnabledWorkbenchApps(context.Context, *ListEnabledWorkbenchAppsReq) (*ListEnabledWorkbenchAppsRes, error)
	mustEmbedUnimplementedPlatformServer()
}

// UnimplementedPlatformServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServer struct{}

func (UnimplementedPlatformServer) AdminQueryLogs(context.Context, *AdminQueryLogsReq) (*AdminQueryLogsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminQueryLogs not implemented")
}
func (UnimplementedPlatformServer) CreateApp(context.Context, *CreateAppReq) (*CreateAppRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (UnimplementedPlatformServer) ListApps(context.Context, *ListAppsReq) (*ListAppsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedPlatformServer) CreateArchitecture(context.Context, *CreateArchitectureReq) (*CreateArchitectureRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArchitecture not implemented")
}
func (UnimplementedPlatformServer) UpdateArchitecture(context.Context, *UpdateArchitectureReq) (*UpdateArchitectureRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArchitecture not implemented")
}
func (UnimplementedPlatformServer) ListArchitectures(context.Context, *ListArchitecturesReq) (*ListArchitecturesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArchitectures not implemented")
}
func (UnimplementedPlatformServer) CreateVersion(context.Context, *CreateVersionReq) (*CreateVersionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVersion not implemented")
}
func (UnimplementedPlatformServer) DeleteVersion(context.Context, *DeleteVersionReq) (*DeleteVersionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVersion not implemented")
}
func (UnimplementedPlatformServer) ListVersions(context.Context, *ListVersionsReq) (*ListVersionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedPlatformServer) ListAppVersions(context.Context, *ListAppVersionsReq) (*ListAppVersionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAppVersions not implemented")
}
func (UnimplementedPlatformServer) UpsertReleasePolicy(context.Context, *UpsertReleasePolicyReq) (*UpsertReleasePolicyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertReleasePolicy not implemented")
}
func (UnimplementedPlatformServer) ListReleasePolicies(context.Context, *ListReleasePoliciesReq) (*ListReleasePoliciesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReleasePolicies not implemented")
}
func (UnimplementedPlatformServer) SubmitFeedback(context.Context, *SubmitFeedbackReq) (*SubmitFeedbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFeedback not implemented")
}
func (UnimplementedPlatformServer) ListFeedback(context.Context, *ListFeedbackReq) (*ListFeedbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeedback not implemented")
}
func (UnimplementedPlatformServer) GetFeedback(context.Context, *GetFeedbackReq) (*GetFeedbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedback not implemented")
}
func (UnimplementedPlatformServer) HandleFeedback(context.Context, *HandleFeedbackReq) (*HandleFeedbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleFeedback not implemented")
}
func (UnimplementedPlatformServer) DeleteFeedback(context.Context, *DeleteFeedbackReq) (*DeleteFeedbackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeedback not implemented")
}
func (UnimplementedPlatformServer) SubmitContentReport(context.Context, *SubmitContentReportReq) (*SubmitContentReportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitContentReport not implemented")
}
func (UnimplementedPlatformServer) ListContentReports(context.Context, *ListContentReportsReq) (*ListContentReportsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentReports not implemented")
}
func (UnimplementedPlatformServer) GetContentReport(context.Context, *GetContentReportReq) (*GetContentReportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentReport not implemented")
}
func (UnimplementedPlatformServer) UpdateContentReports(context.Context, *UpdateContentReportsReq) (*UpdateContentReportsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContentReports not implemented")
}
func (UnimplementedPlatformServer) CreateWorkbenchApp(context.Context, *CreateWorkbenchAppReq) (*CreateWorkbenchAppRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkbenchApp not implemented")
}
func (UnimplementedPlatformServer) UpdateWorkbenchApp(context.Context, *UpdateWorkbenchAppReq) (*UpdateWorkbenchAppRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkbenchApp not implemented")
}
func (UnimplementedPlatformServer) DeleteWorkbenchApp(context.Context, *DeleteWorkbenchAppReq) (*DeleteWorkbenchAppRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkbenchApp not implemented")
}
func (UnimplementedPlatformServer) GetWorkbenchApp(context.Context, *GetWorkbenchAppReq) (*GetWorkbenchAppRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkbenchApp not implemented")
}
func (UnimplementedPlatformServer) ListWorkbenchApps(context.Context, *ListWorkbenchAppsReq) (*ListWorkbenchAppsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkbenchApps not implemented")
}
func (UnimplementedPlatformServer) ListEnabledWorkbenchApps(context.Context, *ListEnabledWorkbenchAppsReq) (*ListEnabledWorkbenchAppsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnabledWorkbenchApps not implemented")
}
func (UnimplementedPlatformServer) mustEmbedUnimplementedPlatformServer() {}
func (UnimplementedPlatformServer) testEmbeddedByValue()                  {}

// UnsafePlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServer will
// result in compilation errors.
type UnsafePlatformServer interface {
	mustEmbedUnimplementedPlatformServer()
}

func RegisterPlatformServer(s grpc.ServiceRegistrar, srv PlatformServer) {
	// If the following call pancis, it indicates UnimplementedPlatformServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Platform_ServiceDesc, srv)
}

func _Platform_AdminQueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminQueryLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).AdminQueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_AdminQueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).AdminQueryLogs(ctx, req.(*AdminQueryLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_CreateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CreateApp(ctx, req.(*CreateAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListApps(ctx, req.(*ListAppsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_CreateArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArchitectureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CreateArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_CreateArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CreateArchitecture(ctx, req.(*CreateArchitectureReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_UpdateArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArchitectureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).UpdateArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_UpdateArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).UpdateArchitecture(ctx, req.(*UpdateArchitectureReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListArchitectures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchitecturesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListArchitectures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListArchitectures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListArchitectures(ctx, req.(*ListArchitecturesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_CreateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CreateVersion(ctx, req.(*CreateVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_DeleteVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).DeleteVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_DeleteVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).DeleteVersion(ctx, req.(*DeleteVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListVersions(ctx, req.(*ListVersionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListAppVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppVersionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListAppVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListAppVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListAppVersions(ctx, req.(*ListAppVersionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_UpsertReleasePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertReleasePolicyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).UpsertReleasePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_UpsertReleasePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).UpsertReleasePolicy(ctx, req.(*UpsertReleasePolicyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListReleasePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleasePoliciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListReleasePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListReleasePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListReleasePolicies(ctx, req.(*ListReleasePoliciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_SubmitFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).SubmitFeedback(ctx, req.(*SubmitFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListFeedback(ctx, req.(*ListFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetFeedback(ctx, req.(*GetFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_HandleFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).HandleFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_HandleFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).HandleFeedback(ctx, req.(*HandleFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_DeleteFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).DeleteFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_DeleteFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).DeleteFeedback(ctx, req.(*DeleteFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_SubmitContentReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitContentReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).SubmitContentReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_SubmitContentReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).SubmitContentReport(ctx, req.(*SubmitContentReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListContentReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListContentReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListContentReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListContentReports(ctx, req.(*ListContentReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetContentReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetContentReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetContentReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetContentReport(ctx, req.(*GetContentReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_UpdateContentReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).UpdateContentReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_UpdateContentReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).UpdateContentReports(ctx, req.(*UpdateContentReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_CreateWorkbenchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkbenchAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CreateWorkbenchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_CreateWorkbenchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CreateWorkbenchApp(ctx, req.(*CreateWorkbenchAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_UpdateWorkbenchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkbenchAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).UpdateWorkbenchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_UpdateWorkbenchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).UpdateWorkbenchApp(ctx, req.(*UpdateWorkbenchAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_DeleteWorkbenchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkbenchAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).DeleteWorkbenchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_DeleteWorkbenchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).DeleteWorkbenchApp(ctx, req.(*DeleteWorkbenchAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetWorkbenchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkbenchAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetWorkbenchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetWorkbenchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetWorkbenchApp(ctx, req.(*GetWorkbenchAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListWorkbenchApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkbenchAppsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListWorkbenchApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListWorkbenchApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListWorkbenchApps(ctx, req.(*ListWorkbenchAppsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListEnabledWorkbenchApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnabledWorkbenchAppsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListEnabledWorkbenchApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListEnabledWorkbenchApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListEnabledWorkbenchApps(ctx, req.(*ListEnabledWorkbenchAppsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Platform_ServiceDesc is the grpc.ServiceDesc for Platform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Platform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_rpc.platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminQueryLogs",
			Handler:    _Platform_AdminQueryLogs_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _Platform_CreateApp_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _Platform_ListApps_Handler,
		},
		{
			MethodName: "CreateArchitecture",
			Handler:    _Platform_CreateArchitecture_Handler,
		},
		{
			MethodName: "UpdateArchitecture",
			Handler:    _Platform_UpdateArchitecture_Handler,
		},
		{
			MethodName: "ListArchitectures",
			Handler:    _Platform_ListArchitectures_Handler,
		},
		{
			MethodName: "CreateVersion",
			Handler:    _Platform_CreateVersion_Handler,
		},
		{
			MethodName: "DeleteVersion",
			Handler:    _Platform_DeleteVersion_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _Platform_ListVersions_Handler,
		},
		{
			MethodName: "ListAppVersions",
			Handler:    _Platform_ListAppVersions_Handler,
		},
		{
			MethodName: "UpsertReleasePolicy",
			Handler:    _Platform_UpsertReleasePolicy_Handler,
		},
		{
			MethodName: "ListReleasePolicies",
			Handler:    _Platform_ListReleasePolicies_Handler,
		},
		{
			MethodName: "SubmitFeedback",
			Handler:    _Platform_SubmitFeedback_Handler,
		},
		{
			MethodName: "ListFeedback",
			Handler:    _Platform_ListFeedback_Handler,
		},
		{
			MethodName: "GetFeedback",
			Handler:    _Platform_GetFeedback_Handler,
		},
		{
			MethodName: "HandleFeedback",
			Handler:    _Platform_HandleFeedback_Handler,
		},
		{
			MethodName: "DeleteFeedback",
			Handler:    _Platform_DeleteFeedback_Handler,
		},
		{
			MethodName: "SubmitContentReport",
			Handler:    _Platform_SubmitContentReport_Handler,
		},
		{
			MethodName: "ListContentReports",
			Handler:    _Platform_ListContentReports_Handler,
		},
		{
			MethodName: "GetContentReport",
			Handler:    _Platform_GetContentReport_Handler,
		},
		{
			MethodName: "UpdateContentReports",
			Handler:    _Platform_UpdateContentReports_Handler,
		},
		{
			MethodName: "CreateWorkbenchApp",
			Handler:    _Platform_CreateWorkbenchApp_Handler,
		},
		{
			MethodName: "UpdateWorkbenchApp",
			Handler:    _Platform_UpdateWorkbenchApp_Handler,
		},
		{
			MethodName: "DeleteWorkbenchApp",
			Handler:    _Platform_DeleteWorkbenchApp_Handler,
		},
		{
			MethodName: "GetWorkbenchApp",
			Handler:    _Platform_GetWorkbenchApp_Handler,
		},
		{
			MethodName: "ListWorkbenchApps",
			Handler:    _Platform_ListWorkbenchApps_Handler,
		},
		{
			MethodName: "ListEnabledWorkbenchApps",
			Handler:    _Platform_ListEnabledWorkbenchApps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_rpc.proto",
}
