// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	emoji "beaver/app/backend/backend_admin/internal/handler/emoji"
	"beaver/app/backend/backend_admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 更新表情图片
				Method:  http.MethodPut,
				Path:    "/admin/emoji/:id",
				Handler: emoji.UpdateEmojiHandler(serverCtx),
			},
			{
				// 删除表情图片
				Method:  http.MethodDelete,
				Path:    "/admin/emoji/:id",
				Handler: emoji.DeleteEmojiHandler(serverCtx),
			},
			{
				// 获取用户收藏的表情图片列表
				Method:  http.MethodGet,
				Path:    "/admin/emoji/collects",
				Handler: emoji.GetEmojiCollectListHandler(serverCtx),
			},
			{
				// 创建表情图片
				Method:  http.MethodPost,
				Path:    "/admin/emoji/create",
				Handler: emoji.CreateEmojiHandler(serverCtx),
			},
			{
				// 获取表情图片列表
				Method:  http.MethodGet,
				Path:    "/admin/emoji/list",
				Handler: emoji.GetEmojiListHandler(serverCtx),
			},
			{
				// 向表情包集合中添加表情图片
				Method:  http.MethodPost,
				Path:    "/admin/emoji/packageaddemoji",
				Handler: emoji.AddEmojiToPackageHandler(serverCtx),
			},
			{
				// 创建表情包集合
				Method:  http.MethodPost,
				Path:    "/admin/emoji/packagecreate",
				Handler: emoji.CreateEmojiPackageHandler(serverCtx),
			},
			{
				// 删除表情包集合
				Method:  http.MethodDelete,
				Path:    "/admin/emoji/packagedelete",
				Handler: emoji.DeleteEmojiPackageHandler(serverCtx),
			},
			{
				// 获取表情包内的表情图片列表
				Method:  http.MethodGet,
				Path:    "/admin/emoji/packageemojis",
				Handler: emoji.GetEmojiPackageEmojisHandler(serverCtx),
			},
			{
				// 从表情包集合中移除表情图片
				Method:  http.MethodDelete,
				Path:    "/admin/emoji/packageremoveemoji",
				Handler: emoji.RemoveEmojiFromPackageHandler(serverCtx),
			},
			{
				// 获取表情包集合列表
				Method:  http.MethodGet,
				Path:    "/admin/emoji/packages",
				Handler: emoji.GetEmojiPackageListHandler(serverCtx),
			},
			{
				// 更新表情包集合
				Method:  http.MethodPut,
				Path:    "/admin/emoji/packageupdate",
				Handler: emoji.UpdateEmojiPackageHandler(serverCtx),
			},
		},
	)
}
