// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.3
// source: file_rpc.proto

package file_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件详情请求
type GetFileDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=fileKey,proto3" json:"fileKey,omitempty"` // 文件ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileDetailReq) Reset() {
	*x = GetFileDetailReq{}
	mi := &file_file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDetailReq) ProtoMessage() {}

func (x *GetFileDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDetailReq.ProtoReflect.Descriptor instead.
func (*GetFileDetailReq) Descriptor() ([]byte, []int) {
	return file_file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileDetailReq) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

// 文件详情响应
type GetFileDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=fileKey,proto3" json:"fileKey,omitempty"`           // 文件唯一ID
	OriginalName  string                 `protobuf:"bytes,2,opt,name=originalName,proto3" json:"originalName,omitempty"` // 文件名
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                // 文件大小
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                 // 文件实际存储路径
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`                   // 文件MD5
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`                 // 文件类型
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`       // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`       // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileDetailRes) Reset() {
	*x = GetFileDetailRes{}
	mi := &file_file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDetailRes) ProtoMessage() {}

func (x *GetFileDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDetailRes.ProtoReflect.Descriptor instead.
func (*GetFileDetailRes) Descriptor() ([]byte, []int) {
	return file_file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileDetailRes) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *GetFileDetailRes) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *GetFileDetailRes) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetFileDetailRes) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileDetailRes) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *GetFileDetailRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetFileDetailRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetFileDetailRes) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 获取七牛云上传token请求
type GetQiniuUploadTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQiniuUploadTokenReq) Reset() {
	*x = GetQiniuUploadTokenReq{}
	mi := &file_file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQiniuUploadTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQiniuUploadTokenReq) ProtoMessage() {}

func (x *GetQiniuUploadTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQiniuUploadTokenReq.ProtoReflect.Descriptor instead.
func (*GetQiniuUploadTokenReq) Descriptor() ([]byte, []int) {
	return file_file_rpc_proto_rawDescGZIP(), []int{2}
}

// 获取七牛云上传token响应
type GetQiniuUploadTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadToken   string                 `protobuf:"bytes,1,opt,name=uploadToken,proto3" json:"uploadToken,omitempty"` // 上传token
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`    // token过期时间 (秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQiniuUploadTokenRes) Reset() {
	*x = GetQiniuUploadTokenRes{}
	mi := &file_file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQiniuUploadTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQiniuUploadTokenRes) ProtoMessage() {}

func (x *GetQiniuUploadTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQiniuUploadTokenRes.ProtoReflect.Descriptor instead.
func (*GetQiniuUploadTokenRes) Descriptor() ([]byte, []int) {
	return file_file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetQiniuUploadTokenRes) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

func (x *GetQiniuUploadTokenRes) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_file_rpc_proto protoreflect.FileDescriptor

const file_file_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0efile_rpc.proto\x12\bfile_rpc\",\n" +
	"\x10GetFileDetailReq\x12\x18\n" +
	"\afileKey\x18\x01 \x01(\tR\afileKey\"\xda\x01\n" +
	"\x10GetFileDetailRes\x12\x18\n" +
	"\afileKey\x18\x01 \x01(\tR\afileKey\x12\"\n" +
	"\foriginalName\x18\x02 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\x18\n" +
	"\x16GetQiniuUploadTokenReq\"X\n" +
	"\x16GetQiniuUploadTokenRes\x12 \n" +
	"\vuploadToken\x18\x01 \x01(\tR\vuploadToken\x12\x1c\n" +
	"\texpiresIn\x18\x02 \x01(\x03R\texpiresIn2\xaa\x01\n" +
	"\x04file\x12G\n" +
	"\rGetFileDetail\x12\x1a.file_rpc.GetFileDetailReq\x1a\x1a.file_rpc.GetFileDetailRes\x12Y\n" +
	"\x13GetQiniuUploadToken\x12 .file_rpc.GetQiniuUploadTokenReq\x1a .file_rpc.GetQiniuUploadTokenResB\fZ\n" +
	"./file_rpcb\x06proto3"

var (
	file_file_rpc_proto_rawDescOnce sync.Once
	file_file_rpc_proto_rawDescData []byte
)

func file_file_rpc_proto_rawDescGZIP() []byte {
	file_file_rpc_proto_rawDescOnce.Do(func() {
		file_file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_rpc_proto_rawDesc), len(file_file_rpc_proto_rawDesc)))
	})
	return file_file_rpc_proto_rawDescData
}

var file_file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_rpc_proto_goTypes = []any{
	(*GetFileDetailReq)(nil),       // 0: file_rpc.GetFileDetailReq
	(*GetFileDetailRes)(nil),       // 1: file_rpc.GetFileDetailRes
	(*GetQiniuUploadTokenReq)(nil), // 2: file_rpc.GetQiniuUploadTokenReq
	(*GetQiniuUploadTokenRes)(nil), // 3: file_rpc.GetQiniuUploadTokenRes
}
var file_file_rpc_proto_depIdxs = []int32{
	0, // 0: file_rpc.file.GetFileDetail:input_type -> file_rpc.GetFileDetailReq
	2, // 1: file_rpc.file.GetQiniuUploadToken:input_type -> file_rpc.GetQiniuUploadTokenReq
	1, // 2: file_rpc.file.GetFileDetail:output_type -> file_rpc.GetFileDetailRes
	3, // 3: file_rpc.file.GetQiniuUploadToken:output_type -> file_rpc.GetQiniuUploadTokenRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_rpc_proto_init() }
func file_file_rpc_proto_init() {
	if File_file_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_rpc_proto_rawDesc), len(file_file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_rpc_proto_goTypes,
		DependencyIndexes: file_file_rpc_proto_depIdxs,
		MessageInfos:      file_file_rpc_proto_msgTypes,
	}.Build()
	File_file_rpc_proto = out.File
	file_file_rpc_proto_goTypes = nil
	file_file_rpc_proto_depIdxs = nil
}
