// Code generated by goctl. DO NOT EDIT.
package types

type DeviceInfo struct {
	DeviceID      string `json:"deviceId"`
	DeviceType    string `json:"deviceType"`
	DeviceOS      string `json:"deviceOs"`
	DeviceName    string `json:"deviceName"`
	LastLoginTime string `json:"lastLoginTime"`
	IsActive      bool   `json:"isActive"`
	LastLoginIP   string `json:"lastLoginIp"`
}

type GetDevicesReq struct {
	UserID string `header:"Beaver-User-Id"`
}

type GetDevicesRes struct {
	Devices []DeviceInfo `json:"devices"`
}

type KickDeviceReq struct {
	UserID   string `header:"Beaver-User-Id"`
	DeviceID string `json:"deviceId"`
}

type KickDeviceRes struct {
}

type LogoutReq struct {
	UserID string `header:"Beaver-User-Id"`
}

type LogoutRes struct {
}

type QrcodeScanReq struct {
	Token     string `json:"token"`
	AuthToken string `header:"Token"`
}

type QrcodeScanRes struct {
}
