// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"beaver/app/dictionary/dictionary_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取城市列表
				Method:  http.MethodGet,
				Path:    "/api/dictionary/cities",
				Handler: GetCitiesHandler(serverCtx),
			},
		},
	)
}
