// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: file_rpc.proto

package server

import (
	"context"

	"beaver/app/file/file_rpc/internal/logic"
	"beaver/app/file/file_rpc/internal/svc"
	"beaver/app/file/file_rpc/types/file_rpc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file_rpc.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 通过fileName查询文件详情
func (s *FileServer) GetFileDetail(ctx context.Context, in *file_rpc.GetFileDetailReq) (*file_rpc.GetFileDetailRes, error) {
	l := logic.NewGetFileDetailLogic(ctx, s.svcCtx)
	return l.GetFileDetail(in)
}

// 获取七牛云上传token
func (s *FileServer) GetQiniuUploadToken(ctx context.Context, in *file_rpc.GetQiniuUploadTokenReq) (*file_rpc.GetQiniuUploadTokenRes, error) {
	l := logic.NewGetQiniuUploadTokenLogic(ctx, s.svcCtx)
	return l.GetQiniuUploadToken(in)
}
