// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	app "beaver/app/open/open_portal/internal/handler/app"
	auth "beaver/app/open/open_portal/internal/handler/auth"
	developer "beaver/app/open/open_portal/internal/handler/developer"
	permission "beaver/app/open/open_portal/internal/handler/permission"
	webhook "beaver/app/open/open_portal/internal/handler/webhook"
	"beaver/app/open/open_portal/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取 Bot 配置
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/bot/config",
				Handler: app.GetBotConfigHandler(serverCtx),
			},
			{
				// 更新 Bot 配置
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/bot/config/update",
				Handler: app.UpdateBotConfigHandler(serverCtx),
			},
			{
				// 创建应用
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/create",
				Handler: app.CreateAppHandler(serverCtx),
			},
			{
				// 删除应用
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/delete",
				Handler: app.DeleteAppHandler(serverCtx),
			},
			{
				// 获取应用详情
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/detail",
				Handler: app.GetAppDetailHandler(serverCtx),
			},
			{
				// 获取应用列表
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/list",
				Handler: app.GetAppListHandler(serverCtx),
			},
			{
				// 获取 OAuth 配置
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/oauth/config",
				Handler: app.GetOAuthConfigHandler(serverCtx),
			},
			{
				// 更新 OAuth 配置
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/oauth/config/update",
				Handler: app.UpdateOAuthConfigHandler(serverCtx),
			},
			{
				// 重置应用密钥
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/reset_secret",
				Handler: app.ResetAppSecretHandler(serverCtx),
			},
			{
				// 获取应用权限列表
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/scopes",
				Handler: app.GetAppScopesHandler(serverCtx),
			},
			{
				// 更新应用权限
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/scopes/update",
				Handler: app.UpdateAppScopesHandler(serverCtx),
			},
			{
				// 更新应用
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/update",
				Handler: app.UpdateAppHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取开发者详情
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/developer/:id",
				Handler: developer.GetDeveloperDetailHandler(serverCtx),
			},
			{
				// 申请成为开发者
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/developer/apply",
				Handler: developer.ApplyDeveloperHandler(serverCtx),
			},
			{
				// 审核开发者申请
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/developer/audit",
				Handler: developer.AuditDeveloperHandler(serverCtx),
			},
			{
				// 获取开发者列表
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/developer/list",
				Handler: developer.GetDeveloperListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 配置应用权限
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/app/permission/config",
				Handler: permission.ConfigAppPermissionHandler(serverCtx),
			},
			{
				// 获取应用权限列表
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/app/permissions",
				Handler: permission.GetAppPermissionsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 配置 Webhook
				Method:  http.MethodPost,
				Path:    "/portal/open/v1/webhook/config",
				Handler: webhook.ConfigWebhookHandler(serverCtx),
			},
			{
				// 获取 Webhook 日志
				Method:  http.MethodGet,
				Path:    "/portal/open/v1/webhook/logs",
				Handler: webhook.GetWebhookLogsHandler(serverCtx),
			},
		},
	)
}
