/*
 * Copyright (c) 2024-2026 Beaver IM Team
 * SPDX-License-Identifier: MIT
 * Project: beaver-server
 * https://github.com/wsrh8888/beaver-server
 *
 * 中文：
 * 本文件为海狸 IM（Beaver IM）开源项目源代码。
 * 版权所有 © 2024-2026 Beaver IM Team，基于 MIT 协议授权。
 * 禁止删除、篡改或替换本文件头部版权与许可声明。
 * 使用与商业授权说明：https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * English:
 * This file is part of the Beaver IM open-source project.
 * Copyright (c) 2024-2026 Beaver IM Team. Licensed under the MIT License.
 * Do not remove, alter, or replace this copyright and license header.
 * Usage & commercial licensing: https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * beaver-server-header-v1
 */

// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification_rpc.proto

package notification

import (
	"context"

	"beaver/app/notification/notification_rpc/types/notification_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DisablePushTokenReq      = notification_rpc.DisablePushTokenReq
	DisablePushTokenRes      = notification_rpc.DisablePushTokenRes
	EventVersion             = notification_rpc.EventVersion
	GetEventVersionsReq      = notification_rpc.GetEventVersionsReq
	GetEventVersionsRes      = notification_rpc.GetEventVersionsRes
	GetInboxVersionsReq      = notification_rpc.GetInboxVersionsReq
	GetInboxVersionsRes      = notification_rpc.GetInboxVersionsRes
	GetReadCursorVersionsReq = notification_rpc.GetReadCursorVersionsReq
	GetReadCursorVersionsRes = notification_rpc.GetReadCursorVersionsRes
	InboxVersion             = notification_rpc.InboxVersion
	ListPushTokensReq        = notification_rpc.ListPushTokensReq
	ListPushTokensRes        = notification_rpc.ListPushTokensRes
	PushEventReq             = notification_rpc.PushEventReq
	PushEventRes             = notification_rpc.PushEventRes
	PushTokenInfo            = notification_rpc.PushTokenInfo
	ReadCursorVersion        = notification_rpc.ReadCursorVersion

	Notification interface {
		PushEvent(ctx context.Context, in *PushEventReq, opts ...grpc.CallOption) (*PushEventRes, error)
		GetEventVersions(ctx context.Context, in *GetEventVersionsReq, opts ...grpc.CallOption) (*GetEventVersionsRes, error)
		GetInboxVersions(ctx context.Context, in *GetInboxVersionsReq, opts ...grpc.CallOption) (*GetInboxVersionsRes, error)
		GetReadCursorVersions(ctx context.Context, in *GetReadCursorVersionsReq, opts ...grpc.CallOption) (*GetReadCursorVersionsRes, error)
		ListPushTokens(ctx context.Context, in *ListPushTokensReq, opts ...grpc.CallOption) (*ListPushTokensRes, error)
		DisablePushToken(ctx context.Context, in *DisablePushTokenReq, opts ...grpc.CallOption) (*DisablePushTokenRes, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) PushEvent(ctx context.Context, in *PushEventReq, opts ...grpc.CallOption) (*PushEventRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.PushEvent(ctx, in, opts...)
}

func (m *defaultNotification) GetEventVersions(ctx context.Context, in *GetEventVersionsReq, opts ...grpc.CallOption) (*GetEventVersionsRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.GetEventVersions(ctx, in, opts...)
}

func (m *defaultNotification) GetInboxVersions(ctx context.Context, in *GetInboxVersionsReq, opts ...grpc.CallOption) (*GetInboxVersionsRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.GetInboxVersions(ctx, in, opts...)
}

func (m *defaultNotification) GetReadCursorVersions(ctx context.Context, in *GetReadCursorVersionsReq, opts ...grpc.CallOption) (*GetReadCursorVersionsRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.GetReadCursorVersions(ctx, in, opts...)
}

func (m *defaultNotification) ListPushTokens(ctx context.Context, in *ListPushTokensReq, opts ...grpc.CallOption) (*ListPushTokensRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.ListPushTokens(ctx, in, opts...)
}

func (m *defaultNotification) DisablePushToken(ctx context.Context, in *DisablePushTokenReq, opts ...grpc.CallOption) (*DisablePushTokenRes, error) {
	client := notification_rpc.NewNotificationClient(m.cli.Conn())
	return client.DisablePushToken(ctx, in, opts...)
}
