// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: notification_rpc.proto

package server

import (
	"context"

	"beaver/app/notification/notification_rpc/internal/logic"
	"beaver/app/notification/notification_rpc/internal/svc"
	"beaver/app/notification/notification_rpc/types/notification_rpc"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	notification_rpc.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) PushEvent(ctx context.Context, in *notification_rpc.PushEventReq) (*notification_rpc.PushEventRes, error) {
	l := logic.NewPushEventLogic(ctx, s.svcCtx)
	return l.PushEvent(in)
}

func (s *NotificationServer) GetEventVersions(ctx context.Context, in *notification_rpc.GetEventVersionsReq) (*notification_rpc.GetEventVersionsRes, error) {
	l := logic.NewGetEventVersionsLogic(ctx, s.svcCtx)
	return l.GetEventVersions(in)
}

func (s *NotificationServer) GetInboxVersions(ctx context.Context, in *notification_rpc.GetInboxVersionsReq) (*notification_rpc.GetInboxVersionsRes, error) {
	l := logic.NewGetInboxVersionsLogic(ctx, s.svcCtx)
	return l.GetInboxVersions(in)
}

func (s *NotificationServer) GetReadCursorVersions(ctx context.Context, in *notification_rpc.GetReadCursorVersionsReq) (*notification_rpc.GetReadCursorVersionsRes, error) {
	l := logic.NewGetReadCursorVersionsLogic(ctx, s.svcCtx)
	return l.GetReadCursorVersions(in)
}
