
services:
  notification_rpc:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/notification_rpc:1.0.2
    container_name: notification_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./notificationrpc.yaml:/etc/notificationrpc.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always

