
services:
  notification_rpc:
    image: wsrh8888/notification_rpc:1.0.0
    container_name: notification_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./notificationrpc.yaml:/etc/notificationrpc.yaml:ro
    restart: "no"
    pull_policy: always

