
services:
  open_portal:
    image: wsrh8888/open_portal:1.0.0
    container_name: open_portal
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./open.yaml:/etc/open.yaml:ro
    restart: "no"
    pull_policy: always
