// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: group_rpc.proto

package group_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Group_GetGroupMembers_FullMethodName               = "/group_rpc.group/GetGroupMembers"
	Group_GetUserGroupMembers_FullMethodName           = "/group_rpc.group/GetUserGroupMembers"
	Group_GetUserGroupIDs_FullMethodName               = "/group_rpc.group/GetUserGroupIDs"
	Group_GetGroupsListByIds_FullMethodName            = "/group_rpc.group/GetGroupsListByIds"
	Group_GetGroupMembersListByIds_FullMethodName      = "/group_rpc.group/GetGroupMembersListByIds"
	Group_GetGroupJoinRequestsListByIds_FullMethodName = "/group_rpc.group/GetGroupJoinRequestsListByIds"
	Group_GetUserGroupRequestVersions_FullMethodName   = "/group_rpc.group/GetUserGroupRequestVersions"
)

// GroupClient is the client API for Group service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupClient interface {
	GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersRes, error)
	GetUserGroupMembers(ctx context.Context, in *GetUserGroupMembersReq, opts ...grpc.CallOption) (*GetUserGroupMembersRes, error)
	GetUserGroupIDs(ctx context.Context, in *GetUserGroupIDsReq, opts ...grpc.CallOption) (*GetUserGroupIDsRes, error)
	GetGroupsListByIds(ctx context.Context, in *GetGroupsListByIdsReq, opts ...grpc.CallOption) (*GetGroupsListByIdsRes, error)
	GetGroupMembersListByIds(ctx context.Context, in *GetGroupMembersListByIdsReq, opts ...grpc.CallOption) (*GetGroupMembersListByIdsRes, error)
	GetGroupJoinRequestsListByIds(ctx context.Context, in *GetGroupJoinRequestsListByIdsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsListByIdsRes, error)
	GetUserGroupRequestVersions(ctx context.Context, in *GetUserGroupRequestVersionsReq, opts ...grpc.CallOption) (*GetUserGroupRequestVersionsRes, error)
}

type groupClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupClient(cc grpc.ClientConnInterface) GroupClient {
	return &groupClient{cc}
}

func (c *groupClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersRes)
	err := c.cc.Invoke(ctx, Group_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetUserGroupMembers(ctx context.Context, in *GetUserGroupMembersReq, opts ...grpc.CallOption) (*GetUserGroupMembersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupMembersRes)
	err := c.cc.Invoke(ctx, Group_GetUserGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetUserGroupIDs(ctx context.Context, in *GetUserGroupIDsReq, opts ...grpc.CallOption) (*GetUserGroupIDsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupIDsRes)
	err := c.cc.Invoke(ctx, Group_GetUserGroupIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetGroupsListByIds(ctx context.Context, in *GetGroupsListByIdsReq, opts ...grpc.CallOption) (*GetGroupsListByIdsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupsListByIdsRes)
	err := c.cc.Invoke(ctx, Group_GetGroupsListByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetGroupMembersListByIds(ctx context.Context, in *GetGroupMembersListByIdsReq, opts ...grpc.CallOption) (*GetGroupMembersListByIdsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersListByIdsRes)
	err := c.cc.Invoke(ctx, Group_GetGroupMembersListByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetGroupJoinRequestsListByIds(ctx context.Context, in *GetGroupJoinRequestsListByIdsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsListByIdsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupJoinRequestsListByIdsRes)
	err := c.cc.Invoke(ctx, Group_GetGroupJoinRequestsListByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupClient) GetUserGroupRequestVersions(ctx context.Context, in *GetUserGroupRequestVersionsReq, opts ...grpc.CallOption) (*GetUserGroupRequestVersionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupRequestVersionsRes)
	err := c.cc.Invoke(ctx, Group_GetUserGroupRequestVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServer is the server API for Group service.
// All implementations must embed UnimplementedGroupServer
// for forward compatibility.
type GroupServer interface {
	GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersRes, error)
	GetUserGroupMembers(context.Context, *GetUserGroupMembersReq) (*GetUserGroupMembersRes, error)
	GetUserGroupIDs(context.Context, *GetUserGroupIDsReq) (*GetUserGroupIDsRes, error)
	GetGroupsListByIds(context.Context, *GetGroupsListByIdsReq) (*GetGroupsListByIdsRes, error)
	GetGroupMembersListByIds(context.Context, *GetGroupMembersListByIdsReq) (*GetGroupMembersListByIdsRes, error)
	GetGroupJoinRequestsListByIds(context.Context, *GetGroupJoinRequestsListByIdsReq) (*GetGroupJoinRequestsListByIdsRes, error)
	GetUserGroupRequestVersions(context.Context, *GetUserGroupRequestVersionsReq) (*GetUserGroupRequestVersionsRes, error)
	mustEmbedUnimplementedGroupServer()
}

// UnimplementedGroupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServer struct{}

func (UnimplementedGroupServer) GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedGroupServer) GetUserGroupMembers(context.Context, *GetUserGroupMembersReq) (*GetUserGroupMembersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupMembers not implemented")
}
func (UnimplementedGroupServer) GetUserGroupIDs(context.Context, *GetUserGroupIDsReq) (*GetUserGroupIDsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupIDs not implemented")
}
func (UnimplementedGroupServer) GetGroupsListByIds(context.Context, *GetGroupsListByIdsReq) (*GetGroupsListByIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupsListByIds not implemented")
}
func (UnimplementedGroupServer) GetGroupMembersListByIds(context.Context, *GetGroupMembersListByIdsReq) (*GetGroupMembersListByIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembersListByIds not implemented")
}
func (UnimplementedGroupServer) GetGroupJoinRequestsListByIds(context.Context, *GetGroupJoinRequestsListByIdsReq) (*GetGroupJoinRequestsListByIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupJoinRequestsListByIds not implemented")
}
func (UnimplementedGroupServer) GetUserGroupRequestVersions(context.Context, *GetUserGroupRequestVersionsReq) (*GetUserGroupRequestVersionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupRequestVersions not implemented")
}
func (UnimplementedGroupServer) mustEmbedUnimplementedGroupServer() {}
func (UnimplementedGroupServer) testEmbeddedByValue()               {}

// UnsafeGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServer will
// result in compilation errors.
type UnsafeGroupServer interface {
	mustEmbedUnimplementedGroupServer()
}

func RegisterGroupServer(s grpc.ServiceRegistrar, srv GroupServer) {
	// If the following call pancis, it indicates UnimplementedGroupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Group_ServiceDesc, srv)
}

func _Group_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetGroupMembers(ctx, req.(*GetGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetUserGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetUserGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetUserGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetUserGroupMembers(ctx, req.(*GetUserGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetUserGroupIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetUserGroupIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetUserGroupIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetUserGroupIDs(ctx, req.(*GetUserGroupIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetGroupsListByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsListByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetGroupsListByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetGroupsListByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetGroupsListByIds(ctx, req.(*GetGroupsListByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetGroupMembersListByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersListByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetGroupMembersListByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetGroupMembersListByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetGroupMembersListByIds(ctx, req.(*GetGroupMembersListByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetGroupJoinRequestsListByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupJoinRequestsListByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetGroupJoinRequestsListByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetGroupJoinRequestsListByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetGroupJoinRequestsListByIds(ctx, req.(*GetGroupJoinRequestsListByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Group_GetUserGroupRequestVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupRequestVersionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServer).GetUserGroupRequestVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Group_GetUserGroupRequestVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServer).GetUserGroupRequestVersions(ctx, req.(*GetUserGroupRequestVersionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Group_ServiceDesc is the grpc.ServiceDesc for Group service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Group_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group_rpc.group",
	HandlerType: (*GroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroupMembers",
			Handler:    _Group_GetGroupMembers_Handler,
		},
		{
			MethodName: "GetUserGroupMembers",
			Handler:    _Group_GetUserGroupMembers_Handler,
		},
		{
			MethodName: "GetUserGroupIDs",
			Handler:    _Group_GetUserGroupIDs_Handler,
		},
		{
			MethodName: "GetGroupsListByIds",
			Handler:    _Group_GetGroupsListByIds_Handler,
		},
		{
			MethodName: "GetGroupMembersListByIds",
			Handler:    _Group_GetGroupMembersListByIds_Handler,
		},
		{
			MethodName: "GetGroupJoinRequestsListByIds",
			Handler:    _Group_GetGroupJoinRequestsListByIds_Handler,
		},
		{
			MethodName: "GetUserGroupRequestVersions",
			Handler:    _Group_GetUserGroupRequestVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group_rpc.proto",
}
