
services:
  user_api:
    image: wsrh8888/user_api:1.0.0
    container_name: user_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./user.yaml:/etc/user.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
