// Code generated by goctl. DO NOT EDIT.
package types

type CategoryUnreadItem struct {
	Category string `json:"category"`
	Unread   int64  `json:"unread"`
}

type EventItem struct {
	EventID    string `json:"eventId"`
	EventType  string `json:"eventType"`
	Category   string `json:"category"`
	Version    int64  `json:"version"`
	FromUserID string `json:"fromUserId,optional"`
	TargetID   string `json:"targetId,optional"`
	TargetType string `json:"targetType"`
	Payload    string `json:"payload"` // JSON 字符串
	Priority   int32  `json:"priority"`
	Status     int32  `json:"status"`
	DedupHash  string `json:"dedupHash"`
	CreatedAt  int64  `json:"createdAt"` // ms
	UpdatedAt  int64  `json:"updatedAt"` // ms
}

type InboxItem struct {
	EventID   string `json:"eventId"`
	EventType string `json:"eventType"`
	Category  string `json:"category"`
	Version   int64  `json:"version"`
	IsRead    bool   `json:"isRead"`
	ReadAt    int64  `json:"readAt"` // ms，未读为0
	Status    int32  `json:"status"`
	IsDeleted bool   `json:"isDeleted"` // 用户是否删除该通知
	Silent    bool   `json:"silent"`
	CreatedAt int64  `json:"createdAt"` // ms
	UpdatedAt int64  `json:"updatedAt"` // ms
}

type ReadCursorItem struct {
	Category   string `json:"category"`
	Version    int64  `json:"version"`
	LastReadAt int64  `json:"lastReadAt"` // ms，最后查看该分类的时间
}

type DeleteNotificationReq struct {
	UserID  string `header:"Beaver-User-Id"` // 当前用户ID
	EventID string `json:"eventId"`          // 通知事件ID
}

type DeleteNotificationRes struct {
	Success bool `json:"success"`
}

type GetEventsByIdsReq struct {
	EventIDs []string `json:"eventIds"` // 必填
}

type GetEventsByIdsRes struct {
	Events []EventItem `json:"events"`
}

type GetInboxByIdsReq struct {
	UserID   string   `header:"Beaver-User-Id"` // 当前用户ID
	EventIDs []string `json:"eventIds"`         // 必填
}

type GetInboxByIdsRes struct {
	Inbox []InboxItem `json:"inbox"`
}

type GetReadCursorsReq struct {
	UserID     string   `header:"Beaver-User-Id"`    // 当前用户ID
	Categories []string `json:"categories,optional"` // 可选过滤分类，不传则返回该用户全部
}

type GetReadCursorsRes struct {
	Cursors []ReadCursorItem `json:"cursors"`
}

type GetUnreadSummaryReq struct {
	UserID     string   `header:"Beaver-User-Id"`    // 当前用户ID
	Categories []string `json:"categories,optional"` // 可选分类过滤
	Scenes     []string `json:"scenes,optional"`     // 可选场景过滤（如消息/系统/群公告等）
}

type GetUnreadSummaryRes struct {
	Total int64                `json:"total"`
	ByCat []CategoryUnreadItem `json:"byCat"`
}

type MarkReadByCategoryReq struct {
	UserID   string `header:"Beaver-User-Id"` // 当前用户ID
	Category string `json:"category"`         // 分类，会话级/业务分类
}

type MarkReadByCategoryRes struct {
}

type MarkReadByCursorReq struct {
	UserID    string `header:"Beaver-User-Id"` // 当前用户ID
	Category  string `json:"category"`         // 分类，会话级/业务分类
	ToEventID string `json:"toEventId"`        // 读到此事件ID
	ToVersion int64  `json:"toVersion"`        // 读到此版本
}

type MarkReadByCursorRes struct {
	Affected int64 `json:"affected"` // 成功标记的条数
}

type MarkReadByEventReq struct {
	UserID  string `header:"Beaver-User-Id"` // 当前用户ID
	EventID string `json:"eventId"`          // 通知事件ID
}

type MarkReadByEventRes struct {
}
