
services:
  feedback_api:
    image: wsrh8888/feedback_api:1.0.0
    container_name: feedback_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./feedback.yaml:/etc/feedback.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
