
services:
  file_api:
    image: wsrh8888/file_api:1.0.2
    container_name: file_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./file.yaml:/etc/file.yaml:ro
      - /mnt/static:/mnt/static
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
