Name: file
Host: 0.0.0.0
Port: 20600
Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/beaver?charset=utf8mb4&parseTime=True&loc=Local
Redis:
  Addr: 127.0.0.1:6379
  Password: '123456'
  DB: 0
Etcd: 127.0.0.1:2379
Log:
  Encoding: plain
  TimeFormat: 2006-01-02T15:04:05
  Stat: false
Timeout: 60000
FileMaxSize:
  image: 2    
  video: 10   
  audio: 2    
  archive: 2  
  document: 2 
  unknown: 10
FileSize: 5 # MB
MaxBytes: 5368709120 # 5GB
UploadDir: uploads
Qiniu: 
  AK: your_qiniu_access_key
  SK: your_qiniu_secret_key
  Bucket: your_qiniu_bucket_name
  Domain: 'your_qiniu_domain'
  ExpireTime: 3600 # 签名URL有效期, 单位：秒
# 本地存储配置
Local:
  UploadDir: /mnt/static # 本地文件上传目录(相对路径，相对于程序运行目录)
WhiteList:
  - png
  - jpg
  - jpeg
  - gif
  - webp
  - mp4
BlackList:
  - exe
  - sh
  - bat
UserRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: userrpc.rpc
