// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: datasync_rpc.proto

package datasync

import (
	"context"

	"beaver/app/datasync/datasync_rpc/types/types/datasync_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetSyncCursorReq    = datasync_rpc.GetSyncCursorReq
	GetSyncCursorRes    = datasync_rpc.GetSyncCursorRes
	UpdateSyncCursorReq = datasync_rpc.UpdateSyncCursorReq
	UpdateSyncCursorRes = datasync_rpc.UpdateSyncCursorRes

	Datasync interface {
		// 获取同步游标
		GetSyncCursor(ctx context.Context, in *GetSyncCursorReq, opts ...grpc.CallOption) (*GetSyncCursorRes, error)
		// 更新同步游标
		UpdateSyncCursor(ctx context.Context, in *UpdateSyncCursorReq, opts ...grpc.CallOption) (*UpdateSyncCursorRes, error)
	}

	defaultDatasync struct {
		cli zrpc.Client
	}
)

func NewDatasync(cli zrpc.Client) Datasync {
	return &defaultDatasync{
		cli: cli,
	}
}

// 获取同步游标
func (m *defaultDatasync) GetSyncCursor(ctx context.Context, in *GetSyncCursorReq, opts ...grpc.CallOption) (*GetSyncCursorRes, error) {
	client := datasync_rpc.NewDatasyncClient(m.cli.Conn())
	return client.GetSyncCursor(ctx, in, opts...)
}

// 更新同步游标
func (m *defaultDatasync) UpdateSyncCursor(ctx context.Context, in *UpdateSyncCursorReq, opts ...grpc.CallOption) (*UpdateSyncCursorRes, error) {
	client := datasync_rpc.NewDatasyncClient(m.cli.Conn())
	return client.UpdateSyncCursor(ctx, in, opts...)
}
