
services:
  platform_api:
    image: wsrh8888/platform_api:1.0.0
    container_name: platform_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./platform.yaml:/etc/platform.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always
