/*
 * Copyright (c) 2024-2026 Beaver IM Team
 * SPDX-License-Identifier: MIT
 * Project: beaver-server
 * https://github.com/wsrh8888/beaver-server
 *
 * 中文：
 * 本文件为海狸 IM（Beaver IM）开源项目源代码。
 * 版权所有 © 2024-2026 Beaver IM Team，基于 MIT 协议授权。
 * 禁止删除、篡改或替换本文件头部版权与许可声明。
 * 使用与商业授权说明：https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * English:
 * This file is part of the Beaver IM open-source project.
 * Copyright (c) 2024-2026 Beaver IM Team. Licensed under the MIT License.
 * Do not remove, alter, or replace this copyright and license header.
 * Usage & commercial licensing: https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * beaver-server-header-v1
 */

// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"beaver/app/emoji/emoji_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加表情，并且自动收藏
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/add",
				Handler: AddEmojiHandler(serverCtx),
			},
			{
				// 批量获取用户收藏的表情记录详情（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/collects-by-ids",
				Handler: GetEmojiCollectsByIdsHandler(serverCtx),
			},
			{
				// 批量获取表情详情（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/emojis-by-ids",
				Handler: GetEmojisByIdsHandler(serverCtx),
			},
			{
				// 收藏或者取消收藏表情
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/favoriteEmoji",
				Handler: UpdateFavoriteEmojiHandler(serverCtx),
			},
			{
				// 获取用户收藏的表情列表
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/favoriteList",
				Handler: GetEmojisListHandler(serverCtx),
			},
			{
				// 获取用户收藏的表情包列表
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/favoritePackageList",
				Handler: GetUserFavoritePackagesHandler(serverCtx),
			},
			{
				// 按ID批量查询表情基础信息（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/getEmojisByUuids",
				Handler: GetEmojisByUuidsHandler(serverCtx),
			},
			{
				// 批量获取用户收藏的表情包记录详情（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/package-collects-by-ids",
				Handler: GetEmojiPackageCollectsByIdsHandler(serverCtx),
			},
			{
				// 批量获取表情包内容详情（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/package-contents-by-package-ids",
				Handler: GetEmojiPackageContentsByPackageIdsHandler(serverCtx),
			},
			{
				// 批量获取表情包内容详情（通过relationIds，数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/package-contents-by-relation-ids",
				Handler: GetEmojiPackageContentsByRelationIdsHandler(serverCtx),
			},
			{
				// 收藏或取消收藏表情包
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/packageFavorite",
				Handler: UpdateFavoriteEmojiPackageHandler(serverCtx),
			},
			{
				// 获取表情包详情
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/packageInfo",
				Handler: GetEmojiPackageDetailHandler(serverCtx),
			},
			{
				// 获取表情包列表
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/packageList",
				Handler: GetEmojiPackagesHandler(serverCtx),
			},
			{
				// 批量获取表情包详情（数据库同步）
				Method:  http.MethodPost,
				Path:    "/api/emoji/v1/packages-by-ids",
				Handler: GetEmojiPackagesByIdsHandler(serverCtx),
			},
		},
	)
}
