
services:
  platform_rpc:
    image: wsrh8888/platform_rpc:1.0.0
    container_name: platform_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./platformrpc.yaml:/etc/platformrpc.yaml:ro
    restart: "no"
    pull_policy: always
