// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend_rpc.proto

package server

import (
	"context"

	"beaver/app/friend/friend_rpc/internal/logic"
	"beaver/app/friend/friend_rpc/internal/svc"
	"beaver/app/friend/friend_rpc/types/friend_rpc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend_rpc.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) GetFriendIds(ctx context.Context, in *friend_rpc.GetFriendIdsRequest) (*friend_rpc.GetFriendIdsResponse, error) {
	l := logic.NewGetFriendIdsLogic(ctx, s.svcCtx)
	return l.GetFriendIds(in)
}

func (s *FriendServer) GetFriendVersions(ctx context.Context, in *friend_rpc.GetFriendVersionsReq) (*friend_rpc.GetFriendVersionsRes, error) {
	l := logic.NewGetFriendVersionsLogic(ctx, s.svcCtx)
	return l.GetFriendVersions(in)
}

func (s *FriendServer) GetFriendVerifyVersions(ctx context.Context, in *friend_rpc.GetFriendVerifyVersionsReq) (*friend_rpc.GetFriendVerifyVersionsRes, error) {
	l := logic.NewGetFriendVerifyVersionsLogic(ctx, s.svcCtx)
	return l.GetFriendVerifyVersions(in)
}

func (s *FriendServer) GetFriendsListByIds(ctx context.Context, in *friend_rpc.GetFriendsListByIdsReq) (*friend_rpc.GetFriendsListByIdsRes, error) {
	l := logic.NewGetFriendsListByIdsLogic(ctx, s.svcCtx)
	return l.GetFriendsListByIds(in)
}

func (s *FriendServer) GetFriendVerifiesListByIds(ctx context.Context, in *friend_rpc.GetFriendVerifiesListByIdsReq) (*friend_rpc.GetFriendVerifiesListByIdsRes, error) {
	l := logic.NewGetFriendVerifiesListByIdsLogic(ctx, s.svcCtx)
	return l.GetFriendVerifiesListByIds(in)
}

func (s *FriendServer) GetFriendDetail(ctx context.Context, in *friend_rpc.GetFriendDetailReq) (*friend_rpc.GetFriendDetailRes, error) {
	l := logic.NewGetFriendDetailLogic(ctx, s.svcCtx)
	return l.GetFriendDetail(in)
}

func (s *FriendServer) IsFriend(ctx context.Context, in *friend_rpc.IsFriendReq) (*friend_rpc.IsFriendRes, error) {
	l := logic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}

func (s *FriendServer) IsBlocked(ctx context.Context, in *friend_rpc.IsBlockedReq) (*friend_rpc.IsBlockedRes, error) {
	l := logic.NewIsBlockedLogic(ctx, s.svcCtx)
	return l.IsBlocked(in)
}

// 管理类通用能力（admin / 其他服务均可复用，不与 HTTP 接口 1:1）
func (s *FriendServer) ListFriends(ctx context.Context, in *friend_rpc.ListFriendsReq) (*friend_rpc.ListFriendsRes, error) {
	l := logic.NewListFriendsLogic(ctx, s.svcCtx)
	return l.ListFriends(in)
}

func (s *FriendServer) UpdateFriends(ctx context.Context, in *friend_rpc.UpdateFriendsReq) (*friend_rpc.UpdateFriendsRes, error) {
	l := logic.NewUpdateFriendsLogic(ctx, s.svcCtx)
	return l.UpdateFriends(in)
}

func (s *FriendServer) ListFriendVerifies(ctx context.Context, in *friend_rpc.ListFriendVerifiesReq) (*friend_rpc.ListFriendVerifiesRes, error) {
	l := logic.NewListFriendVerifiesLogic(ctx, s.svcCtx)
	return l.ListFriendVerifies(in)
}

func (s *FriendServer) UpdateFriendVerifies(ctx context.Context, in *friend_rpc.UpdateFriendVerifiesReq) (*friend_rpc.UpdateFriendVerifiesRes, error) {
	l := logic.NewUpdateFriendVerifiesLogic(ctx, s.svcCtx)
	return l.UpdateFriendVerifies(in)
}

func (s *FriendServer) ListFriendBlocks(ctx context.Context, in *friend_rpc.ListFriendBlocksReq) (*friend_rpc.ListFriendBlocksRes, error) {
	l := logic.NewListFriendBlocksLogic(ctx, s.svcCtx)
	return l.ListFriendBlocks(in)
}

func (s *FriendServer) UpdateFriendBlocks(ctx context.Context, in *friend_rpc.UpdateFriendBlocksReq) (*friend_rpc.UpdateFriendBlocksRes, error) {
	l := logic.NewUpdateFriendBlocksLogic(ctx, s.svcCtx)
	return l.UpdateFriendBlocks(in)
}
