// Code generated by goctl. DO NOT EDIT.
// Source: friend_rpc.proto

package server

import (
	"context"

	"beaver/app/friend/friend_rpc/internal/logic"
	"beaver/app/friend/friend_rpc/internal/svc"
	"beaver/app/friend/friend_rpc/types/friend_rpc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend_rpc.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) GetFriendIds(ctx context.Context, in *friend_rpc.GetFriendIdsRequest) (*friend_rpc.GetFriendIdsResponse, error) {
	l := logic.NewGetFriendIdsLogic(ctx, s.svcCtx)
	return l.GetFriendIds(in)
}
