// Code generated by goctl. DO NOT EDIT.
package types

type AddEmojiReq struct {
	UserID    string `header:"Beaver-User-Id"`
	FileName  string `json:"fileName"`
	Title     string `json:"title"`
	PackageID string `json:"packageId,optional"`
}

type AddEmojiRes struct {
}

type EmojiCollectDetailItem struct {
	UUID      string `json:"uuid"`
	UserID    string `json:"userId"`
	EmojiID   string `json:"emojiId"`
	IsDeleted bool   `json:"isDeleted"`
	Version   int64  `json:"version"`
	CreateAt  int64  `json:"createAt"`
	UpdateAt  int64  `json:"updateAt"`
}

type EmojiDetailItem struct {
	EmojiID   string  `json:"emojiId"`
	UUID      string  `json:"uuid"`
	FileKey   string  `json:"fileKey"`
	Title     string  `json:"title"`
	Status    int8    `json:"status"`
	Version   int64   `json:"version"`
	PackageID *string `json:"packageId"`
	CreateAt  int64   `json:"createAt"`
	UpdateAt  int64   `json:"updateAt"`
}

type EmojiItem struct {
	EmojiID   string  `json:"emojiId"`
	FileName  string  `json:"fileName"`
	Title     string  `json:"title"`
	PackageID *string `json:"packageId"`
}

type EmojiPackageCollectDetailItem struct {
	UUID      string `json:"uuid"`
	UserID    string `json:"userId"`
	PackageID string `json:"packageId"`
	IsDeleted bool   `json:"isDeleted"`
	Version   int64  `json:"version"`
	CreateAt  int64  `json:"createAt"`
	UpdateAt  int64  `json:"updateAt"`
}

type EmojiPackageContentDetailItem struct {
	PackageID string `json:"packageId"`
	EmojiID   string `json:"emojiId"`
	SortOrder int    `json:"sortOrder"`
	Version   int64  `json:"version"`
	CreateAt  int64  `json:"createAt"`
	UpdateAt  int64  `json:"updateAt"`
}

type EmojiPackageDetailItem struct {
	PackageID    string `json:"packageId"`
	UUID         string `json:"uuid"`
	Title        string `json:"title"`
	CoverFile    string `json:"coverFile"`
	UserID       string `json:"userId"`
	Description  string `json:"description"`
	Type         string `json:"type"`
	Status       int8   `json:"status"`
	CollectCount int    `json:"collectCount"`
	CreateAt     int64  `json:"createAt"`
	UpdateAt     int64  `json:"updateAt"`
	Version      int64  `json:"version"`
}

type EmojiPackageItem struct {
	PackageID    string `json:"packageId"`
	Title        string `json:"title"`
	CoverFile    string `json:"coverFile"`
	Description  string `json:"description"`
	Type         string `json:"type"` // 类型：official-官方，user-用户自定义
	CollectCount int    `json:"collectCount"`
	EmojiCount   int    `json:"emojiCount"`
	IsCollected  bool   `json:"isCollected"` // 当前用户是否已收藏
	IsAuthor     bool   `json:"isAuthor"`    // 当前用户是否是作者
}

type GetEmojiCollectsByIdsReq struct {
	UserID string   `header:"Beaver-User-Id"`
	Ids    []string `json:"ids"` // 收藏记录UUID列表
}

type GetEmojiCollectsByIdsRes struct {
	Collects []EmojiCollectDetailItem `json:"collects"`
}

type GetEmojiPackageCollectsByIdsReq struct {
	UserID string   `header:"Beaver-User-Id"`
	Ids    []string `json:"ids"` // 收藏记录UUID列表
}

type GetEmojiPackageCollectsByIdsRes struct {
	Collects []EmojiPackageCollectDetailItem `json:"collects"`
}

type GetEmojiPackageContentsByPackageIdsReq struct {
	UserID     string   `header:"Beaver-User-Id"`
	PackageIds []string `json:"packageIds"` // 表情包ID列表
}

type GetEmojiPackageContentsByPackageIdsRes struct {
	Contents []EmojiPackageContentDetailItem `json:"contents"`
}

type GetEmojiPackageDetailReq struct {
	UserID    string `header:"Beaver-User-Id"`
	PackageID string `json:"packageId"`
}

type GetEmojiPackageDetailRes struct {
	PackageID    string      `json:"packageId"`
	Title        string      `json:"title"`
	CoverFile    string      `json:"coverFile"`
	Description  string      `json:"description"`
	Type         string      `json:"type"` // 类型：official-官方，user-用户自定义
	CollectCount int         `json:"collectCount"`
	EmojiCount   int         `json:"emojiCount"`
	IsCollected  bool        `json:"isCollected"`
	IsAuthor     bool        `json:"isAuthor"` // 当前用户是否是作者
	Emojis       []EmojiItem `json:"emojis"`
}

type GetEmojiPackagesByIdsReq struct {
	UserID string   `header:"Beaver-User-Id"`
	Ids    []string `json:"ids"` // 表情包UUID列表
}

type GetEmojiPackagesByIdsRes struct {
	Packages []EmojiPackageDetailItem `json:"packages"`
}

type GetEmojiPackagesReq struct {
	UserID     string `header:"Beaver-User-Id"`
	CategoryID uint   `json:"categoryId,optional"` // 可选，按分类筛选
	Type       string `json:"type,optional"`       // 可选，按类型筛选：official-官方，user-用户自定义
	Page       int    `json:"page"`
	Size       int    `json:"size"`
}

type GetEmojiPackagesRes struct {
	Count int64              `json:"count"`
	List  []EmojiPackageItem `json:"list"`
}

type GetEmojisByIdsReq struct {
	UserID string   `header:"Beaver-User-Id"`
	Ids    []string `json:"ids"` // 表情UUID列表
}

type GetEmojisByIdsRes struct {
	Emojis []EmojiDetailItem `json:"emojis"`
}

type GetEmojisListReq struct {
	UserID string `header:"Beaver-User-Id"`
	Page   int    `json:"page"`
	Size   int    `json:"size"`
}

type GetEmojisListRes struct {
	Count int64       `json:"count"`
	List  []EmojiItem `json:"list"`
}

type GetUserFavoritePackagesReq struct {
	UserID string `header:"Beaver-User-Id"`
	Page   int    `json:"page"`
	Size   int    `json:"size"`
}

type GetUserFavoritePackagesRes struct {
	Count int64              `json:"count"`
	List  []EmojiPackageItem `json:"list"`
}

type UpdateFavoriteEmojiPackageReq struct {
	UserID    string `header:"Beaver-User-Id"`
	PackageID string `json:"packageId"`
	Type      string `json:"type"` // "favorite" or "unfavorite"
}

type UpdateFavoriteEmojiPackageRes struct {
}

type UpdateFavoriteEmojiReq struct {
	UserID  string `header:"Beaver-User-Id"`
	EmojiID string `json:"emojiId"`
	Type    string `json:"type"` // "favorite" or "unfavorite"
}

type UpdateFavoriteEmojiRes struct {
}
