// Code generated by goctl. DO NOT EDIT.
package types

type AudioFile struct {
	Duration int `json:"duration"`
}

type FileInfo struct {
	Type      string     `json:"type"`
	ImageFile *ImageFile `json:"imageFile,optional"`
	VideoFile *VideoFile `json:"videoFile,optional"`
	AudioFile *AudioFile `json:"audioFile,optional"`
}

type FileReq struct {
	UserID string `header:"Beaver-User-Id"`
}

type FileRes struct {
	FileKey      string    `json:"fileKey"`
	OriginalName string    `json:"originalName"`
	FileInfo     *FileInfo `json:"fileInfo,optional"`
}

type ImageFile struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}

type PreviewReq struct {
	FileKey string `path:"fileKey"`
}

type PreviewRes struct {
}

type VideoFile struct {
	Width    int `json:"width"`
	Height   int `json:"height"`
	Duration int `json:"duration"`
}
