Name: backend
Host: 0.0.0.0
Port: 40000
Timeout: 600000 # 10分钟超时，单位毫秒，文件上传需要更长的处理时间
Auth:
  AccessSecret: robert
  AccessExpire: 3600
Etcd: 127.0.0.1:2379
Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/beaver_backend?charset=utf8mb4&parseTime=True&loc=Local
Etcd: 127.0.0.1:2379
Redis:
  Addr: 127.0.0.1:6379
  Password: '123456'
  DB: 0
WhiteList:
  - /admin/auth_public/v1/login
  - /admin/auth_public/v1/authentication
BlackList: []
File:
  WhiteList:
    - png
    - jpg
    - jpeg
    - gif
    - webp
    - mp4
    - mp3
    - pdf
    - exe
    - apk
  BlackList:
    - sh
    - bat
  MaxSize:
    image: 2
    video: 10
    audio: 2
    archive: 2
    document: 2
    unknown: 10
    exe: 1024
    apk: 512
MaxBytes: 1073741824 # 1GB - go-zero HTTP服务器最大请求体大小
Domain: "http://192.168.3.4:20800" # 对外访问域名，用于生成本地文件完整 URL
# 本地存储配置
Local:
  UploadDir: /mnt/static # 本地文件上传目录(相对路径，相对于程序运行目录)
  ProjectName: beaver # 项目名称，用于文件路径前缀（为空则使用根目录）
# 七牛云配置
Qiniu:
  ProjectName: beaver # 项目名称，用于文件路径前缀（为空则使用根目录）
  AK: your_qiniu_access_key
  SK: your_qiniu_secret_key
  Bucket: your_qiniu_bucket_name
  Domain: 'your_qiniu_domain'
  ExpireTime: 3600 # 签名URL有效期, 单位：秒
UserRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: userrpc.rpc
AuthRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: authrpc.rpc
FileRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: filerpc.rpc
PlatformRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: platformrpc.rpc
OpenRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: openrpc.rpc
FriendRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: friendrpc.rpc
GroupRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: grouprpc.rpc
ChatRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: chatrpc.rpc
MomentRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: momentrpc.rpc
EmojiRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: emojirpc.rpc

