
services:
  backend_admin:
    image: wsrh8888/backend_admin:1.0.2
    container_name: backend_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend.yaml:/etc/backend.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always

