services:
  call_rpc:
    image: wsrh8888/call_rpc:1.0.0
    container_name: call_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./callrpc.yaml:/etc/callrpc.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always
