// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: call_rpc.proto

package server

import (
	"context"

	"beaver/app/call/call_rpc/internal/logic"
	"beaver/app/call/call_rpc/internal/svc"
	"beaver/app/call/call_rpc/types/call_rpc"
)

type CallServer struct {
	svcCtx *svc.ServiceContext
	call_rpc.UnimplementedCallServer
}

func NewCallServer(svcCtx *svc.ServiceContext) *CallServer {
	return &CallServer{
		svcCtx: svcCtx,
	}
}

// 供 Chat/User 等服务查询用户是否忙碌
func (s *CallServer) GetUserStatus(ctx context.Context, in *call_rpc.GetUserStatusReq) (*call_rpc.GetUserStatusRes, error) {
	l := logic.NewGetUserStatusLogic(ctx, s.svcCtx)
	return l.GetUserStatus(in)
}

// 供 Call-Api 调用，创建通话记录
func (s *CallServer) CreateSession(ctx context.Context, in *call_rpc.CreateSessionReq) (*call_rpc.CreateSessionRes, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

// 更新参与者状态
func (s *CallServer) UpdateParticipantStatus(ctx context.Context, in *call_rpc.UpdateParticipantStatusReq) (*call_rpc.UpdateParticipantStatusRes, error) {
	l := logic.NewUpdateParticipantStatusLogic(ctx, s.svcCtx)
	return l.UpdateParticipantStatus(in)
}

// 结束通话记录
func (s *CallServer) FinalizeSession(ctx context.Context, in *call_rpc.FinalizeSessionReq) (*call_rpc.FinalizeSessionRes, error) {
	l := logic.NewFinalizeSessionLogic(ctx, s.svcCtx)
	return l.FinalizeSession(in)
}

// 获取通话信息
func (s *CallServer) GetSession(ctx context.Context, in *call_rpc.GetSessionReq) (*call_rpc.GetSessionRes, error) {
	l := logic.NewGetSessionLogic(ctx, s.svcCtx)
	return l.GetSession(in)
}

// 获取参与者列表及状态
func (s *CallServer) GetParticipants(ctx context.Context, in *call_rpc.GetParticipantsReq) (*call_rpc.GetParticipantsRes, error) {
	l := logic.NewGetParticipantsLogic(ctx, s.svcCtx)
	return l.GetParticipants(in)
}
