

services:
  auth_api:
    image: wsrh8888/auth_api:1.0.2
    container_name: auth_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./auth.yaml:/etc/auth.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
