
services:
  emoji_api:
    image: wsrh8888/emoji_api:1.0.0
    container_name: emoji_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./emoji.yaml:/etc/emoji.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
