// Code generated by goctl. DO NOT EDIT.
package types

type AppInfo struct {
	AppID         string `json:"appId"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Icon          string `json:"icon,optional"` // 应用图标 URL
	AppSecret     string `json:"appSecret"`     // 应用密钥（掩码形式）
	Status        int    `json:"status"`        // 0=草稿，1=已发布，2=禁用
	EnableRobot   int    `json:"enableRobot"`   // 是否启用智能机器人能力
	EnableOAuth   int    `json:"enableOAuth"`   // 是否启用OAuth能力
	EnableWebhook int    `json:"enableWebhook"` // 是否启用Webhook能力
	WebhookURL    string `json:"webhookUrl"`
	CreatedAt     int64  `json:"createdAt"`
}

type ApplyDeveloperReq struct {
	RealName    string `json:"realName"`             // 真实姓名
	CompanyName string `json:"companyName,optional"` // 公司名称
	Phone       string `json:"phone"`                // 联系电话
	Email       string `json:"email"`                // 联系邮箱
	Description string `json:"description"`          // 应用场景描述
}

type ApplyDeveloperRes struct {
	Success bool   `json:"success"`
	Message string `json:"message"` // 提示信息
}

type AuditDeveloperReq struct {
	ID          uint   `json:"id"`
	Status      int    `json:"status"` // 1通过 2拒绝
	AuditRemark string `json:"auditRemark,optional"`
}

type AuditDeveloperRes struct {
	Success bool `json:"success"`
}

type BotConfigInfo struct {
	AppID            string   `json:"appId"`
	BotName          string   `json:"botName"`
	BotAvatar        string   `json:"botAvatar"`
	BotDescription   string   `json:"botDescription"`
	UsageGuide       string   `json:"usageGuide"` // 使用说明
	EnableSingleChat bool     `json:"enableSingleChat"`
	EnableGroupChat  bool     `json:"enableGroupChat"`
	EnableAtMention  bool     `json:"enableAtMention"`
	EnableMenu       bool     `json:"enableMenu"` // 是否启用自定义菜单
	MenuItems        string   `json:"menuItems"`  // JSON 字符串，菜单项配置
	AutoReplyRules   []string `json:"autoReplyRules"`
	Commands         []string `json:"commands"`
	Status           int      `json:"status"`
}

type CreateAppReq struct {
	Name        string `json:"name" validate:"required,min=2,max=50"`
	Description string `json:"description,optional" validate:"max=200"`
	Icon        string `json:"icon,optional"`    // 应用图标 URL
	UserID      string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type CreateAppRes struct {
	AppID     string `json:"appId"`
	AppSecret string `json:"appSecret"`
}

type CreateEventSubscriptionReq struct {
	AppID      string `json:"appId"`
	EventType  string `json:"eventType"`           // 事件类型
	TargetURL  string `json:"targetUrl"`           // 推送目标URL
	Secret     string `json:"secret,optional"`     // 签名密钥
	RetryCount int    `json:"retryCount,optional"` // 重试次数
	Timeout    int    `json:"timeout,optional"`    // 超时时间(秒)
	UserID     string `header:"Beaver-User-Id"`
}

type CreateEventSubscriptionRes struct {
	Subscription EventSubscriptionInfo `json:"subscription"`
}

type CreateIncomingWebhookReq struct {
	AppID   string `json:"appId"`
	GroupID string `json:"groupId"`
	Name    string `json:"name,optional"`
	UserID  string `header:"Beaver-User-Id"`
}

type CreateIncomingWebhookRes struct {
	Webhook IncomingWebhookInfo `json:"webhook"`
}

type CreateVersionReq struct {
	AppID       string `json:"appId"`
	Version     string `json:"version" validate:"required,max=20"`                    // 版本号，如 1.0.0
	Description string `json:"description,optional" validate:"max=500"`               // 版本说明
	Visibility  string `json:"visibility" validate:"required,oneof=self partial all"` // 可见范围：self/partial/all
	UserID      string `header:"Beaver-User-Id"`
}

type CreateVersionRes struct {
	VersionID string `json:"versionId"`
}

type DeleteAppReq struct {
	AppID  string `json:"appId"`
	UserID string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type DeleteAppRes struct {
}

type DeleteEventSubscriptionReq struct {
	ID     string `json:"id"`
	UserID string `header:"Beaver-User-Id"`
}

type DeleteEventSubscriptionRes struct {
}

type DeleteIncomingWebhookReq struct {
	ID     string `json:"id"`
	UserID string `header:"Beaver-User-Id"`
}

type DeleteIncomingWebhookRes struct {
}

type DesktopOAuthConfigInfo struct {
	Enabled      bool   `json:"enabled"`
	CustomScheme string `json:"customScheme"`
	AuthPageURL  string `json:"authPageUrl"` // 授权页面完整 URL（服务端生成）
}

type DeveloperInfo struct {
	ID          uint   `json:"id"`
	UserID      string `json:"userId"`
	RealName    string `json:"realName"`
	CompanyName string `json:"companyName"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	AuditBy     string `json:"auditBy"`
	AuditTime   int64  `json:"auditTime"`
	AuditRemark string `json:"auditRemark"`
	CreatedAt   int64  `json:"createdAt"`
}

type EventSubscriptionInfo struct {
	ID         string `json:"id"`
	AppID      string `json:"appId"`
	EventType  string `json:"eventType"`
	TargetURL  string `json:"targetUrl"`
	Secret     string `json:"secret"`
	Status     int    `json:"status"` // 0禁用 1启用
	RetryCount int    `json:"retryCount"`
	Timeout    int    `json:"timeout"`
	CreatedAt  int64  `json:"createdAt"`
	UpdatedAt  int64  `json:"updatedAt"`
}

type GetAppDetailReq struct {
	AppID  string `form:"appId"`            // 应用ID
	UserID string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type GetAppDetailRes struct {
	App AppInfo `json:"app"`
}

type GetAppListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Status   int    `form:"status,optional"`
	UserID   string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type GetAppListRes struct {
	Total int64     `json:"total"`
	List  []AppInfo `json:"list"`
}

type GetAppScopesReq struct {
	AppID  string `form:"appId"`
	UserID string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type GetAppScopesRes struct {
	Scopes []ScopeInfo `json:"scopes"`
}

type GetBotConfigReq struct {
	AppID  string `form:"appId"`
	UserID string `header:"Beaver-User-Id"`
}

type GetBotConfigRes struct {
	Config BotConfigInfo `json:"config"`
}

type GetDeveloperDetailReq struct {
	ID uint `form:"id"`
}

type GetDeveloperDetailRes struct {
	Developer DeveloperInfo `json:"developer"`
}

type GetDeveloperListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=10"`
	Status   int `form:"status,optional"` // 0待审核 1已通过 2已拒绝
}

type GetDeveloperListRes struct {
	Total int64           `json:"total"`
	List  []DeveloperInfo `json:"list"`
}

type GetOAuthConfigReq struct {
	AppID  string `form:"appId"`
	UserID string `header:"Beaver-User-Id"`
}

type GetOAuthConfigRes struct {
	H5Config      *H5OAuthConfigInfo      `json:"h5Config,optional"`
	DesktopConfig *DesktopOAuthConfigInfo `json:"desktopConfig,optional"`
	MobileConfig  *MobileOAuthConfigInfo  `json:"mobileConfig,optional"`
}

type GetSecurityConfigReq struct {
	AppID  string `form:"appId"`
	UserID string `header:"Beaver-User-Id"`
}

type GetSecurityConfigRes struct {
	Config SecurityConfigInfo `json:"config"`
}

type GetVersionListReq struct {
	AppID    string `form:"appId"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	UserID   string `header:"Beaver-User-Id"`
}

type GetVersionListRes struct {
	Total int64         `json:"total"`
	List  []VersionInfo `json:"list"`
}

type H5OAuthConfigInfo struct {
	Enabled      bool     `json:"enabled"`
	RedirectURIs []string `json:"redirectUris"`
	JsSdkDomains []string `json:"jsSdkDomains"` // JS-SDK 安全域名
	EnablePKCE   bool     `json:"enablePKCE"`
}

type IncomingWebhookInfo struct {
	ID         string `json:"id"`
	Token      string `json:"token"`           // access_token
	Secret     string `json:"secret,optional"` // 加签密钥，仅创建时返回
	AppID      string `json:"appId"`
	GroupID    string `json:"groupId"`
	BotUserID  string `json:"botUserId"`
	Name       string `json:"name"`
	WebhookURL string `json:"webhookUrl"` // 基址含 access_token，调用时另拼 timestamp、sign
	Status     int    `json:"status"`
	CreatedAt  int64  `json:"createdAt"`
}

type ListEventSubscriptionsReq struct {
	AppID     string `form:"appId"`
	EventType string `form:"eventType,optional"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=20"`
	UserID    string `header:"Beaver-User-Id"`
}

type ListEventSubscriptionsRes struct {
	Total int64                   `json:"total"`
	List  []EventSubscriptionInfo `json:"list"`
}

type ListIncomingWebhooksReq struct {
	AppID    string `form:"appId"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	UserID   string `header:"Beaver-User-Id"`
}

type ListIncomingWebhooksRes struct {
	Total int64                 `json:"total"`
	List  []IncomingWebhookInfo `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"` // 手机号或邮箱
	Password string `json:"password"`
}

type LoginRes struct {
	Token    string `json:"token"`
	UserID   string `json:"userId"`
	NickName string `json:"nickName"` // 用户昵称
	ExpireAt int64  `json:"expireAt"`
}

type MobileOAuthConfigInfo struct {
	Enabled            bool   `json:"enabled"`
	IOSBundleID        string `json:"iosBundleId"`
	AndroidPackageName string `json:"androidPackageName"`
	UniversalLink      string `json:"universalLink"`
	CustomScheme       string `json:"customScheme"`
	EnablePKCE         bool   `json:"enablePKCE"`
}

type PublishAppReq struct {
	AppID       string `json:"appId"`
	Version     string `json:"version,optional" validate:"max=20"`      // 版本号，如 1.0.0
	Description string `json:"description,optional" validate:"max=500"` // 版本说明
	UserID      string `header:"Beaver-User-Id"`                        // 当前用户ID（由网关注入）
}

type PublishAppRes struct {
	Status int `json:"status"` // 发布后状态：1已发布
}

type PublishVersionReq struct {
	VersionID string `json:"versionId"`
	UserID    string `header:"Beaver-User-Id"`
}

type PublishVersionRes struct {
}

type ResetAppSecretReq struct {
	AppID  string `json:"appId"`
	UserID string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type ResetAppSecretRes struct {
	AppSecret string `json:"appSecret"`
}

type ScopeInfo struct {
	Scope       string `json:"scope"`       // 权限标识
	Name        string `json:"name"`        // 权限名称
	Description string `json:"description"` // 权限描述
	Enabled     bool   `json:"enabled"`     // 是否已启用
	Required    bool   `json:"required"`    // 是否需要审核
}

type SecurityConfigInfo struct {
	AppID          string   `json:"appId"`
	IPWhitelist    []string `json:"ipWhitelist"`    // IP白名单
	TrustedDomains []string `json:"trustedDomains"` // H5可信域名
}

type SubmitVersionReviewReq struct {
	VersionID string `json:"versionId"`
	UserID    string `header:"Beaver-User-Id"`
}

type SubmitVersionReviewRes struct {
}

type ToggleAppCapabilityReq struct {
	AppID      string `json:"appId"`
	Capability string `json:"capability" validate:"required,oneof=robot oauth webhook"` // 能力类型：robot/oauth/webhook
	Enable     bool   `json:"enable"`                                                   // true=启用，false=禁用
	UserID     string `header:"Beaver-User-Id"`                                         // 当前用户ID（由网关注入）
}

type ToggleAppCapabilityRes struct {
	Enabled bool `json:"enabled"` // 当前状态
}

type UpdateAppReq struct {
	AppID       string `json:"appId"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Icon        string `json:"icon,optional"` // 应用图标 URL
	WebhookURL  string `json:"webhookUrl,optional"`
	UserID      string `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type UpdateAppRes struct {
}

type UpdateAppScopesReq struct {
	AppID  string   `json:"appId"`
	Scopes []string `json:"scopes"`           // 权限标识列表
	UserID string   `header:"Beaver-User-Id"` // 当前用户ID（由网关注入）
}

type UpdateAppScopesRes struct {
}

type UpdateBotConfigReq struct {
	AppID            string   `json:"appId"`
	BotName          string   `json:"botName,optional"`
	BotAvatar        string   `json:"botAvatar,optional"`
	BotDescription   string   `json:"botDescription,optional"`
	UsageGuide       string   `json:"usageGuide,optional"` // 使用说明
	EnableSingleChat *bool    `json:"enableSingleChat,optional"`
	EnableGroupChat  *bool    `json:"enableGroupChat,optional"`
	EnableAtMention  *bool    `json:"enableAtMention,optional"`
	EnableMenu       *bool    `json:"enableMenu,optional"` // 是否启用自定义菜单
	MenuItems        string   `json:"menuItems,optional"`  // JSON 字符串，菜单项配置
	AutoReplyRules   []string `json:"autoReplyRules,optional"`
	Commands         []string `json:"commands,optional"`
	Status           *int     `json:"status,optional"`
	UserID           string   `header:"Beaver-User-Id"`
}

type UpdateBotConfigRes struct {
}

type UpdateEventSubscriptionReq struct {
	ID         string `json:"id"`
	TargetURL  string `json:"targetUrl,optional"`
	Secret     string `json:"secret,optional"`
	Status     *int   `json:"status,optional"` // 0禁用 1启用
	RetryCount *int   `json:"retryCount,optional"`
	Timeout    *int   `json:"timeout,optional"`
	UserID     string `header:"Beaver-User-Id"`
}

type UpdateEventSubscriptionRes struct {
}

type UpdateOAuthConfigReq struct {
	AppID     string `json:"appId"`
	OAuthType string `json:"oauthType"` // h5 | desktop | mobile
	Config    string `json:"config"`    // JSON 字符串，根据不同类型包含不同字段
	UserID    string `header:"Beaver-User-Id"`
}

type UpdateOAuthConfigRes struct {
}

type UpdateSecurityConfigReq struct {
	AppID          string   `json:"appId"`
	IPWhitelist    []string `json:"ipWhitelist,optional"`    // IP白名单
	TrustedDomains []string `json:"trustedDomains,optional"` // H5可信域名
	UserID         string   `header:"Beaver-User-Id"`
}

type UpdateSecurityConfigRes struct {
}

type VersionInfo struct {
	ID           string   `json:"id"`
	Version      string   `json:"version"`
	Description  string   `json:"description"`
	Visibility   string   `json:"visibility"`   // self/partial/all
	Status       string   `json:"status"`       // draft/reviewing/approved/rejected/published
	Capabilities []string `json:"capabilities"` // 该版本包含的能力
	CreatedAt    int64    `json:"createdAt"`
}
