Name: gateway
Addr: 0.0.0.0:20800
etcd: 127.0.0.1:2379
Log:
  Encoding: plain
  TimeFormat: 2006-01-02T15:04:05
  Stat: false
Auth:
  AccessSecret: robert
  AccessExpire: 3600
PublicList:
  - /api/auth/auth_public/.*
  - /api/platform/track_public/.*
  - /api/platform/update_public/.*
  - /api/open/.*_public/.*
  - /api/settings/open_login_info
  - /api/file/preview/.*
CustomAuthList:
  - /api/open_portal/.*
