
services:
  emoji_rpc:
    image: wsrh8888/emoji_rpc:1.0.0
    container_name: emoji_rpc
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./emojirpc.yaml:/etc/emojirpc.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always

