// Code generated by goctl. DO NOT EDIT.
package types

type CityInfo struct {
	Code string `json:"code"` // 城市代码
	Name string `json:"name"` // 城市名称
}

type GetCitiesRes struct {
	Cities []CityInfo `json:"cities"` // 城市列表
}
