// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user_rpc.proto

package user_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`                       // 手机号（与email二选一）
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                 // 密码
	Source        int32                  `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`                    // 注册来源：1-手机号注册，2-邮箱注册
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                       // 邮箱（与phone二选一）
	NickName      string                 `protobuf:"bytes,5,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` // 昵称（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateReq) Reset() {
	*x = UserCreateReq{}
	mi := &file_user_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateReq) ProtoMessage() {}

func (x *UserCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateReq.ProtoReflect.Descriptor instead.
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateReq) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *UserCreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type UserCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRes) Reset() {
	*x = UserCreateRes{}
	mi := &file_user_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRes) ProtoMessage() {}

func (x *UserCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRes.ProtoReflect.Descriptor instead.
func (*UserCreateRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateRes) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_user_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRes) Reset() {
	*x = UserInfoRes{}
	mi := &file_user_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRes) ProtoMessage() {}

func (x *UserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRes.ProtoReflect.Descriptor instead.
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoRes) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type IsFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendReq) Reset() {
	*x = IsFriendReq{}
	mi := &file_user_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendReq) ProtoMessage() {}

func (x *IsFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendReq.ProtoReflect.Descriptor instead.
func (*IsFriendReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *IsFriendReq) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *IsFriendReq) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type IsFriendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendRes) Reset() {
	*x = IsFriendRes{}
	mi := &file_user_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRes) ProtoMessage() {}

func (x *IsFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRes.ProtoReflect.Descriptor instead.
func (*IsFriendRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *IsFriendRes) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // 用户版本号，用于同步
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Abstract      string                 `protobuf:"bytes,6,opt,name=abstract,proto3" json:"abstract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

type UserVersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVersionInfo) Reset() {
	*x = UserVersionInfo{}
	mi := &file_user_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVersionInfo) ProtoMessage() {}

func (x *UserVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVersionInfo.ProtoReflect.Descriptor instead.
func (*UserVersionInfo) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *UserVersionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserVersionInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UserVersionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVersionsReq) Reset() {
	*x = UserVersionsReq{}
	mi := &file_user_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVersionsReq) ProtoMessage() {}

func (x *UserVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVersionsReq.ProtoReflect.Descriptor instead.
func (*UserVersionsReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *UserVersionsReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserVersionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserVersions  map[string]int64       `protobuf:"bytes,1,rep,name=user_versions,json=userVersions,proto3" json:"user_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // user_id -> version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVersionsRes) Reset() {
	*x = UserVersionsRes{}
	mi := &file_user_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVersionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVersionsRes) ProtoMessage() {}

func (x *UserVersionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVersionsRes.ProtoReflect.Descriptor instead.
func (*UserVersionsRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *UserVersionsRes) GetUserVersions() map[string]int64 {
	if x != nil {
		return x.UserVersions
	}
	return nil
}

type UserListInfoReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserIdList     []string               `protobuf:"bytes,1,rep,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // 可选：从这个时间戳之后查询更新的用户，不传则返回所有
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserListInfoReq) Reset() {
	*x = UserListInfoReq{}
	mi := &file_user_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInfoReq) ProtoMessage() {}

func (x *UserListInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInfoReq.ProtoReflect.Descriptor instead.
func (*UserListInfoReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *UserListInfoReq) GetUserIdList() []string {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

func (x *UserListInfoReq) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

type UserListInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      map[string]*UserInfo   `protobuf:"bytes,1,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //用户配置的json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListInfoRes) Reset() {
	*x = UserListInfoRes{}
	mi := &file_user_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInfoRes) ProtoMessage() {}

func (x *UserListInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInfoRes.ProtoReflect.Descriptor instead.
func (*UserListInfoRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *UserListInfoRes) GetUserInfo() map[string]*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type SearchUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` // 搜索关键词（邮箱或用户ID）
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // 搜索类型：email 或 userId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	mi := &file_user_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *SearchUserReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SearchUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserRes) Reset() {
	*x = SearchUserRes{}
	mi := &file_user_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserRes) ProtoMessage() {}

func (x *SearchUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserRes.ProtoReflect.Descriptor instead.
func (*SearchUserRes) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *SearchUserRes) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_user_rpc_proto protoreflect.FileDescriptor

const file_user_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0euser_rpc.proto\x12\buser_rpc\"\x8c\x01\n" +
	"\rUserCreateReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x05R\x06source\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\tnick_name\x18\x05 \x01(\tR\bnickName\"'\n" +
	"\rUserCreateRes\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"%\n" +
	"\vUserInfoReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\">\n" +
	"\vUserInfoRes\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.user_rpc.UserInfoR\buserInfo\"9\n" +
	"\vIsFriendReq\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"*\n" +
	"\vIsFriendRes\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\"\xa4\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\babstract\x18\x06 \x01(\tR\babstract\"D\n" +
	"\x0fUserVersionInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\",\n" +
	"\x0fUserVersionsReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xa4\x01\n" +
	"\x0fUserVersionsRes\x12P\n" +
	"\ruser_versions\x18\x01 \x03(\v2+.user_rpc.UserVersionsRes.UserVersionsEntryR\fuserVersions\x1a?\n" +
	"\x11UserVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\\\n" +
	"\x0fUserListInfoReq\x12 \n" +
	"\fuser_id_list\x18\x01 \x03(\tR\n" +
	"userIdList\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\"\xa8\x01\n" +
	"\x0fUserListInfoRes\x12D\n" +
	"\tuser_info\x18\x01 \x03(\v2'.user_rpc.UserListInfoRes.UserInfoEntryR\buserInfo\x1aO\n" +
	"\rUserInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.user_rpc.UserInfoR\x05value:\x028\x01\"=\n" +
	"\rSearchUserReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"@\n" +
	"\rSearchUserRes\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.user_rpc.UserInfoR\buserInfo2\x86\x03\n" +
	"\x04user\x12>\n" +
	"\n" +
	"UserCreate\x12\x17.user_rpc.UserCreateReq\x1a\x17.user_rpc.UserCreateRes\x128\n" +
	"\bUserInfo\x12\x15.user_rpc.UserInfoReq\x1a\x15.user_rpc.UserInfoRes\x128\n" +
	"\bIsFriend\x12\x15.user_rpc.IsFriendReq\x1a\x15.user_rpc.IsFriendRes\x12>\n" +
	"\n" +
	"SearchUser\x12\x17.user_rpc.SearchUserReq\x1a\x17.user_rpc.SearchUserRes\x12D\n" +
	"\fUserListInfo\x12\x19.user_rpc.UserListInfoReq\x1a\x19.user_rpc.UserListInfoRes\x12D\n" +
	"\fUserVersions\x12\x19.user_rpc.UserVersionsReq\x1a\x19.user_rpc.UserVersionsResB\fZ\n" +
	"./user_rpcb\x06proto3"

var (
	file_user_rpc_proto_rawDescOnce sync.Once
	file_user_rpc_proto_rawDescData []byte
)

func file_user_rpc_proto_rawDescGZIP() []byte {
	file_user_rpc_proto_rawDescOnce.Do(func() {
		file_user_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)))
	})
	return file_user_rpc_proto_rawDescData
}

var file_user_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_rpc_proto_goTypes = []any{
	(*UserCreateReq)(nil),   // 0: user_rpc.UserCreateReq
	(*UserCreateRes)(nil),   // 1: user_rpc.UserCreateRes
	(*UserInfoReq)(nil),     // 2: user_rpc.UserInfoReq
	(*UserInfoRes)(nil),     // 3: user_rpc.UserInfoRes
	(*IsFriendReq)(nil),     // 4: user_rpc.IsFriendReq
	(*IsFriendRes)(nil),     // 5: user_rpc.IsFriendRes
	(*UserInfo)(nil),        // 6: user_rpc.UserInfo
	(*UserVersionInfo)(nil), // 7: user_rpc.UserVersionInfo
	(*UserVersionsReq)(nil), // 8: user_rpc.UserVersionsReq
	(*UserVersionsRes)(nil), // 9: user_rpc.UserVersionsRes
	(*UserListInfoReq)(nil), // 10: user_rpc.UserListInfoReq
	(*UserListInfoRes)(nil), // 11: user_rpc.UserListInfoRes
	(*SearchUserReq)(nil),   // 12: user_rpc.SearchUserReq
	(*SearchUserRes)(nil),   // 13: user_rpc.SearchUserRes
	nil,                     // 14: user_rpc.UserVersionsRes.UserVersionsEntry
	nil,                     // 15: user_rpc.UserListInfoRes.UserInfoEntry
}
var file_user_rpc_proto_depIdxs = []int32{
	6,  // 0: user_rpc.UserInfoRes.user_info:type_name -> user_rpc.UserInfo
	14, // 1: user_rpc.UserVersionsRes.user_versions:type_name -> user_rpc.UserVersionsRes.UserVersionsEntry
	15, // 2: user_rpc.UserListInfoRes.user_info:type_name -> user_rpc.UserListInfoRes.UserInfoEntry
	6,  // 3: user_rpc.SearchUserRes.user_info:type_name -> user_rpc.UserInfo
	6,  // 4: user_rpc.UserListInfoRes.UserInfoEntry.value:type_name -> user_rpc.UserInfo
	0,  // 5: user_rpc.user.UserCreate:input_type -> user_rpc.UserCreateReq
	2,  // 6: user_rpc.user.UserInfo:input_type -> user_rpc.UserInfoReq
	4,  // 7: user_rpc.user.IsFriend:input_type -> user_rpc.IsFriendReq
	12, // 8: user_rpc.user.SearchUser:input_type -> user_rpc.SearchUserReq
	10, // 9: user_rpc.user.UserListInfo:input_type -> user_rpc.UserListInfoReq
	8,  // 10: user_rpc.user.UserVersions:input_type -> user_rpc.UserVersionsReq
	1,  // 11: user_rpc.user.UserCreate:output_type -> user_rpc.UserCreateRes
	3,  // 12: user_rpc.user.UserInfo:output_type -> user_rpc.UserInfoRes
	5,  // 13: user_rpc.user.IsFriend:output_type -> user_rpc.IsFriendRes
	13, // 14: user_rpc.user.SearchUser:output_type -> user_rpc.SearchUserRes
	11, // 15: user_rpc.user.UserListInfo:output_type -> user_rpc.UserListInfoRes
	9,  // 16: user_rpc.user.UserVersions:output_type -> user_rpc.UserVersionsRes
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_rpc_proto_init() }
func file_user_rpc_proto_init() {
	if File_user_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_rpc_proto_goTypes,
		DependencyIndexes: file_user_rpc_proto_depIdxs,
		MessageInfos:      file_user_rpc_proto_msgTypes,
	}.Build()
	File_user_rpc_proto = out.File
	file_user_rpc_proto_goTypes = nil
	file_user_rpc_proto_depIdxs = nil
}
