
services:
  datasync_api:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/datasync_api:1.0.2
    container_name: datasync_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./datasync.yaml:/etc/datasync.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always

