// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: open_rpc.proto

package open

import (
	"context"

	"beaver/app/open/open_rpc/types/open_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateBotReq      = open_rpc.CreateBotReq
	CreateBotRes      = open_rpc.CreateBotRes
	DeleteBotReq      = open_rpc.DeleteBotReq
	DeleteBotRes      = open_rpc.DeleteBotRes
	ExchangeTokenReq  = open_rpc.ExchangeTokenReq
	ExchangeTokenRes  = open_rpc.ExchangeTokenRes
	GetUserInfoReq    = open_rpc.GetUserInfoReq
	GetUserInfoRes    = open_rpc.GetUserInfoRes
	RefreshTokenReq   = open_rpc.RefreshTokenReq
	RefreshTokenRes   = open_rpc.RefreshTokenRes
	ResetBotSecretReq = open_rpc.ResetBotSecretReq
	ResetBotSecretRes = open_rpc.ResetBotSecretRes
	ValidateTokenReq  = open_rpc.ValidateTokenReq
	ValidateTokenRes  = open_rpc.ValidateTokenRes

	Open interface {
		ExchangeToken(ctx context.Context, in *ExchangeTokenReq, opts ...grpc.CallOption) (*ExchangeTokenRes, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenRes, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error)
		CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*CreateBotRes, error)
		DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*DeleteBotRes, error)
		ResetBotSecret(ctx context.Context, in *ResetBotSecretReq, opts ...grpc.CallOption) (*ResetBotSecretRes, error)
	}

	defaultOpen struct {
		cli zrpc.Client
	}
)

func NewOpen(cli zrpc.Client) Open {
	return &defaultOpen{
		cli: cli,
	}
}

func (m *defaultOpen) ExchangeToken(ctx context.Context, in *ExchangeTokenReq, opts ...grpc.CallOption) (*ExchangeTokenRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.ExchangeToken(ctx, in, opts...)
}

func (m *defaultOpen) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultOpen) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultOpen) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultOpen) CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*CreateBotRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.CreateBot(ctx, in, opts...)
}

func (m *defaultOpen) DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*DeleteBotRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.DeleteBot(ctx, in, opts...)
}

func (m *defaultOpen) ResetBotSecret(ctx context.Context, in *ResetBotSecretReq, opts ...grpc.CallOption) (*ResetBotSecretRes, error) {
	client := open_rpc.NewOpenClient(m.cli.Conn())
	return client.ResetBotSecret(ctx, in, opts...)
}
