// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: group_rpc.proto

package server

import (
	"context"

	"beaver/app/group/group_rpc/internal/logic"
	"beaver/app/group/group_rpc/internal/svc"
	"beaver/app/group/group_rpc/types/group_rpc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group_rpc.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) GetGroupMembers(ctx context.Context, in *group_rpc.GetGroupMembersReq) (*group_rpc.GetGroupMembersRes, error) {
	l := logic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

func (s *GroupServer) GetUserGroupMembers(ctx context.Context, in *group_rpc.GetUserGroupMembersReq) (*group_rpc.GetUserGroupMembersRes, error) {
	l := logic.NewGetUserGroupMembersLogic(ctx, s.svcCtx)
	return l.GetUserGroupMembers(in)
}

func (s *GroupServer) GetUserGroupIDs(ctx context.Context, in *group_rpc.GetUserGroupIDsReq) (*group_rpc.GetUserGroupIDsRes, error) {
	l := logic.NewGetUserGroupIDsLogic(ctx, s.svcCtx)
	return l.GetUserGroupIDs(in)
}

func (s *GroupServer) GetGroupsListByIds(ctx context.Context, in *group_rpc.GetGroupsListByIdsReq) (*group_rpc.GetGroupsListByIdsRes, error) {
	l := logic.NewGetGroupsListByIdsLogic(ctx, s.svcCtx)
	return l.GetGroupsListByIds(in)
}

func (s *GroupServer) GetGroupMembersListByIds(ctx context.Context, in *group_rpc.GetGroupMembersListByIdsReq) (*group_rpc.GetGroupMembersListByIdsRes, error) {
	l := logic.NewGetGroupMembersListByIdsLogic(ctx, s.svcCtx)
	return l.GetGroupMembersListByIds(in)
}

func (s *GroupServer) GetGroupJoinRequestsListByIds(ctx context.Context, in *group_rpc.GetGroupJoinRequestsListByIdsReq) (*group_rpc.GetGroupJoinRequestsListByIdsRes, error) {
	l := logic.NewGetGroupJoinRequestsListByIdsLogic(ctx, s.svcCtx)
	return l.GetGroupJoinRequestsListByIds(in)
}

func (s *GroupServer) GetUserGroupRequestVersions(ctx context.Context, in *group_rpc.GetUserGroupRequestVersionsReq) (*group_rpc.GetUserGroupRequestVersionsRes, error) {
	l := logic.NewGetUserGroupRequestVersionsLogic(ctx, s.svcCtx)
	return l.GetUserGroupRequestVersions(in)
}
