// Code generated by goctl. DO NOT EDIT.
package types

type CreateAuthorityReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateAuthorityRes struct {
}

type CreateMenuReq struct {
	ParentId uint   `json:"parentId"`
	Path     string `json:"path"`
	Name     string `json:"name"`
	Hidden   bool   `json:"hidden"`
	Sort     int    `json:"sort"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	UserID   string `header:"Beaver-User-Id"`
}

type CreateMenuRes struct {
}

type DeleteMenuReq struct {
	Id     uint   `json:"id"`
	UserID string `header:"Beaver-User-Id"`
}

type DeleteMenuRes struct {
}

type GetMenuListReq struct {
	UserID string `header:"Beaver-User-Id"`
}

type GetMenuListRes struct {
	List []GetMenuListItem `json:"list"`
}

type UpdateAuthorityMenuReq struct {
	UserID string                        `header:"Beaver-User-Id"`
	Id     uint                          `json:"id"`
	Menus  []UpdateAuthorityMenuMenuItem `json:"menus"`
}

type UpdateAuthorityMenuRes struct {
}

type UpdateMenuReq struct {
	Id       uint   `json:"id"`
	ParentId uint   `json:"parentId"`
	Path     string `json:"path"`
	Name     string `json:"name"`
	Hidden   bool   `json:"hidden"`
	Sort     int    `json:"sort"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	UserID   string `header:"Beaver-User-Id"`
}

type UpdateMenuRes struct {
}
