// Code generated by goctl. DO NOT EDIT.
package types

type AddAppReq struct {
	Name        string `json:"name"`                 // 应用名称
	Description string `json:"description,optional"` // 应用描述
}

type AddAppRes struct {
	Id    uint   `json:"id"`    // 创建的应用ID
	AppID string `json:"appId"` // 系统生成的应用唯一标识
}

type AddArchitectureReq struct {
	AppID       string `json:"appId"`                // 应用ID
	PlatformID  uint   `json:"platformId"`           // 平台ID：1=Windows, 2=MacOS, 3=Android
	ArchID      uint   `json:"archId"`               // 架构ID：1=WinX64, 2=WinArm64, 3=MacIntel, 4=MacApple, 5=Android
	Description string `json:"description,optional"` // 描述
}

type AddArchitectureRes struct {
	Id uint `json:"id"` // 创建的记录ID
}

type AddEmojiInfo struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}

type AddEmojiToPackageReq struct {
	PackageId string       `json:"packageId"`
	FileKey   string       `json:"fileKey"`
	Title     string       `json:"title"`
	EmojiInfo AddEmojiInfo `json:"emojiInfo"`
	AuthorID  string       `header:"Beaver-User-Id"`
}

type AddEmojiToPackageRes struct {
	RelationId string `json:"relationId"`
}

type AddVersionReq struct {
	ArchitectureID uint   `json:"architectureId"`        // 架构ID
	Version        string `json:"version"`               // 版本号
	FileKey        string `json:"fileKey"`               // 文件ID
	Description    string `json:"description,optional"`  // 版本描述
	ReleaseNotes   string `json:"releaseNotes,optional"` // 更新日志
}

type AddVersionRes struct {
	VersionID uint `json:"versionId"` // 创建的版本ID
}

type AdminUnifiedSearchReq struct {
	Keyword string `form:"keyword"`
	Limit   int    `form:"limit,default=10"`
}

type AdminUnifiedSearchRes struct {
	Users         []SearchUserHit         `json:"users"`
	Groups        []SearchGroupHit        `json:"groups"`
	Messages      []SearchMessageHit      `json:"messages"`
	Conversations []SearchConversationHit `json:"conversations"`
}

type AdminUserInfo struct {
	Id             uint     `json:"id"`
	UserID         string   `json:"userId"`
	NickName       string   `json:"nickName"`
	Phone          string   `json:"phone"`
	Status         int8     `json:"status"`
	LastLoginAt    int64    `json:"lastLoginAt"`
	CreatedAt      string   `json:"createdAt"`
	AuthorityIds   []uint   `json:"authorityIds"`
	AuthorityNames []string `json:"authorityNames"`
}

type ApplyDeveloperReq struct {
	ApplicantUserID string `json:"applicantUserId,optional"` // 代申请目标用户ID，空则取当前登录用户
	RealName        string `json:"realName"`
	CompanyName     string `json:"companyName,optional"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
	Description     string `json:"description,optional"`
	UserID          string `header:"Beaver-User-Id"` // 操作人ID（由网关注入）
}

type ApplyDeveloperRes struct {
	ID string `json:"id"`
}

type AuditDeveloperReq struct {
	ID          string `json:"id"`
	Status      int    `json:"status"` // 1通过 2拒绝
	AuditRemark string `json:"auditRemark,optional"`
	UserID      string `header:"Beaver-User-Id"` // 审核人ID（由网关注入）
}

type AuditDeveloperRes struct {
}

type AuditOpenAppReq struct {
	AppID       string `json:"appId"`
	Status      int    `json:"status"` // 1通过 2拒绝
	AuditRemark string `json:"auditRemark,optional"`
	UserID      string `header:"Beaver-User-Id"`
}

type AuditOpenAppRes struct {
}

type AuthenticationReq struct {
	Token     string `header:"Token,optional"`     // string JWT，可选
	ValidPath string `header:"ValidPath,optional"` // string 当前请求路径，用于白名单判断
}

type AuthenticationRes struct {
	UserID string `json:"userId"` // string 管理员用户 ID
}

type AuthorityInfo struct {
	Id          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int8   `json:"status"`
	Sort        int    `json:"sort"`
	MenuCount   int64  `json:"menuCount"`
}

type BatchDeleteChatMessagesReq struct {
	Ids []string `json:"ids"`
}

type BatchDeleteChatMessagesRes struct {
}

type BatchDeleteFileReq struct {
	Ids []uint `json:"ids"`
}

type BatchDeleteFileRes struct {
}

type BatchDeleteFriendVerifyReq struct {
	Ids []string `json:"ids"`
}

type BatchDeleteFriendVerifyRes struct {
}

type BatchDeleteFriendsReq struct {
	Ids []string `json:"ids"`
}

type BatchDeleteFriendsRes struct {
}

type BatchDeleteUsersReq struct {
	Ids []string `json:"ids"`
}

type BatchDeleteUsersRes struct {
}

type BatchRestoreChatMessagesReq struct {
	Ids []string `json:"ids"`
}

type BatchRestoreChatMessagesRes struct {
}

type BatchUpdateUserStatusReq struct {
	Ids    []string `json:"ids"`
	Status int      `json:"status"`
}

type BatchUpdateUserStatusRes struct {
}

type CaseContextGroup struct {
	GroupID string `json:"groupId"`
	Title   string `json:"title"`
	Status  int    `json:"status"`
}

type CaseContextMessage struct {
	MessageID      string `json:"messageId"`
	ConversationID string `json:"conversationId"`
	SendUserID     string `json:"sendUserId"`
	SendUserName   string `json:"sendUserName"`
	MsgPreview     string `json:"msgPreview"`
	IsDeleted      bool   `json:"isDeleted"`
	CreateTime     string `json:"createTime"`
}

type CaseContextMoment struct {
	MomentID string `json:"momentId"`
	UserID   string `json:"userId"`
	Content  string `json:"content"`
}

type CaseContextUser struct {
	UserID   string `json:"userId"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Status   int    `json:"status"`
}

type ClearConversationReq struct {
	ConversationID string `json:"conversationId"`
}

type ClearConversationRes struct {
}

type ContentReportInfo struct {
	ID             uint64 `json:"id"`
	ReporterUserID string `json:"reporterUserId"`
	ReporterName   string `json:"reporterName"`
	TargetType     int    `json:"targetType"`
	TargetID       string `json:"targetId"`
	ReasonType     int    `json:"reasonType"`
	Content        string `json:"content"`
	Status         int    `json:"status"`
	CaseID         uint64 `json:"caseId"`
	CreatedAt      string `json:"createdAt"`
}

type CreateAdminUserReq struct {
	NickName     string `json:"nickName"`
	Phone        string `json:"phone"`
	Password     string `json:"password"`
	AuthorityIds []uint `json:"authorityIds"`
	OperatorID   string `header:"Beaver-User-Id"`
}

type CreateAdminUserRes struct {
	UserID string `json:"userId"`
}

type CreateAuthorityReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateAuthorityRes struct {
}

type CreateBucketReq struct {
	UserID      string `header:"Beaver-User-Id"` // 用户ID
	Name        string `json:"name"`             // Bucket名称
	Description string `json:"description"`      // Bucket描述
}

type CreateBucketRes struct {
	BucketId string `json:"bucketId"` // 创建的Bucket ID
}

type CreateEmojiPackageReq struct {
	Title       string  `json:"title"`
	CoverFile   *string `json:"coverFile,optional"`
	UserID      string  `header:"Beaver-User-Id"`
	Description string  `json:"description"`
	Type        string  `json:"type"`
}

type CreateEmojiPackageRes struct {
	PackageId string `json:"packageId"`
}

type CreateEmojiReq struct {
	FileKey   string    `json:"fileKey"`
	Title     string    `json:"title"`
	EmojiInfo EmojiInfo `json:"emojiInfo"`
	AuthorID  string    `header:"Beaver-User-Id"`
}

type CreateEmojiRes struct {
	EmojiId string `json:"emojiId"`
}

type CreateMenuReq struct {
	ParentId uint   `json:"parentId"`
	Path     string `json:"path"`
	Name     string `json:"name"`
	Hidden   bool   `json:"hidden"`
	Sort     int    `json:"sort"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	UserID   string `header:"Beaver-User-Id"`
}

type CreateMenuRes struct {
}

type CreateModerationCaseReq struct {
	TargetType  int    `json:"targetType"`
	TargetID    string `json:"targetId"`
	Title       string `json:"title"`
	Description string `json:"description,optional"`
	Priority    int    `json:"priority,optional"`
	UserID      string `header:"Beaver-User-Id"`
}

type CreateModerationCaseRes struct {
	CaseID uint64 `json:"caseId"`
	CaseNo string `json:"caseNo"`
}

type CreateSensitiveWordReq struct {
	Word     string `json:"word"`
	Category string `json:"category,optional"`
	Level    int    `json:"level,optional"`
	Remark   string `json:"remark,optional"`
	UserID   string `header:"Beaver-User-Id"`
}

type CreateSensitiveWordRes struct {
	ID uint64 `json:"id"`
}

type CreateUserReq struct {
	NickName string `json:"nickName"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Abstract string `json:"abstract,optional"`
	UserID   string `header:"Beaver-User-Id"`
}

type CreateUserRes struct {
	Id string `json:"id"`
}

type DashboardInboxItem struct {
	Category  string `json:"category"`
	Title     string `json:"title"`
	Summary   string `json:"summary"`
	EntityID  string `json:"entityId"`
	CreatedAt string `json:"createdAt"`
	Action    string `json:"action"`
}

type DashboardTrendSeries struct {
	Key    string  `json:"key"`
	Label  string  `json:"label"`
	Values []int64 `json:"values"`
}

type DeleteAuthorityReq struct {
	Id uint `json:"id"`
}

type DeleteAuthorityRes struct {
}

type DeleteBucketReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	BucketId string `json:"bucketId"`         // Bucket ID
}

type DeleteBucketRes struct {
}

type DeleteChatMessageReq struct {
	MessageID string `path:"id"`
}

type DeleteChatMessageRes struct {
}

type DeleteEmojiPackageReq struct {
	PackageId string `json:"packageId"`
}

type DeleteEmojiPackageRes struct {
}

type DeleteEmojiReq struct {
	EmojiId string `path:"emojiId"`
}

type DeleteEmojiRes struct {
}

type DeleteFeedbackReq struct {
	Id uint `path:"id"`
}

type DeleteFeedbackRes struct {
}

type DeleteFileReq struct {
	Id uint `path:"id"`
}

type DeleteFileRes struct {
}

type DeleteFriendReq struct {
	FriendID string `path:"id"`
}

type DeleteFriendRes struct {
}

type DeleteFriendVerifyReq struct {
	VerifyID string `json:"verifyId"`
}

type DeleteFriendVerifyRes struct {
}

type DeleteGroupReq struct {
	Id uint `path:"id"`
}

type DeleteGroupRes struct {
}

type DeleteMenuReq struct {
	Id     uint   `json:"id"`
	UserID string `header:"Beaver-User-Id"`
}

type DeleteMenuRes struct {
}

type DeleteMessagesByTypeReq struct {
	ConversationID string `json:"conversationId,optional"`
	MsgType        int    `json:"msgType"`
	StartTime      string `json:"startTime,optional"`
	EndTime        string `json:"endTime,optional"`
}

type DeleteMessagesByTypeRes struct {
	DeletedCount int64 `json:"deletedCount"`
}

type DeleteMomentCommentReq struct {
	CommentId string `path:"commentId"`
}

type DeleteMomentCommentRes struct {
}

type DeleteMomentReq struct {
	MomentId string `path:"momentId"`
}

type DeleteMomentRes struct {
}

type DeleteSensitiveWordReq struct {
	ID     uint64 `path:"id"`
	UserID string `header:"Beaver-User-Id"`
}

type DeleteSensitiveWordRes struct {
}

type DeleteUserReq struct {
	UserID string `path:"id"`
}

type DeleteUserRes struct {
}

type DeleteVersionReq struct {
	VersionID uint `path:"id"`
}

type DeleteVersionRes struct {
}

type DeveloperInfo struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	RealName    string `json:"realName"`
	CompanyName string `json:"companyName"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	Description string `json:"description"`
	Status      int    `json:"status"`
	AuditBy     string `json:"auditBy"`
	AuditTime   int64  `json:"auditTime"`
	AuditRemark string `json:"auditRemark"`
	CreatedAt   int64  `json:"createdAt"`
}

type EmojiInfo struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}

type EscalateContentReportReq struct {
	ReportID uint64 `json:"reportId"`
	Priority int    `json:"priority,optional"`
	UserID   string `header:"Beaver-User-Id"`
}

type EscalateContentReportRes struct {
	CaseID uint64 `json:"caseId"`
	CaseNo string `json:"caseNo"`
}

type ExecuteUserControlReq struct {
	UserID     string `json:"userId"`
	Action     string `json:"action"`
	Reason     string `json:"reason,optional"`
	CaseID     uint64 `json:"caseId,optional"`
	OperatorID string `header:"Beaver-User-Id"`
}

type ExecuteUserControlRes struct {
}

type FileUploadLocalReq struct {
	UserID string `header:"Beaver-User-Id"`
	Source string `form:"source"` // 文件来源：qiniu 或 local
}

type FileUploadLocalRes struct {
	FileKey      string `json:"fileKey"`
	OriginalName string `json:"originalName"`
}

type FileUploadQiniuReq struct {
	UserID string `header:"Beaver-User-Id"`
	Source string `form:"source,optional"` // 文件来源：qiniu 或 local
}

type FileUploadQiniuRes struct {
	FileKey      string `json:"fileKey"`
	OriginalName string `json:"originalName"`
}

type GetAdminUserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
	Status   int8   `form:"status,optional"`
}

type GetAdminUserListRes struct {
	List  []AdminUserInfo `json:"list"`
	Total int64           `json:"total"`
}

type GetAppVersionsItem struct {
	ArchitectureID uint                        `json:"architectureId"` // 架构ID
	ArchID         uint                        `json:"archId"`         // 架构类型
	Description    string                      `json:"description"`    // 架构描述
	Versions       []GetAppVersionsVersionItem `json:"versions"`       // 该架构下的版本列表
}

type GetAppVersionsReq struct {
	AppID    string `form:"appId"`             // 应用ID
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
}

type GetAppVersionsRes struct {
	Total         int64                `json:"total"`         // 总架构数
	Architectures []GetAppVersionsItem `json:"architectures"` // 按架构分组的版本信息
}

type GetAppVersionsVersionItem struct {
	VersionID uint   `json:"versionId"` // 版本ID
	Version   string `json:"version"`   // 版本号
}

type GetAppsItem struct {
	Id          uint   `json:"id"`          // 应用ID
	AppID       string `json:"appId"`       // 应用唯一标识
	Name        string `json:"name"`        // 应用名称
	Description string `json:"description"` // 应用描述
	IsActive    bool   `json:"isActive"`    // 是否活跃
	CreatedAt   string `json:"createdAt"`   // 创建时间
	UpdatedAt   string `json:"updatedAt"`   // 更新时间
}

type GetAppsReq struct {
	Page     int  `form:"page,optional"`     // 页码
	PageSize int  `form:"pageSize,optional"` // 每页数量
	IsActive bool `form:"isActive,optional"` // 是否仅显示活跃应用
}

type GetAppsRes struct {
	Total int64         `json:"total"` // 总数
	Apps  []GetAppsItem `json:"apps"`  // 应用列表
}

type GetArchitecturesItem struct {
	Id          uint   `json:"id"`          // 记录ID
	AppID       string `json:"appId"`       // 应用ID
	AppName     string `json:"appName"`     // 应用名称
	PlatformID  uint   `json:"platformId"`  // 平台ID：1=Windows, 2=MacOS, 3=Android
	ArchID      uint   `json:"archId"`      // 架构ID：1=WinX64, 2=WinArm64, 3=MacIntel, 4=MacApple, 5=Android
	Description string `json:"description"` // 描述
	IsActive    bool   `json:"isActive"`    // 是否启用
	CreatedAt   string `json:"createdAt"`   // 创建时间
	UpdatedAt   string `json:"updatedAt"`   // 更新时间
}

type GetArchitecturesReq struct {
	AppID    string `form:"appId,optional"`    // 应用ID
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	IsActive bool   `form:"isActive,optional"` // 是否仅显示活跃架构
}

type GetArchitecturesRes struct {
	Total         int64                  `json:"total"`         // 总数
	Architectures []GetArchitecturesItem `json:"architectures"` // 架构列表
}

type GetAuthorityListReq struct {
}

type GetAuthorityListRes struct {
	List []AuthorityInfo `json:"list"`
}

type GetAuthorityMenusReq struct {
	Id uint `path:"id"`
}

type GetAuthorityMenusRes struct {
	MenuIds []uint `json:"menuIds"`
}

type GetBucketListItem struct {
	BucketId    string `json:"bucketId"`    // Bucket ID
	Name        string `json:"name"`        // Bucket名称
	Description string `json:"description"` // Bucket描述
	CreateUser  string `json:"createUser"`  // 创建者
	IsActive    bool   `json:"isActive"`    // 是否激活
	CreatedAt   string `json:"createdAt"`   // 创建时间
	UpdatedAt   string `json:"updatedAt"`   // 更新时间
}

type GetBucketListReq struct {
	UserID   string `header:"Beaver-User-Id"`    // 用户ID
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=10"` // 每页大小
	Keyword  string `form:"keyword,optional"`    // 关键词搜索(名称或描述)
	IsActive *bool  `form:"isActive,optional"`   // 是否激活
}

type GetBucketListRes struct {
	List  []GetBucketListItem `json:"list"`  // Bucket列表
	Total int64               `json:"total"` // 总数
}

type GetChatMessageDetailReq struct {
	MessageID string `path:"id"`
}

type GetChatMessageDetailRes struct {
	Id               string `json:"id"`
	MessageID        string `json:"messageId"`
	ConversationID   string `json:"conversationId"`
	SendUserID       string `json:"sendUserId"`
	SendUserName     string `json:"sendUserName"`
	SendUserFileName string `json:"sendUserFileName"`
	MsgType          int    `json:"msgType"`
	MsgPreview       string `json:"msgPreview"`
	MsgContent       string `json:"msgContent"`
	IsDeleted        bool   `json:"isDeleted"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type GetChatMessageListItem struct {
	Id               string `json:"id"`
	MessageID        string `json:"messageId"`
	ConversationID   string `json:"conversationId"`
	ConversationType int    `json:"conversationType"`
	SendUserID       string `json:"sendUserId"`
	SendUserName     string `json:"sendUserName"`
	MsgType          int    `json:"msgType"`
	MsgPreview       string `json:"msgPreview"`
	MsgContent       string `json:"msgContent,optional"`
	IsDeleted        bool   `json:"isDeleted"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type GetChatMessageListReq struct {
	Page           int    `form:"page,default=1"`
	PageSize       int    `form:"pageSize,default=10"`
	ConversationID string `form:"conversationId,optional"` // 按会话ID筛选
	SendUserID     string `form:"sendUserId,optional"`     // 按发送者ID筛选
	MsgType        int    `form:"msgType,optional"`        // 按消息类型筛选
	IsDeleted      bool   `form:"isDeleted,optional"`      // 按删除状态筛选
	StartTime      string `form:"startTime,optional"`
	EndTime        string `form:"endTime,optional"`
	Order          int    `form:"order,optional"`       // 1正序时间线 2倒序
	WithContent    bool   `form:"withContent,optional"` // 是否返回完整内容
}

type GetChatMessageListRes struct {
	List  []GetChatMessageListItem `json:"list"`
	Total int64                    `json:"total"`
}

type GetChatSessionListItem struct {
	ConversationID   string   `json:"conversationId"`
	ConversationType int      `json:"conversationType"`
	Title            string   `json:"title"`
	PeerUserID       string   `json:"peerUserId"`
	PeerUserName     string   `json:"peerUserName"`
	ParticipantIDs   []string `json:"participantIds"`
	ParticipantNames []string `json:"participantNames"`
	LastMessage      string   `json:"lastMessage"`
	LastMessageTime  string   `json:"lastMessageTime"`
	MessageCount     int64    `json:"messageCount"`
}

type GetChatSessionListReq struct {
	UserID           string `form:"userId"`
	ConversationType int    `form:"conversationType,optional"`
	Page             int    `form:"page,default=1"`
	PageSize         int    `form:"pageSize,default=20"`
}

type GetChatSessionListRes struct {
	List  []GetChatSessionListItem `json:"list"`
	Total int64                    `json:"total"`
}

type GetCityStrategiesItem struct {
	Id        uint                            `json:"id"`        // 策略ID
	AppID     string                          `json:"appId"`     // 应用ID
	CityID    string                          `json:"cityId"`    // 城市代码
	Strategy  []GetCityStrategiesStrategyItem `json:"strategy"`  // 城市策略配置
	IsActive  bool                            `json:"isActive"`  // 是否启用
	CreatedAt string                          `json:"createdAt"` // 创建时间
	UpdatedAt string                          `json:"updatedAt"` // 更新时间
}

type GetCityStrategiesReq struct {
	AppID    string `form:"appId,optional"`    // 应用ID
	IsActive bool   `form:"isActive,optional"` // 是否仅查询活跃策略
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
}

type GetCityStrategiesRes struct {
	Total      int64                   `json:"total"`      // 总数
	Strategies []GetCityStrategiesItem `json:"strategies"` // 策略列表
}

type GetCityStrategiesStrategyItem struct {
	ArchitectureID uint   `json:"architectureId"` // 架构ID
	VersionID      uint   `json:"versionId"`      // 版本ID
	Version        string `json:"version"`        // 版本号
	ForceUpdate    bool   `json:"forceUpdate"`    // 是否强制更新
	IsActive       bool   `json:"isActive"`       // 是否启用
}

type GetContentReportListReq struct {
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=10"`
	Status     int    `form:"status,optional"`
	TargetType int    `form:"targetType,optional"`
	TargetID   string `form:"targetId,optional"`
}

type GetContentReportListRes struct {
	List  []ContentReportInfo `json:"list"`
	Total int64               `json:"total"`
}

type GetDashboardInboxReq struct {
	Limit int `form:"limit,default=20"`
}

type GetDashboardInboxRes struct {
	List  []DashboardInboxItem `json:"list"`
	Total int64                `json:"total"`
}

type GetDashboardOverviewReq struct {
}

type GetDashboardOverviewRes struct {
	UserTotal             int64 `json:"userTotal"`
	GroupTotal            int64 `json:"groupTotal"`
	FriendTotal           int64 `json:"friendTotal"`
	MessageTotal          int64 `json:"messageTotal"`
	MomentTotal           int64 `json:"momentTotal"`
	BlockTotal            int64 `json:"blockTotal"`
	PendingDeveloperCount int64 `json:"pendingDeveloperCount"`
	PendingAppCount       int64 `json:"pendingAppCount"`
	PendingFeedbackCount  int64 `json:"pendingFeedbackCount"`
	PendingReportCount    int64 `json:"pendingReportCount"`
	PendingCaseCount      int64 `json:"pendingCaseCount"`
}

type GetDashboardTrendsReq struct {
	Days int `form:"days,default=7"`
}

type GetDashboardTrendsRes struct {
	Days   []string               `json:"days"`
	Series []DashboardTrendSeries `json:"series"`
}

type GetDeveloperListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=10"`
	Status   int `form:"status,optional"` // 0待审核 1已通过 2已拒绝
}

type GetDeveloperListRes struct {
	Total int64           `json:"total"`
	List  []DeveloperInfo `json:"list"`
}

type GetEmojiCollectListItem struct {
	CollectId    string `json:"collectId"`
	UserID       string `json:"userId"`
	EmojiId      string `json:"emojiId"`
	EmojiTitle   string `json:"emojiTitle"`
	EmojiFileKey string `json:"emojiFileKey"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetEmojiCollectListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	UserID    string `form:"userId,optional"`  // 按用户ID筛选
	EmojiID   string `form:"emojiId,optional"` // 按表情图片ID筛选
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiCollectListRes struct {
	List  []GetEmojiCollectListItem `json:"list"`
	Total int64                     `json:"total"`
}

type GetEmojiListItem struct {
	EmojiId    string `json:"emojiId"`
	FileKey    string `json:"fileKey"`
	Title      string `json:"title"`
	AuthorID   string `json:"authorId"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type GetEmojiListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	AuthorID  string `form:"authorId,optional"` // 按创建者ID筛选
	Title     string `form:"title,optional"`    // 按表情图片名称搜索
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiListRes struct {
	List  []GetEmojiListItem `json:"list"`
	Total int64              `json:"total"`
}

type GetEmojiPackageEmojisItem struct {
	EmojiId    string `json:"emojiId"`
	FileKey    string `json:"fileKey"`
	Title      string `json:"title"`
	AuthorID   string `json:"authorId"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type GetEmojiPackageEmojisReq struct {
	PackageId string `form:"packageId"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=50"`
}

type GetEmojiPackageEmojisRes struct {
	List  []GetEmojiPackageEmojisItem `json:"list"`
	Total int64                       `json:"total"`
}

type GetEmojiPackageListItem struct {
	PackageId   string `json:"packageId"`
	Title       string `json:"title"`
	CoverFile   string `json:"coverFile"`
	UserID      string `json:"userId"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Status      int    `json:"status"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type GetEmojiPackageListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	UserID    string `form:"userId,optional"` // 按创建者ID筛选
	Type      string `form:"type,optional"`   // 按类型筛选
	Status    int    `form:"status,optional"` // 按状态筛选
	Title     string `form:"title,optional"`  // 按表情包集合名称搜索
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiPackageListRes struct {
	List  []GetEmojiPackageListItem `json:"list"`
	Total int64                     `json:"total"`
}

type GetEventListItem struct {
	Id         uint   `json:"id"`         // 事件ID
	EventName  string `json:"eventName"`  // 事件名称
	Action     string `json:"action"`     // 操作
	UserID     string `json:"userId"`     // 用户ID
	BucketID   string `json:"bucketId"`   // Bucket Id
	BucketName string `json:"bucketName"` // Bucket名称
	Platform   string `json:"platform"`   // 平台
	DeviceID   string `json:"deviceId"`   // 设备ID
	Data       string `json:"data"`       // 事件数据(JSON格式)
	Timestamp  int64  `json:"timestamp"`  // 事件时间戳(毫秒)
	CreatedAt  string `json:"createdAt"`  // 创建时间
}

type GetEventListReq struct {
	UserID     string `header:"Beaver-User-Id"`    // 用户ID
	Page       int    `form:"page,default=1"`      // 页码
	PageSize   int    `form:"pageSize,default=20"` // 每页大小
	BucketID   string `form:"bucketId,optional"`   // Bucket ID筛选
	EventName  string `form:"eventName,optional"`  // 事件名称筛选
	Action     string `form:"action,optional"`     // 操作筛选
	UserFilter string `form:"userFilter,optional"` // 用户ID筛选
	StartTime  int64  `form:"startTime,optional"`  // 开始时间戳(毫秒)
	EndTime    int64  `form:"endTime,optional"`    // 结束时间戳(毫秒)
	Platform   string `form:"platform,optional"`   // 平台筛选
}

type GetEventListRes struct {
	List  []GetEventListItem `json:"list"`  // 事件列表
	Total int64              `json:"total"` // 总数
}

type GetFeedbackDetailReq struct {
	Id uint `path:"id"`
}

type GetFeedbackDetailRes struct {
	Id           uint     `json:"id"`
	UserId       string   `json:"userId"`
	Content      string   `json:"content"`
	Type         int      `json:"type"`
	Status       int      `json:"status"`
	FileNames    []string `json:"fileNames"`
	HandlerId    int64    `json:"handlerId"`
	HandleTime   string   `json:"handleTime"`
	HandleResult string   `json:"handleResult"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
}

type GetFeedbackListItem struct {
	Id           uint     `json:"id"`
	UserId       string   `json:"userId"`
	Content      string   `json:"content"`
	Type         int      `json:"type"`
	Status       int      `json:"status"`
	FileNames    []string `json:"fileNames"`
	HandlerId    int64    `json:"handlerId"`
	HandleTime   string   `json:"handleTime"`
	HandleResult string   `json:"handleResult"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
}

type GetFeedbackListReq struct {
	Page     int    `form:"page,optional"`
	Limit    int    `form:"limit,optional"`
	Status   int    `form:"status,optional"`   // 反馈状态筛选
	Type     int    `form:"type,optional"`     // 反馈类型筛选
	UserID   string `form:"userId,optional"`   // 用户ID筛选
	Keywords string `form:"keywords,optional"` // 关键词搜索
}

type GetFeedbackListRes struct {
	List  []GetFeedbackListItem `json:"list"`
	Total int64                 `json:"total"`
}

type GetFileDetailReq struct {
	Id uint `path:"id"`
}

type GetFileDetailRes struct {
	Id           uint   `json:"id"`
	FileName     string `json:"fileName"`
	OriginalName string `json:"originalName"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
	Md5          string `json:"md5"`
	Type         string `json:"type"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type GetFileListItem struct {
	Id           uint   `json:"id"`
	FileName     string `json:"fileName"`
	OriginalName string `json:"originalName"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
	Md5          string `json:"md5"`
	Type         string `json:"type"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type GetFileListReq struct {
	Page     int    `form:"page,optional"`
	Limit    int    `form:"limit,optional"`
	Type     string `form:"type,optional"`     // 文件类型筛选
	Keywords string `form:"keywords,optional"` // 文件名关键词搜索
}

type GetFileListRes struct {
	List  []GetFileListItem `json:"list"`
	Total int64             `json:"total"`
}

type GetFriendBlockListItem struct {
	Id              string `json:"id"`
	UserID          string `json:"userId"`
	UserName        string `json:"userName"`
	BlockedUserID   string `json:"blockedUserId"`
	BlockedUserName string `json:"blockedUserName"`
	CreateTime      string `json:"createTime"`
}

type GetFriendBlockListReq struct {
	Page          int    `form:"page,default=1"`
	PageSize      int    `form:"pageSize,default=10"`
	UserID        string `form:"userId,optional"`
	BlockedUserID string `form:"blockedUserId,optional"`
}

type GetFriendBlockListRes struct {
	List  []GetFriendBlockListItem `json:"list"`
	Total int64                    `json:"total"`
}

type GetFriendDetailReq struct {
	FriendID string `path:"id"`
}

type GetFriendDetailRes struct {
	Id               string `json:"id"`
	SendUserId       string `json:"sendUserId"`
	SendUserName     string `json:"sendUserName"`
	SendUserFileName string `json:"sendUserFileName"`
	RevUserId        string `json:"revUserId"`
	RevUserName      string `json:"revUserName"`
	RevUserFileName  string `json:"revUserFileName"`
	SendUserNotice   string `json:"sendUserNotice"`
	RevUserNotice    string `json:"revUserNotice"`
	IsDeleted        bool   `json:"isDeleted"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type GetFriendListItem struct {
	Id             string `json:"id"`
	SendUserId     string `json:"sendUserId"`
	SendUserName   string `json:"sendUserName"`
	RevUserId      string `json:"revUserId"`
	RevUserName    string `json:"revUserName"`
	SendUserNotice string `json:"sendUserNotice"`
	RevUserNotice  string `json:"revUserNotice"`
	IsDeleted      bool   `json:"isDeleted"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type GetFriendListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	UserID    string `form:"userId,optional"`    // 按用户ID筛选
	FriendID  string `form:"friendId,optional"`  // 按好友ID筛选
	IsDeleted bool   `form:"isDeleted,optional"` // 按删除状态筛选
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetFriendListRes struct {
	List  []GetFriendListItem `json:"list"`
	Total int64               `json:"total"`
}

type GetFriendVerifyDetailReq struct {
	VerifyID string `form:"verifyId"`
}

type GetFriendVerifyDetailRes struct {
	Id               string `json:"id"`
	SendUserId       string `json:"sendUserId"`
	SendUserName     string `json:"sendUserName"`
	SendUserFileName string `json:"sendUserFileName"`
	RevUserId        string `json:"revUserId"`
	RevUserName      string `json:"revUserName"`
	RevUserFileName  string `json:"revUserFileName"`
	SendStatus       int    `json:"sendStatus"`
	RevStatus        int    `json:"revStatus"`
	Message          string `json:"message"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type GetFriendVerifyListItem struct {
	Id           string `json:"id"`
	SendUserId   string `json:"sendUserId"`
	SendUserName string `json:"sendUserName"`
	RevUserId    string `json:"revUserId"`
	RevUserName  string `json:"revUserName"`
	SendStatus   int    `json:"sendStatus"`
	RevStatus    int    `json:"revStatus"`
	Message      string `json:"message"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetFriendVerifyListReq struct {
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=10"`
	SendUserId string `form:"sendUserId,optional"`
	RevUserId  string `form:"revUserId,optional"`
	SendStatus int    `form:"sendStatus,optional"` // 0:未处理 1:已通过 2:已拒绝 3:忽略 4:删除
	RevStatus  int    `form:"revStatus,optional"`
	StartTime  string `form:"startTime,optional"`
	EndTime    string `form:"endTime,optional"`
}

type GetFriendVerifyListRes struct {
	List  []GetFriendVerifyListItem `json:"list"`
	Total int64                     `json:"total"`
}

type GetGroupDetailReq struct {
	Id uint `path:"id"`
}

type GetGroupDetailRes struct {
	Id        uint   `json:"id"`
	GroupId   string `json:"groupId"`
	Type      int    `json:"type"`
	Title     string `json:"title"`
	FileName  string `json:"fileName"`
	CreatorId string `json:"creatorId"`
	Notice    string `json:"notice"`
	Status    int    `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetGroupListItem struct {
	Id        uint   `json:"id"`
	GroupId   string `json:"groupId"`
	Type      int    `json:"type"`
	Title     string `json:"title"`
	FileName  string `json:"fileName"`
	CreatorId string `json:"creatorId"`
	Notice    string `json:"notice"`
	Status    int    `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetGroupListReq struct {
	Page     int    `form:"page,optional"`
	Limit    int    `form:"limit,optional"`
	Status   int    `form:"status,optional"`   // 群状态筛选
	Type     int    `form:"type,optional"`     // 群类型筛选
	Keywords string `form:"keywords,optional"` // 群名关键词搜索
}

type GetGroupListRes struct {
	List  []GetGroupListItem `json:"list"`
	Total int64              `json:"total"`
}

type GetGroupMemberListItem struct {
	Id              uint   `json:"id"`
	GroupId         string `json:"groupId"`
	UserId          string `json:"userId"`
	MemberNickname  string `json:"memberNickname"`
	Role            int    `json:"role"`
	ProhibitionTime int    `json:"prohibitionTime"`
	InviterId       string `json:"inviterId"`
	Status          int    `json:"status"`
	NotifyLevel     int    `json:"notifyLevel"`
	DisplayName     string `json:"displayName"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type GetGroupMemberListReq struct {
	Page    int    `form:"page,optional"`
	Limit   int    `form:"limit,optional"`
	GroupId string `form:"groupId"`
	Role    int    `form:"role,optional"`   // 成员角色筛选
	Status  int    `form:"status,optional"` // 成员状态筛选
}

type GetGroupMemberListRes struct {
	List  []GetGroupMemberListItem `json:"list"`
	Total int64                    `json:"total"`
}

type GetGroupOperationsProfileReq struct {
	GroupID string `path:"groupId"`
}

type GetGroupOperationsProfileRes struct {
	Profile      GroupOpsProfileInfo   `json:"profile"`
	MemberTotal  int64                 `json:"memberTotal"`
	MessageTotal int64                 `json:"messageTotal"`
	ReportTotal  int64                 `json:"reportTotal"`
	Members      []GroupOpsMemberItem  `json:"members"`
	Messages     []GroupOpsMessageItem `json:"messages"`
	Reports      []GroupOpsReportItem  `json:"reports"`
}

type GetMenuListItem struct {
	Id       uint   `json:"id"`
	ParentId uint   `json:"parentId"`
	Path     string `json:"path"`
	Name     string `json:"name"`
	Hidden   bool   `json:"hidden"`
	Sort     int    `json:"sort"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
}

type GetMenuListReq struct {
	UserID string `header:"Beaver-User-Id"`
}

type GetMenuListRes struct {
	List []GetMenuListItem `json:"list"`
}

type GetModerationCaseContextReq struct {
	CaseID uint64 `path:"id"`
}

type GetModerationCaseContextRes struct {
	Case           ModerationCaseInfo   `json:"case"`
	TargetUser     *CaseContextUser     `json:"targetUser,optional"`
	TargetMessage  *CaseContextMessage  `json:"targetMessage,optional"`
	TargetMoment   *CaseContextMoment   `json:"targetMoment,optional"`
	TargetGroup    *CaseContextGroup    `json:"targetGroup,optional"`
	RelatedReports []ContentReportInfo  `json:"relatedReports"`
	RecentMessages []CaseContextMessage `json:"recentMessages"`
}

type GetModerationCaseDetailReq struct {
	CaseID uint64 `path:"id"`
}

type GetModerationCaseDetailRes struct {
	Case ModerationCaseInfo `json:"case"`
}

type GetModerationCaseListReq struct {
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=10"`
	Status     int    `form:"status,optional"`
	TargetType int    `form:"targetType,optional"`
	Keyword    string `form:"keyword,optional"`
}

type GetModerationCaseListRes struct {
	List  []ModerationCaseInfo `json:"list"`
	Total int64                `json:"total"`
}

type GetMomentCommentListItem struct {
	CommentId string `json:"commentId"`
	MomentId  string `json:"momentId"`
	UserId    string `json:"userId"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetMomentCommentListReq struct {
	Page     int    `form:"page,optional"`
	Limit    int    `form:"limit,optional"`
	MomentId string `form:"momentId"`
}

type GetMomentCommentListRes struct {
	List  []GetMomentCommentListItem `json:"list"`
	Total int64                      `json:"total"`
}

type GetMomentDetailFileInfo struct {
	FileName string `json:"fileName"`
}

type GetMomentDetailReq struct {
	MomentId string `path:"momentId"`
}

type GetMomentDetailRes struct {
	MomentId  string                    `json:"momentId"`
	UserId    string                    `json:"userId"`
	Content   string                    `json:"content"`
	Files     []GetMomentDetailFileInfo `json:"files"`
	IsDeleted bool                      `json:"isDeleted"`
	CreatedAt string                    `json:"createdAt"`
	UpdatedAt string                    `json:"updatedAt"`
}

type GetMomentListFileInfo struct {
	FileName string `json:"fileName"`
}

type GetMomentListItem struct {
	MomentId  string                  `json:"momentId"`
	UserId    string                  `json:"userId"`
	Content   string                  `json:"content"`
	Files     []GetMomentListFileInfo `json:"files"`
	IsDeleted bool                    `json:"isDeleted"`
	CreatedAt string                  `json:"createdAt"`
	UpdatedAt string                  `json:"updatedAt"`
}

type GetMomentListReq struct {
	Page     int    `form:"page,optional"`
	Limit    int    `form:"limit,optional"`
	UserId   string `form:"userId,optional"`   // 用户ID筛选
	Keywords string `form:"keywords,optional"` // 内容关键词搜索
}

type GetMomentListRes struct {
	List  []GetMomentListItem `json:"list"`
	Total int64               `json:"total"`
}

type GetOpenAppListReq struct {
	Page           int    `form:"page,default=1"`
	PageSize       int    `form:"pageSize,default=10"`
	Keyword        string `form:"keyword,optional"`
	OwnerUserID    string `form:"ownerUserId,optional"`
	AppID          string `form:"appId,optional"`
	Status         int    `form:"status,optional"`         // 0全部 1草稿 2已发布 3禁用
	AuditStatus    int    `form:"auditStatus,optional"`    // 0全部 1待审核 2已通过 3已拒绝
	CapabilityType int    `form:"capabilityType,optional"` // 0全部 1Robot 2Webhook 3Robot或Webhook
}

type GetOpenAppListRes struct {
	Total int64         `json:"total"`
	List  []OpenAppInfo `json:"list"`
}

type GetOpenWebhookLogListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=20"`
	AppID     string `form:"appId,optional"`
	EventType string `form:"eventType,optional"`
	Status    int    `form:"status,optional"` // 0全部 1成功 2失败
}

type GetOpenWebhookLogListRes struct {
	Total int64                `json:"total"`
	List  []OpenWebhookLogInfo `json:"list"`
}

type GetOperationLogListReq struct {
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=20"`
	OperatorID string `form:"operatorId,optional"`
	Action     string `form:"action,optional"`
	Actions    string `form:"actions,optional"`
	TargetType string `form:"targetType,optional"`
	TargetID   string `form:"targetId,optional"`
	CaseID     uint64 `form:"caseId,optional"`
}

type GetOperationLogListRes struct {
	List  []OperationLogInfo `json:"list"`
	Total int64              `json:"total"`
}

type GetQiniuUploadTokenReq struct {
}

type GetQiniuUploadTokenRes struct {
	UploadToken string `json:"uploadToken"` // 上传token
	ExpiresIn   int64  `json:"expiresIn"`   // token过期时间 (秒)
}

type GetSensitiveWordListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
	IsActive bool   `form:"isActive,optional"`
}

type GetSensitiveWordListRes struct {
	List  []SensitiveWordInfo `json:"list"`
	Total int64               `json:"total"`
}

type GetUserDetailReq struct {
	UserID string `path:"id"`
}

type GetUserDetailRes struct {
	Id          string `json:"id"`
	NickName    string `json:"nickName"`
	FileName    string `json:"fileName"`
	Email       string `json:"email"`
	Abstract    string `json:"abstract"`
	Status      int    `json:"status"`
	Source      int    `json:"source"`
	LastLoginIP string `json:"lastLoginIp"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type GetUserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Email    string `form:"email,optional"`
	Keyword  string `form:"keyword,optional"` // 昵称/邮箱/手机号模糊搜索
	Status   int    `form:"status,optional"`
	Source   int    `form:"source,optional"`
}

type GetUserListRes struct {
	List  []UserInfo `json:"list"`
	Total int64      `json:"total"`
}

type GetUserOperationsProfileReq struct {
	UserID string `path:"userId"`
}

type GetUserOperationsProfileRes struct {
	Profile      UserOpsProfileInfo   `json:"profile"`
	FriendTotal  int64                `json:"friendTotal"`
	GroupTotal   int64                `json:"groupTotal"`
	SessionTotal int64                `json:"sessionTotal"`
	MomentTotal  int64                `json:"momentTotal"`
	ReportTotal  int64                `json:"reportTotal"`
	BlockTotal   int64                `json:"blockTotal"`
	Friends      []UserOpsFriendItem  `json:"friends"`
	Groups       []UserOpsGroupItem   `json:"groups"`
	Sessions     []UserOpsSessionItem `json:"sessions"`
	Moments      []UserOpsMomentItem  `json:"moments"`
	Reports      []UserOpsReportItem  `json:"reports"`
	Blocks       []UserOpsBlockItem   `json:"blocks"`
}

type GetVersionListItem struct {
	VersionID      uint   `json:"versionId"`      // 版本ID
	ArchitectureID uint   `json:"architectureId"` // 架构ID
	Version        string `json:"version"`        // 版本号
	FileKey        string `json:"fileKey"`        // 文件ID
	Description    string `json:"description"`    // 版本描述
	ReleaseNotes   string `json:"releaseNotes"`   // 更新日志
	ReleaseDate    string `json:"releaseDate"`    // 发布时间
	CreatedAt      string `json:"createdAt"`      // 创建时间
	UpdatedAt      string `json:"updatedAt"`      // 更新时间
}

type GetVersionListReq struct {
	ArchitectureID uint   `form:"architectureId"`    // 架构ID
	AppID          string `form:"appId,optional"`    // 应用ID
	Page           int    `form:"page,optional"`     // 页码
	PageSize       int    `form:"pageSize,optional"` // 每页数量
}

type GetVersionListRes struct {
	Total    int64                `json:"total"`    // 总数
	Versions []GetVersionListItem `json:"versions"` // 版本列表
}

type GroupOpsMemberItem struct {
	UserID   string `json:"userId"`
	NickName string `json:"nickName"`
	Role     int    `json:"role"`
	Status   int    `json:"status"`
	JoinTime string `json:"joinTime"`
}

type GroupOpsMessageItem struct {
	MessageID  string `json:"messageId"`
	SendUserID string `json:"sendUserId"`
	SendName   string `json:"sendName"`
	MsgPreview string `json:"msgPreview"`
	IsDeleted  bool   `json:"isDeleted"`
	CreateTime string `json:"createTime"`
}

type GroupOpsProfileInfo struct {
	GroupID   string `json:"groupId"`
	Title     string `json:"title"`
	Avatar    string `json:"avatar"`
	CreatorID string `json:"creatorId"`
	Notice    string `json:"notice"`
	Status    int    `json:"status"`
	MuteAll   bool   `json:"muteAll"`
	CreatedAt string `json:"createdAt"`
}

type GroupOpsReportItem struct {
	ID             uint64 `json:"id"`
	ReporterUserID string `json:"reporterUserId"`
	ReporterName   string `json:"reporterName"`
	ReasonType     int    `json:"reasonType"`
	Status         int    `json:"status"`
	CreatedAt      string `json:"createdAt"`
}

type HandleFeedbackReq struct {
	Id           uint   `path:"id"`
	Status       int    `json:"status"`       // 处理状态
	HandleResult string `json:"handleResult"` // 处理结果
	UserID       string `header:"Beaver-User-Id"`
}

type HandleFeedbackRes struct {
}

type HandleModerationCaseReq struct {
	CaseID       uint64                    `path:"id"`
	Status       int                       `json:"status"`
	HandleRemark string                    `json:"handleRemark,optional"`
	Actions      []ModerationControlAction `json:"actions,optional"`
	UserID       string                    `header:"Beaver-User-Id"`
}

type HandleModerationCaseRes struct {
}

type LoginReq struct {
	Phone    string `json:"phone"`    // string 管理员手机号
	Password string `json:"password"` // string 登录密码
}

type LoginRes struct {
	Token  string `json:"token"`  // string 访问 JWT
	UserID string `json:"userId"` // string 管理员用户 ID
}

type ModerationCaseInfo struct {
	ID           uint64 `json:"id"`
	CaseNo       string `json:"caseNo"`
	Source       int    `json:"source"`
	SourceID     uint64 `json:"sourceId"`
	TargetType   int    `json:"targetType"`
	TargetID     string `json:"targetId"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Priority     int    `json:"priority"`
	Status       int    `json:"status"`
	HandlerID    string `json:"handlerId"`
	HandleRemark string `json:"handleRemark"`
	HandleTime   string `json:"handleTime"`
	CreatedAt    string `json:"createdAt"`
}

type ModerationControlAction struct {
	Action string `json:"action"`
	Target string `json:"target,optional"`
	Reason string `json:"reason,optional"`
	Extra  string `json:"extra,optional"`
}

type MuteGroupMemberReq struct {
	Id              uint `path:"id"`
	ProhibitionTime int  `json:"prohibitionTime"` // 禁言时长(分钟)，0表示解除禁言
}

type MuteGroupMemberRes struct {
}

type OpenAppInfo struct {
	AppID         string `json:"appId"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Icon          string `json:"icon"`
	OwnerUserID   string `json:"ownerUserId"`
	OwnerUserName string `json:"ownerUserName"`
	AppType       int    `json:"appType"`
	Category      string `json:"category"`
	Status        int    `json:"status"`
	AuditStatus   int    `json:"auditStatus"`
	AuditedBy     string `json:"auditedBy"`
	AuditedAt     int64  `json:"auditedAt"`
	EnableRobot   int    `json:"enableRobot"`
	EnableOAuth   int    `json:"enableOAuth"`
	EnableWebhook int    `json:"enableWebhook"`
	CreatedAt     int64  `json:"createdAt"`
}

type OpenWebhookLogInfo struct {
	ID           uint64 `json:"id"`
	AppID        string `json:"appId"`
	EventID      string `json:"eventId"`
	EventType    string `json:"eventType"`
	TargetURL    string `json:"targetUrl"`
	HTTPStatus   int    `json:"httpStatus"`
	LatencyMs    int64  `json:"latencyMs"`
	RetryCount   int    `json:"retryCount"`
	Status       int    `json:"status"`
	ErrorMessage string `json:"errorMessage"`
	CreatedAt    int64  `json:"createdAt"`
}

type OperationLogInfo struct {
	ID           uint64 `json:"id"`
	OperatorID   string `json:"operatorId"`
	Action       string `json:"action"`
	TargetType   string `json:"targetType"`
	TargetID     string `json:"targetId"`
	CaseID       uint64 `json:"caseId"`
	Detail       string `json:"detail"`
	Result       string `json:"result"`
	ErrorMessage string `json:"errorMessage"`
	CreatedAt    string `json:"createdAt"`
}

type PreviewReq struct {
	FileName string `path:"fileName"`
}

type PreviewRes struct {
}

type QueryLogsItem struct {
	Id         uint   `json:"id"`         // 日志ID
	Level      string `json:"level"`      // 日志级别
	Data       string `json:"data"`       // 日志数据
	UserID     string `json:"userId"`     // 用户ID
	BucketID   string `json:"bucketId"`   // Bucket Id
	BucketName string `json:"bucketName"` // Bucket名称
	Timestamp  int64  `json:"timestamp"`  // 时间戳(毫秒)
	CreatedAt  string `json:"createdAt"`  // 创建时间
}

type QueryLogsReq struct {
	UserID     string `header:"Beaver-User-Id"`    // 用户ID
	BucketID   string `form:"bucketId"`            // Bucket Id
	Level      string `form:"level,optional"`      // 日志级别(可选)
	StartTime  int64  `form:"startTime"`           // 开始时间戳(毫秒)
	EndTime    int64  `form:"endTime"`             // 结束时间戳(毫秒)
	Keyword    string `form:"keyword,optional"`    // 关键词(可选)
	UserFilter string `form:"userFilter,optional"` // 用户ID筛选(可选)
	Page       int    `form:"page,default=1"`      // 页码
	PageSize   int    `form:"pageSize,default=20"` // 每页大小
}

type QueryLogsRes struct {
	Total int64           `json:"total"` // 总数
	Logs  []QueryLogsItem `json:"logs"`  // 日志条目
}

type RejectContentReportReq struct {
	ReportID     uint64 `json:"reportId"`
	HandleRemark string `json:"handleRemark,optional"`
	UserID       string `header:"Beaver-User-Id"`
}

type RejectContentReportRes struct {
}

type RemoveEmojiFromPackageReq struct {
	PackageId string `json:"packageId"`
	EmojiId   string `json:"emojiId"`
}

type RemoveEmojiFromPackageRes struct {
}

type RemoveGroupMemberReq struct {
	GroupId   string   `json:"groupId"`
	MemberIds []string `json:"memberIds"`
}

type RemoveGroupMemberRes struct {
}

type ResetUserPasswordReq struct {
	UserID      string `json:"userId"`
	NewPassword string `json:"newPassword"`
}

type ResetUserPasswordRes struct {
}

type RestoreChatMessageReq struct {
	MessageID string `json:"messageId"`
}

type RestoreChatMessageRes struct {
}

type RestoreFriendReq struct {
	FriendID string `json:"friendId"`
}

type RestoreFriendRes struct {
}

type SaveFileReq struct {
	OriginalName string `json:"originalName"` // 文件名
	Size         int64  `json:"size"`         // 文件大小
	Path         string `json:"path"`         // 文件在七牛云的路径
	Md5          string `json:"md5"`          // 文件MD5
	Type         string `json:"type"`         // 文件类型
	Source       string `json:"source"`       // 文件来源：qiniu 或 local
	FileInfo     string `json:"fileInfo"`     // 文件信息JSON
}

type SaveFileRes struct {
	FileKey string `json:"fileKey"`
}

type SearchConversationHit struct {
	ConversationID string `json:"conversationId"`
	Title          string `json:"title"`
	LastMessage    string `json:"lastMessage"`
}

type SearchGroupHit struct {
	GroupID string `json:"groupId"`
	Title   string `json:"title"`
	Status  int    `json:"status"`
}

type SearchMessageHit struct {
	MessageID      string `json:"messageId"`
	ConversationID string `json:"conversationId"`
	SendUserID     string `json:"sendUserId"`
	MsgPreview     string `json:"msgPreview"`
	CreateTime     string `json:"createTime"`
}

type SearchUserHit struct {
	UserID   string `json:"userId"`
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Status   int    `json:"status"`
}

type SensitiveWordInfo struct {
	ID        uint64 `json:"id"`
	Word      string `json:"word"`
	Category  string `json:"category"`
	Level     int    `json:"level"`
	IsActive  bool   `json:"isActive"`
	Remark    string `json:"remark"`
	CreatedAt string `json:"createdAt"`
}

type UnblockFriendUsersReq struct {
	Ids []string `json:"ids"`
}

type UnblockFriendUsersRes struct {
}

type UpdateAdminUserReq struct {
	UserID       string `path:"userId"`
	NickName     string `json:"nickName,optional"`
	Status       int8   `json:"status,optional"`
	Password     string `json:"password,optional"`
	AuthorityIds []uint `json:"authorityIds,optional"`
	OperatorID   string `header:"Beaver-User-Id"`
}

type UpdateAdminUserRes struct {
}

type UpdateArchitectureReq struct {
	Id          uint   `json:"id"`                   // 记录ID
	Description string `json:"description,optional"` // 描述
	IsActive    bool   `json:"isActive,optional"`    // 是否启用
}

type UpdateArchitectureRes struct {
}

type UpdateAuthorityMenuMenuItem struct {
	Id uint `json:"id"`
}

type UpdateAuthorityMenuReq struct {
	UserID string                        `header:"Beaver-User-Id"`
	Id     uint                          `json:"id"`
	Menus  []UpdateAuthorityMenuMenuItem `json:"menus"`
}

type UpdateAuthorityMenuRes struct {
}

type UpdateAuthorityReq struct {
	Id          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      int8   `json:"status"`
	Sort        int    `json:"sort"`
}

type UpdateAuthorityRes struct {
}

type UpdateBucketReq struct {
	UserID      string `header:"Beaver-User-Id"`     // 用户ID
	BucketId    string `json:"bucketId"`             // Bucket ID
	Name        string `json:"name,optional"`        // Bucket名称
	Description string `json:"description,optional"` // Bucket描述
	IsActive    *bool  `json:"isActive,optional"`    // 是否激活
}

type UpdateBucketRes struct {
}

type UpdateCityStrategyItem struct {
	ArchitectureID uint `json:"architectureId"` // 架构ID
	VersionID      uint `json:"versionId"`      // 版本ID
	ForceUpdate    bool `json:"forceUpdate"`    // 是否强制更新
	IsActive       bool `json:"isActive"`       // 是否启用
}

type UpdateCityStrategyReq struct {
	AppID      string                   `json:"appId"`               // 应用ID
	CityIDs    []string                 `json:"cityIds"`             // 城市ID数组
	Strategy   []UpdateCityStrategyItem `json:"strategy"`            // 城市策略配置
	UpdateType string                   `json:"updateType,optional"` // 更新类型：single(单个架构) | global(全局架构)
}

type UpdateCityStrategyRes struct {
}

type UpdateEmojiPackageReq struct {
	PackageId   string  `json:"packageId"`
	Title       *string `json:"title,optional"`
	CoverFile   *string `json:"coverFile,optional"`
	Description *string `json:"description,optional"`
	Type        *string `json:"type,optional"`
	Status      *int    `json:"status,optional"`
}

type UpdateEmojiPackageRes struct {
}

type UpdateEmojiReq struct {
	EmojiId string  `path:"emojiId"`
	FileKey *string `json:"fileKey,optional"`
	Title   *string `json:"title,optional"`
}

type UpdateEmojiRes struct {
}

type UpdateGroupReq struct {
	Id       uint   `path:"id"`
	Title    string `json:"title,optional"`
	FileName string `json:"fileName,optional"`
	Notice   string `json:"notice,optional"`
	Status   int    `json:"status,optional"`
	MuteAll  bool   `json:"muteAll,optional"`
	Category string `json:"category,optional"`
}

type UpdateGroupRes struct {
}

type UpdateMemberRoleReq struct {
	Id   uint `path:"id"`
	Role int  `json:"role"`
}

type UpdateMemberRoleRes struct {
}

type UpdateMenuReq struct {
	Id       uint   `json:"id"`
	ParentId uint   `json:"parentId"`
	Path     string `json:"path"`
	Name     string `json:"name"`
	Hidden   bool   `json:"hidden"`
	Sort     int    `json:"sort"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	UserID   string `header:"Beaver-User-Id"`
}

type UpdateMenuRes struct {
}

type UpdateOpenAppStatusReq struct {
	AppIDs []string `json:"appIds"`
	Action int      `json:"action"` // 3禁用 4启用
	UserID string   `header:"Beaver-User-Id"`
}

type UpdateOpenAppStatusRes struct {
}

type UpdateSensitiveWordReq struct {
	ID       uint64 `path:"id"`
	Word     string `json:"word,optional"`
	Category string `json:"category,optional"`
	Level    int    `json:"level,optional"`
	IsActive bool   `json:"isActive,optional"`
	Remark   string `json:"remark,optional"`
	UserID   string `header:"Beaver-User-Id"`
}

type UpdateSensitiveWordRes struct {
}

type UpdateUserReq struct {
	UserID   string  `path:"id"`
	NickName *string `json:"nickName,optional"`
	Email    *string `json:"email,optional"`
	FileName *string `json:"fileName,optional"`
	Abstract *string `json:"abstract,optional"`
	Status   *int    `json:"status,optional"`
}

type UpdateUserRes struct {
}

type UserInfo struct {
	Id          string `json:"id"`
	NickName    string `json:"nickName"`
	Email       string `json:"email"`
	Abstract    string `json:"abstract"`
	FileName    string `json:"fileName"`
	Status      int    `json:"status"`
	Source      int    `json:"source"`
	LastLoginIP string `json:"lastLoginIp"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type UserOpsBlockItem struct {
	ID              string `json:"id"`
	BlockedUserID   string `json:"blockedUserId"`
	BlockedUserName string `json:"blockedUserName"`
	CreateTime      string `json:"createTime"`
}

type UserOpsFriendItem struct {
	PeerUserID   string `json:"peerUserId"`
	PeerUserName string `json:"peerUserName"`
	CreateTime   string `json:"createTime"`
}

type UserOpsGroupItem struct {
	GroupID string `json:"groupId"`
	Title   string `json:"title"`
	Role    int    `json:"role"`
	Status  int    `json:"status"`
}

type UserOpsMomentItem struct {
	MomentID  string `json:"momentId"`
	Content   string `json:"content"`
	IsDeleted bool   `json:"isDeleted"`
	CreatedAt string `json:"createdAt"`
}

type UserOpsProfileInfo struct {
	UserID     string `json:"userId"`
	NickName   string `json:"nickName"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	Abstract   string `json:"abstract"`
	Status     int    `json:"status"`
	Source     int    `json:"source"`
	CreateTime string `json:"createTime"`
}

type UserOpsReportItem struct {
	ID         uint64 `json:"id"`
	TargetType int    `json:"targetType"`
	TargetID   string `json:"targetId"`
	ReasonType int    `json:"reasonType"`
	Status     int    `json:"status"`
	CreatedAt  string `json:"createdAt"`
}

type UserOpsSessionItem struct {
	ConversationID   string `json:"conversationId"`
	ConversationType int    `json:"conversationType"`
	Title            string `json:"title"`
	LastMessage      string `json:"lastMessage"`
	LastMessageTime  string `json:"lastMessageTime"`
	MessageCount     int64  `json:"messageCount"`
}
