// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddEmojiToPackageReq struct {
	PackageID string `json:"packageId"`
	FileKey   string `json:"fileKey"`
	Title     string `json:"title"`
	AuthorID  string `header:"Beaver-User-Id"`
}

type AddEmojiToPackageRes struct {
	Id string `json:"id"`
}

type CreateEmojiPackageReq struct {
	Title       string  `json:"title"`
	CoverFile   *string `json:"coverFile,optional"`
	UserID      string  `header:"Beaver-User-Id"`
	Description string  `json:"description"`
	Type        string  `json:"type"`
}

type CreateEmojiPackageRes struct {
	Id string `json:"id"`
}

type CreateEmojiReq struct {
	FileKey  string `json:"fileKey"`
	Title    string `json:"title"`
	AuthorID string `header:"Beaver-User-Id"`
}

type CreateEmojiRes struct {
	Id string `json:"id"`
}

type DeleteEmojiPackageReq struct {
	PackageID string `json:"packageId"`
}

type DeleteEmojiPackageRes struct {
}

type DeleteEmojiReq struct {
	EmojiID string `path:"id"`
}

type DeleteEmojiRes struct {
}

type GetEmojiCollectListItem struct {
	Id           string `json:"id"`
	UserID       string `json:"userId"`
	EmojiID      string `json:"emojiId"`
	EmojiTitle   string `json:"emojiTitle"`
	EmojiFileKey string `json:"emojiFileKey"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type GetEmojiCollectListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	UserID    string `form:"userId,optional"`  // 按用户ID筛选
	EmojiID   string `form:"emojiId,optional"` // 按表情图片ID筛选
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiCollectListRes struct {
	List  []GetEmojiCollectListItem `json:"list"`
	Total int64                     `json:"total"`
}

type GetEmojiListItem struct {
	Id         string `json:"id"`
	FileKey    string `json:"fileKey"`
	Title      string `json:"title"`
	AuthorID   string `json:"authorId"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type GetEmojiListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	AuthorID  string `form:"authorId,optional"` // 按创建者ID筛选
	Title     string `form:"title,optional"`    // 按表情图片名称搜索
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiListRes struct {
	List  []GetEmojiListItem `json:"list"`
	Total int64              `json:"total"`
}

type GetEmojiPackageEmojisItem struct {
	Id         string `json:"id"`
	FileKey    string `json:"fileKey"`
	Title      string `json:"title"`
	AuthorID   string `json:"authorId"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type GetEmojiPackageEmojisReq struct {
	PackageID string `form:"packageId"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=50"`
}

type GetEmojiPackageEmojisRes struct {
	List  []GetEmojiPackageEmojisItem `json:"list"`
	Total int64                       `json:"total"`
}

type GetEmojiPackageListItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	CoverFile   string `json:"coverFile"`
	UserID      string `json:"userId"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Status      int    `json:"status"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type GetEmojiPackageListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	UserID    string `form:"userId,optional"` // 按创建者ID筛选
	Type      string `form:"type,optional"`   // 按类型筛选
	Status    int    `form:"status,optional"` // 按状态筛选
	Title     string `form:"title,optional"`  // 按表情包集合名称搜索
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetEmojiPackageListRes struct {
	List  []GetEmojiPackageListItem `json:"list"`
	Total int64                     `json:"total"`
}

type RemoveEmojiFromPackageReq struct {
	PackageID string `json:"packageId"`
	EmojiID   string `json:"emojiId"`
}

type RemoveEmojiFromPackageRes struct {
}

type UpdateEmojiPackageReq struct {
	PackageID   string  `json:"packageId"`
	Title       *string `json:"title,optional"`
	CoverFile   *string `json:"coverFile,optional"`
	Description *string `json:"description,optional"`
	Type        *string `json:"type,optional"`
	Status      *int    `json:"status,optional"`
}

type UpdateEmojiPackageRes struct {
}

type UpdateEmojiReq struct {
	EmojiID string  `path:"id"`
	FileKey *string `json:"fileKey,optional"`
	Title   *string `json:"title,optional"`
}

type UpdateEmojiRes struct {
}
