// Code generated by goctl. DO NOT EDIT.
package types

type AddAppReq struct {
	Name        string `json:"name"`                 // 应用名称
	Description string `json:"description,optional"` // 应用描述
}

type AddAppRes struct {
	Id    uint   `json:"id"`    // 创建的应用ID
	AppID string `json:"appId"` // 系统生成的应用唯一标识
}

type AddArchitectureReq struct {
	AppID       string `json:"appId"`                // 应用ID
	PlatformID  uint   `json:"platformId"`           // 平台ID：1=Windows, 2=MacOS, 3=Android
	ArchID      uint   `json:"archId"`               // 架构ID：1=WinX64, 2=WinArm64, 3=MacIntel, 4=MacApple, 5=Android
	Description string `json:"description,optional"` // 描述
}

type AddArchitectureRes struct {
	Id uint `json:"id"` // 创建的记录ID
}

type AddVersionReq struct {
	ArchitectureID uint   `json:"architectureId"`        // 架构ID
	Version        string `json:"version"`               // 版本号
	FileKey        string `json:"fileKey"`               // 文件ID
	Description    string `json:"description,optional"`  // 版本描述
	ReleaseNotes   string `json:"releaseNotes,optional"` // 更新日志
}

type AddVersionRes struct {
	VersionID uint `json:"versionId"` // 创建的版本ID
}

type GetAppVersionsReq struct {
	AppID    string `form:"appId"`             // 应用ID
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
}

type GetAppVersionsRes struct {
	Total         int64                `json:"total"`         // 总架构数
	Architectures []GetAppVersionsItem `json:"architectures"` // 按架构分组的版本信息
}

type GetAppsReq struct {
	Page     int  `form:"page,optional"`     // 页码
	PageSize int  `form:"pageSize,optional"` // 每页数量
	IsActive bool `form:"isActive,optional"` // 是否仅显示活跃应用
}

type GetAppsRes struct {
	Total int64         `json:"total"` // 总数
	Apps  []GetAppsItem `json:"apps"`  // 应用列表
}

type GetArchitecturesReq struct {
	AppID    string `form:"appId,optional"`    // 应用ID
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
	IsActive bool   `form:"isActive,optional"` // 是否仅显示活跃架构
}

type GetArchitecturesRes struct {
	Total         int64                  `json:"total"`         // 总数
	Architectures []GetArchitecturesItem `json:"architectures"` // 架构列表
}

type GetCityStrategiesReq struct {
	AppID    string `form:"appId,optional"`    // 应用ID
	IsActive bool   `form:"isActive,optional"` // 是否仅查询活跃策略
	Page     int    `form:"page,optional"`     // 页码
	PageSize int    `form:"pageSize,optional"` // 每页数量
}

type GetCityStrategiesRes struct {
	Total      int64                   `json:"total"`      // 总数
	Strategies []GetCityStrategiesItem `json:"strategies"` // 策略列表
}

type GetVersionListReq struct {
	ArchitectureID uint   `form:"architectureId"`    // 架构ID
	AppID          string `form:"appId,optional"`    // 应用ID
	Page           int    `form:"page,optional"`     // 页码
	PageSize       int    `form:"pageSize,optional"` // 每页数量
}

type GetVersionListRes struct {
	Total    int64                `json:"total"`    // 总数
	Versions []GetVersionListItem `json:"versions"` // 版本列表
}

type UpdateArchitectureReq struct {
	Id          uint   `json:"id"`                   // 记录ID
	Description string `json:"description,optional"` // 描述
	IsActive    bool   `json:"isActive,optional"`    // 是否启用
}

type UpdateArchitectureRes struct {
}

type UpdateCityStrategyReq struct {
	AppID      string                   `json:"appId"`               // 应用ID
	CityIDs    []string                 `json:"cityIds"`             // 城市ID数组
	Strategy   []UpdateCityStrategyItem `json:"strategy"`            // 城市策略配置
	UpdateType string                   `json:"updateType,optional"` // 更新类型：single(单个架构) | global(全局架构)
}

type UpdateCityStrategyRes struct {
}
