// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: agent.proto

package pyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamAgentMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMessageId string                 `protobuf:"bytes,1,opt,name=user_message_id,json=userMessageId,proto3" json:"user_message_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`       // 业务模型ID；auto 表示由 agent 选模
	ModelJson     string                 `protobuf:"bytes,8,opt,name=model_json,json=modelJson,proto3" json:"model_json,omitempty"` // Go 解析后的调用配置 JSON（含 endpoint/apiKey 等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAgentMessageReq) Reset() {
	*x = StreamAgentMessageReq{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAgentMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentMessageReq) ProtoMessage() {}

func (x *StreamAgentMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentMessageReq.ProtoReflect.Descriptor instead.
func (*StreamAgentMessageReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAgentMessageReq) GetUserMessageId() string {
	if x != nil {
		return x.UserMessageId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamAgentMessageReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *StreamAgentMessageReq) GetModelJson() string {
	if x != nil {
		return x.ModelJson
	}
	return ""
}

type StreamAgentMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LlmMetaJson   string                 `protobuf:"bytes,4,opt,name=llm_meta_json,json=llmMetaJson,proto3" json:"llm_meta_json,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	DataJson      string                 `protobuf:"bytes,6,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAgentMessageEvent) Reset() {
	*x = StreamAgentMessageEvent{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAgentMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentMessageEvent) ProtoMessage() {}

func (x *StreamAgentMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentMessageEvent.ProtoReflect.Descriptor instead.
func (*StreamAgentMessageEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAgentMessageEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StreamAgentMessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamAgentMessageEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StreamAgentMessageEvent) GetLlmMetaJson() string {
	if x != nil {
		return x.LlmMetaJson
	}
	return ""
}

func (x *StreamAgentMessageEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamAgentMessageEvent) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xff\x01\n" +
	"\x15StreamAgentMessageReq\x12&\n" +
	"\x0fuser_message_id\x18\x01 \x01(\tR\ruserMessageId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_json\x18\b \x01(\tR\tmodelJson\"\xc3\x01\n" +
	"\x17StreamAgentMessageEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\"\n" +
	"\rllm_meta_json\x18\x04 \x01(\tR\vllmMetaJson\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_json\x18\x06 \x01(\tR\bdataJson2]\n" +
	"\x05Agent\x12T\n" +
	"\x12StreamAgentMessage\x12\x1c.agent.StreamAgentMessageReq\x1a\x1e.agent.StreamAgentMessageEvent0\x01B\x1aZ\x18beaver/app/agent/pyagentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_proto_goTypes = []any{
	(*StreamAgentMessageReq)(nil),   // 0: agent.StreamAgentMessageReq
	(*StreamAgentMessageEvent)(nil), // 1: agent.StreamAgentMessageEvent
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: agent.Agent.StreamAgentMessage:input_type -> agent.StreamAgentMessageReq
	1, // 1: agent.Agent.StreamAgentMessage:output_type -> agent.StreamAgentMessageEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
