/*
 * Copyright (c) 2024-2026 Beaver IM Team
 * SPDX-License-Identifier: MIT
 * Project: beaver-server
 * https://github.com/wsrh8888/beaver-server
 *
 * 中文：
 * 本文件为海狸 IM（Beaver IM）开源项目源代码。
 * 版权所有 © 2024-2026 Beaver IM Team，基于 MIT 协议授权。
 * 禁止删除、篡改或替换本文件头部版权与许可声明。
 * 使用与商业授权说明：https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * English:
 * This file is part of the Beaver IM open-source project.
 * Copyright (c) 2024-2026 Beaver IM Team. Licensed under the MIT License.
 * Do not remove, alter, or replace this copyright and license header.
 * Usage & commercial licensing: https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * beaver-server-header-v1
 */

// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: emoji_rpc.proto

package server

import (
	"context"

	"beaver/app/emoji/emoji_rpc/internal/logic"
	"beaver/app/emoji/emoji_rpc/internal/svc"
	"beaver/app/emoji/emoji_rpc/types/emoji_rpc"
)

type EmojiServer struct {
	svcCtx *svc.ServiceContext
	emoji_rpc.UnimplementedEmojiServer
}

func NewEmojiServer(svcCtx *svc.ServiceContext) *EmojiServer {
	return &EmojiServer{
		svcCtx: svcCtx,
	}
}

// ========== 用户收藏表情同步 ==========
func (s *EmojiServer) GetUserEmojiCollects(ctx context.Context, in *emoji_rpc.GetUserEmojiCollectsReq) (*emoji_rpc.GetUserEmojiCollectsRes, error) {
	l := logic.NewGetUserEmojiCollectsLogic(ctx, s.svcCtx)
	return l.GetUserEmojiCollects(in)
}

// ========== 用户收藏表情包同步 ==========
func (s *EmojiServer) GetUserEmojiPackageCollects(ctx context.Context, in *emoji_rpc.GetUserEmojiPackageCollectsReq) (*emoji_rpc.GetUserEmojiPackageCollectsRes, error) {
	l := logic.NewGetUserEmojiPackageCollectsLogic(ctx, s.svcCtx)
	return l.GetUserEmojiPackageCollects(in)
}

// ========== 表情包基础数据同步 ==========
func (s *EmojiServer) GetEmojiPackages(ctx context.Context, in *emoji_rpc.GetEmojiPackagesReq) (*emoji_rpc.GetEmojiPackagesRes, error) {
	l := logic.NewGetEmojiPackagesLogic(ctx, s.svcCtx)
	return l.GetEmojiPackages(in)
}

// ========== 表情包内容同步 ==========
func (s *EmojiServer) GetEmojiPackageContents(ctx context.Context, in *emoji_rpc.GetEmojiPackageContentsReq) (*emoji_rpc.GetEmojiPackageContentsRes, error) {
	l := logic.NewGetEmojiPackageContentsLogic(ctx, s.svcCtx)
	return l.GetEmojiPackageContents(in)
}

// ========== 表情基础数据同步 ==========
func (s *EmojiServer) GetEmojis(ctx context.Context, in *emoji_rpc.GetEmojisReq) (*emoji_rpc.GetEmojisRes, error) {
	l := logic.NewGetEmojisLogic(ctx, s.svcCtx)
	return l.GetEmojis(in)
}

// 管理类通用能力（admin / 其他服务均可复用，不与 HTTP 接口 1:1）
func (s *EmojiServer) ListEmojis(ctx context.Context, in *emoji_rpc.ListEmojisReq) (*emoji_rpc.ListEmojisRes, error) {
	l := logic.NewListEmojisLogic(ctx, s.svcCtx)
	return l.ListEmojis(in)
}

func (s *EmojiServer) SaveEmoji(ctx context.Context, in *emoji_rpc.SaveEmojiReq) (*emoji_rpc.SaveEmojiRes, error) {
	l := logic.NewSaveEmojiLogic(ctx, s.svcCtx)
	return l.SaveEmoji(in)
}

func (s *EmojiServer) ListEmojiPackages(ctx context.Context, in *emoji_rpc.ListEmojiPackagesReq) (*emoji_rpc.ListEmojiPackagesRes, error) {
	l := logic.NewListEmojiPackagesLogic(ctx, s.svcCtx)
	return l.ListEmojiPackages(in)
}

func (s *EmojiServer) SaveEmojiPackage(ctx context.Context, in *emoji_rpc.SaveEmojiPackageReq) (*emoji_rpc.SaveEmojiPackageRes, error) {
	l := logic.NewSaveEmojiPackageLogic(ctx, s.svcCtx)
	return l.SaveEmojiPackage(in)
}

func (s *EmojiServer) UpdateEmojiPackageContent(ctx context.Context, in *emoji_rpc.UpdateEmojiPackageContentReq) (*emoji_rpc.UpdateEmojiPackageContentRes, error) {
	l := logic.NewUpdateEmojiPackageContentLogic(ctx, s.svcCtx)
	return l.UpdateEmojiPackageContent(in)
}

func (s *EmojiServer) ListEmojiCollects(ctx context.Context, in *emoji_rpc.ListEmojiCollectsReq) (*emoji_rpc.ListEmojiCollectsRes, error) {
	l := logic.NewListEmojiCollectsLogic(ctx, s.svcCtx)
	return l.ListEmojiCollects(in)
}
