/*
 * Copyright (c) 2024-2026 Beaver IM Team
 * SPDX-License-Identifier: MIT
 * Project: beaver-server
 * https://github.com/wsrh8888/beaver-server
 *
 * 中文：
 * 本文件为海狸 IM（Beaver IM）开源项目源代码。
 * 版权所有 © 2024-2026 Beaver IM Team，基于 MIT 协议授权。
 * 禁止删除、篡改或替换本文件头部版权与许可声明。
 * 使用与商业授权说明：https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * English:
 * This file is part of the Beaver IM open-source project.
 * Copyright (c) 2024-2026 Beaver IM Team. Licensed under the MIT License.
 * Do not remove, alter, or replace this copyright and license header.
 * Usage & commercial licensing: https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * beaver-server-header-v1
 */

// Code generated by goctl. DO NOT EDIT.
package types

type CircleSyncItem struct {
	CircleID    string `json:"circleId"`    // 圈子ID
	Name        string `json:"name"`        // 圈子名称
	Avatar      string `json:"avatar"`      // 圈子头像
	MemberCount int64  `json:"memberCount"` // 成员数量
	Role        int8   `json:"role"`        // 当前用户角色：0=已退出 1=圈主 2=管理员 3=普通成员
	Version     int64  `json:"version"`     // 数据版本号
}

type CircleSyncReq struct {
	UserID  string `header:"Beaver-User-Id"` // 用户ID
	Version int64  `json:"version"`          // 本地版本号，服务端返回大于此版本的变更
}

type CircleSyncRes struct {
	List []CircleSyncItem `json:"list"` // 变更的圈子列表
}

type CreateCircleReq struct {
	UserID      string `header:"Beaver-User-Id"`     // 用户ID
	Name        string `json:"name"`                 // 圈子名称
	Description string `json:"description,optional"` // 圈子简介
	Avatar      string `json:"avatar,optional"`      // 圈子头像
	JoinType    int8   `json:"joinType,optional"`    // 加入方式：0=自由加入（默认） 1=审批加入
}

type CreateCircleRes struct {
	CircleID    string `json:"circleId"`    // 圈子ID
	Name        string `json:"name"`        // 圈子名称
	Description string `json:"description"` // 圈子简介
	Avatar      string `json:"avatar"`      // 圈子头像
	JoinType    int8   `json:"joinType"`    // 加入方式：0=自由加入 1=审批加入
	CreatorID   string `json:"creatorId"`   // 创建者用户ID
	CreatedAt   string `json:"createdAt"`   // 创建时间
}

type CreateCommentReq struct {
	UserID           string `header:"Beaver-User-Id"`          // 用户ID
	PostID           string `json:"postId"`                    // 帖子ID
	Content          string `json:"content"`                   // 评论内容
	ParentID         string `json:"parentId,optional"`         // 父评论ID，空表示一级评论
	ReplyToCommentID string `json:"replyToCommentId,optional"` // 被回复的评论ID
}

type CreateCommentRes struct {
	CommentID        string `json:"commentId"`        // 评论ID
	PostID           string `json:"postId"`           // 帖子ID
	UserID           string `json:"userId"`           // 评论用户ID
	UserName         string `json:"userName"`         // 评论用户昵称
	Avatar           string `json:"avatar"`           // 评论用户头像
	Content          string `json:"content"`          // 评论内容
	ParentID         string `json:"parentId"`         // 父评论ID
	ReplyToCommentID string `json:"replyToCommentId"` // 被回复的评论ID
	ReplyToUserName  string `json:"replyToUserName"`  // 被回复用户昵称
	CreatedAt        string `json:"createdAt"`        // 评论时间
}

type CreatePostFileInfo struct {
	FileKey string `json:"fileKey"` // 文件key
	Type    uint32 `json:"type"`    // 文件类型：2=图片 3=视频 4=文件
}

type CreatePostReq struct {
	UserID   string               `header:"Beaver-User-Id"` // 用户ID
	CircleID string               `json:"circleId"`         // 圈子ID
	Content  string               `json:"content"`          // 帖子内容
	Files    []CreatePostFileInfo `json:"files,optional"`   // 附件列表
}

type CreatePostRes struct {
	PostID    string `json:"postId"`    // 帖子ID
	CircleID  string `json:"circleId"`  // 圈子ID
	UserID    string `json:"userId"`    // 发帖用户ID
	UserName  string `json:"userName"`  // 发帖用户昵称
	Avatar    string `json:"avatar"`    // 发帖用户头像
	Content   string `json:"content"`   // 帖子内容
	CreatedAt string `json:"createdAt"` // 发布时间
}

type DeleteCircleReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	CircleID string `form:"circleId"`         // 圈子ID
}

type DeleteCircleRes struct {
}

type DeleteCommentReq struct {
	UserID    string `header:"Beaver-User-Id"` // 用户ID
	CommentID string `form:"commentId"`        // 评论ID
}

type DeleteCommentRes struct {
}

type DeletePostReq struct {
	UserID string `header:"Beaver-User-Id"` // 用户ID
	PostID string `form:"postId"`           // 帖子ID
}

type DeletePostRes struct {
}

type GetCircleDetailReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	CircleID string `form:"circleId"`         // 圈子ID
}

type GetCircleDetailRes struct {
	CircleID    string `json:"circleId"`            // 圈子ID
	Name        string `json:"name"`                // 圈子名称
	Description string `json:"description"`         // 圈子简介
	Avatar      string `json:"avatar"`              // 圈子头像
	JoinType    int8   `json:"joinType"`            // 加入方式：0=自由加入 1=审批加入
	CreatorID   string `json:"creatorId"`           // 创建者用户ID
	MemberCount int64  `json:"memberCount"`         // 成员数量
	PostCount   int64  `json:"postCount"`           // 帖子数量
	Role        int8   `json:"role"`                // 当前用户角色：0=未加入 1=圈主 2=管理员 3=普通成员
	CreatedAt   string `json:"createdAt"`           // 创建时间
	InviteUrl   string `json:"inviteUrl,optional"`  // 成员可见：稳定邀请链接
}

type GetCircleMembersItem struct {
	UserID   string `json:"userId"`   // 用户ID
	UserName string `json:"userName"` // 用户昵称
	Avatar   string `json:"avatar"`   // 用户头像
	Role     int8   `json:"role"`     // 角色：1=圈主 2=管理员 3=普通成员
}

type GetCircleMembersReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	CircleID string `form:"circleId"`         // 圈子ID
	Page     int    `form:"page"`             // 页码
	Limit    int    `form:"limit"`            // 每页数量
}

type GetCircleMembersRes struct {
	Count int64                  `json:"count"` // 总数
	List  []GetCircleMembersItem `json:"list"`  // 成员列表
}

type InviteCircleMembersReq struct {
	UserID   string   `header:"Beaver-User-Id"` // 用户ID（需为圈主或管理员）
	CircleID string   `json:"circleId"`         // 圈子ID
	UserIds  []string `json:"userIds"`          // 被邀请用户ID列表
}

type InviteCircleMembersRes struct {
}

type RemoveCircleMembersReq struct {
	UserID   string   `header:"Beaver-User-Id"` // 用户ID（需为圈主或管理员）
	CircleID string   `json:"circleId"`         // 圈子ID
	UserIds  []string `json:"userIds"`          // 被移除用户ID列表
}

type RemoveCircleMembersRes struct {
}

type GetCommentListItem struct {
	CommentID        string               `json:"commentId"`        // 评论ID
	UserID           string               `json:"userId"`           // 评论用户ID
	UserName         string               `json:"userName"`         // 评论用户昵称
	Avatar           string               `json:"avatar"`           // 评论用户头像
	Content          string               `json:"content"`          // 评论内容
	ParentID         string               `json:"parentId"`         // 父评论ID
	ReplyToCommentID string               `json:"replyToCommentId"` // 被回复的评论ID
	ReplyToUserName  string               `json:"replyToUserName"`  // 被回复用户昵称
	ChildCount       int64                `json:"childCount"`       // 子评论总数
	Children         []GetCommentListItem `json:"children"`         // 子评论
	CreatedAt        string               `json:"createdAt"`        // 评论时间
}

type GetCommentListReq struct {
	UserID   string `header:"Beaver-User-Id"`  // 用户ID
	PostID   string `form:"postId"`            // 帖子ID
	ParentID string `form:"parentId,optional"` // 父评论ID，查询其子回复
	Page     int    `form:"page"`              // 页码
	Limit    int    `form:"limit"`             // 每页数量
}

type GetCommentListRes struct {
	Count int64                `json:"count"` // 总数
	List  []GetCommentListItem `json:"list"`  // 评论列表
}

type GetJoinRequestListItem struct {
	RequestID string `json:"requestId"` // 申请记录ID
	UserID    string `json:"userId"`    // 申请用户ID
	UserName  string `json:"userName"`  // 申请用户昵称
	Avatar    string `json:"avatar"`    // 申请用户头像
	Reason    string `json:"reason"`    // 申请理由
	CreatedAt string `json:"createdAt"` // 申请时间
}

type GetJoinRequestListReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID（需为圈主或管理员）
	CircleID string `form:"circleId"`         // 圈子ID
	Page     int    `form:"page"`             // 页码
	Limit    int    `form:"limit"`            // 每页数量
}

type GetJoinRequestListRes struct {
	Count int64                    `json:"count"` // 总数
	List  []GetJoinRequestListItem `json:"list"`  // 申请列表
}

type GetMyCircleListReq struct {
	UserID string `header:"Beaver-User-Id"` // 用户ID
	Page   int    `form:"page"`             // 页码
	Limit  int    `form:"limit"`            // 每页数量
}

type GetMyCircleListRes struct {
	Count int64              `json:"count"` // 总数
	List  []MyCircleListItem `json:"list"`  // 圈子列表
}

type GetPostDetailCommentInfo struct {
	CommentID        string                     `json:"commentId"`        // 评论ID
	UserID           string                     `json:"userId"`           // 评论用户ID
	UserName         string                     `json:"userName"`         // 评论用户昵称
	Avatar           string                     `json:"avatar"`           // 评论用户头像
	Content          string                     `json:"content"`          // 评论内容
	ParentID         string                     `json:"parentId"`         // 父评论ID，空表示一级评论
	ReplyToCommentID string                     `json:"replyToCommentId"` // 被回复的评论ID
	ReplyToUserName  string                     `json:"replyToUserName"`  // 被回复用户昵称
	ChildCount       int64                      `json:"childCount"`       // 子评论总数
	Children         []GetPostDetailCommentInfo `json:"children"`         // 子评论（部分）
	CreatedAt        string                     `json:"createdAt"`        // 评论时间
}

type GetPostDetailLikeInfo struct {
	UserID   string `json:"userId"`   // 点赞用户ID
	UserName string `json:"userName"` // 点赞用户昵称
	Avatar   string `json:"avatar"`   // 点赞用户头像
}

type GetPostLikesReq struct {
	UserID string `header:"Beaver-User-Id"` // 用户ID
	PostID string `form:"postId"`           // 帖子ID
	Page   int    `form:"page"`             // 页码
	Limit  int    `form:"limit"`            // 每页数量
}

type GetPostLikesInfo struct {
	UserID    string `json:"userId"`    // 点赞用户ID
	UserName  string `json:"userName"`  // 点赞用户昵称
	Avatar    string `json:"avatar"`    // 点赞用户头像
	CreatedAt string `json:"createdAt"` // 点赞时间
}

type GetPostLikesRes struct {
	Count int64              `json:"count"` // 总数
	List  []GetPostLikesInfo `json:"list"`  // 点赞列表
}

type GetPostDetailFileInfo struct {
	FileKey string `json:"fileKey"` // 文件key
	Type    uint32 `json:"type"`    // 文件类型：2=图片 3=视频 4=文件
}

type GetPostDetailReq struct {
	UserID string `header:"Beaver-User-Id"` // 用户ID
	PostID string `form:"postId"`           // 帖子ID
}

type GetPostDetailRes struct {
	PostID       string                     `json:"postId"`       // 帖子ID
	CircleID     string                     `json:"circleId"`     // 圈子ID
	UserID       string                     `json:"userId"`       // 发帖用户ID
	UserName     string                     `json:"userName"`     // 发帖用户昵称
	Avatar       string                     `json:"avatar"`       // 发帖用户头像
	Content      string                     `json:"content"`      // 帖子内容
	Files        []GetPostDetailFileInfo    `json:"files"`        // 附件列表
	CommentCount int64                      `json:"commentCount"` // 评论总数
	LikeCount    int64                      `json:"likeCount"`    // 点赞总数
	IsLiked      bool                       `json:"isLiked"`      // 当前用户是否已点赞
	IsTop        bool                       `json:"isTop"`        // 是否置顶
	Comments     []GetPostDetailCommentInfo `json:"comments"`     // 最新20条评论
	Likes        []GetPostDetailLikeInfo    `json:"likes"`        // 点赞用户列表
	CreatedAt    string                     `json:"createdAt"`    // 发布时间
}

type GetPostListCommentInfo struct {
	CommentID string `json:"commentId"` // 评论ID
	UserID    string `json:"userId"`    // 评论用户ID
	UserName  string `json:"userName"`  // 评论用户昵称
	Content   string `json:"content"`   // 评论内容
	CreatedAt string `json:"createdAt"` // 评论时间
}

type GetPostListFileInfo struct {
	FileKey string `json:"fileKey"` // 文件key
	Type    uint32 `json:"type"`    // 文件类型：2=图片 3=视频 4=文件
}

type GetPostListReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	CircleID string `form:"circleId"`         // 圈子ID
	Page     int    `form:"page"`             // 页码
	Limit    int    `form:"limit"`            // 每页数量
}

type GetPostListRes struct {
	Count int64          `json:"count"` // 总数
	List  []PostListItem `json:"list"`  // 帖子列表
}

type HandleJoinRequestReq struct {
	UserID    string `header:"Beaver-User-Id"` // 用户ID（需为圈主或管理员）
	RequestID string `json:"requestId"`        // 申请记录ID
	Status    int8   `json:"status"`           // 处理结果：1=通过 2=拒绝
}

type HandleJoinRequestRes struct {
}

type JoinCircleReq struct {
	UserID     string `header:"Beaver-User-Id"`     // 用户ID
	CircleID   string `json:"circleId,optional"`    // 圈子ID（有 inviteCode 时可空）
	Reason     string `json:"reason,optional"`      // 申请理由（审批加入时填写）
	InviteCode string `json:"inviteCode,optional"`  // 邀请短码
}

type JoinCircleRes struct {
	Status   int8   `json:"status"`             // 加入结果：1=已加入 0=申请待审批
	CircleID string `json:"circleId,optional"`  // 圈子ID
}

type LikePostReq struct {
	UserID string `header:"Beaver-User-Id"` // 用户ID
	PostID string `json:"postId"`           // 帖子ID
	Status bool   `json:"status"`           // 点赞状态：true=点赞 false=取消点赞
}

type LikePostRes struct {
}

type MyCircleListItem struct {
	CircleID    string `json:"circleId"`    // 圈子ID
	Name        string `json:"name"`        // 圈子名称
	Avatar      string `json:"avatar"`      // 圈子头像
	MemberCount int64  `json:"memberCount"` // 成员数量
	PostCount   int64  `json:"postCount"`   // 帖子数量
	Role        int8   `json:"role"`        // 当前用户角色：1=圈主 2=管理员 3=普通成员
}

type PostListItem struct {
	PostID       string                   `json:"postId"`       // 帖子ID
	CircleID     string                   `json:"circleId"`     // 圈子ID
	UserID       string                   `json:"userId"`       // 发帖用户ID
	UserName     string                   `json:"userName"`     // 发帖用户昵称
	Avatar       string                   `json:"avatar"`       // 发帖用户头像
	Content      string                   `json:"content"`      // 帖子内容
	Files        []GetPostListFileInfo    `json:"files"`        // 附件列表
	CommentCount int64                    `json:"commentCount"` // 评论总数
	LikeCount    int64                    `json:"likeCount"`    // 点赞总数
	IsLiked      bool                     `json:"isLiked"`      // 当前用户是否已点赞
	IsTop        bool                     `json:"isTop"`        // 是否置顶
	Comments     []GetPostListCommentInfo `json:"comments"`     // 最新3条评论
	CreatedAt    string                   `json:"createdAt"`    // 发布时间
}

type QuitCircleReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	CircleID string `json:"circleId"`         // 圈子ID
}

type QuitCircleRes struct {
}

type SearchCircleItem struct {
	CircleID    string `json:"circleId"`    // 圈子ID
	Name        string `json:"name"`        // 圈子名称
	Description string `json:"description"` // 圈子简介
	Avatar      string `json:"avatar"`      // 圈子头像
	MemberCount int64  `json:"memberCount"` // 成员数量
	JoinType    int8   `json:"joinType"`    // 加入方式：0=自由加入 1=审批加入
	Role        int8   `json:"role"`        // 当前用户角色：0=未加入 1=圈主 2=管理员 3=普通成员
}

type SearchCircleReq struct {
	UserID   string `header:"Beaver-User-Id"` // 用户ID
	Keywords string `form:"keywords"`         // 搜索关键词
	Page     int    `form:"page"`             // 页码
	Limit    int    `form:"limit"`            // 每页数量
}

type SearchCircleRes struct {
	Count int64              `json:"count"` // 总数
	List  []SearchCircleItem `json:"list"`  // 圈子列表
}

type UpdateCircleReq struct {
	UserID      string `header:"Beaver-User-Id"`     // 用户ID
	CircleID    string `json:"circleId"`             // 圈子ID
	Name        string `json:"name,optional"`        // 圈子名称
	Description string `json:"description,optional"` // 圈子简介
	Avatar      string `json:"avatar,optional"`      // 圈子头像
	JoinType    int8   `json:"joinType,optional"`    // 加入方式：0=自由加入 1=审批加入
}

type UpdateCircleRes struct {
}

type ResolveCircleInviteReq struct {
	UserID string `header:"Beaver-User-Id"` // 当前用户
	Code   string `form:"code"`             // 邀请短码
}

type ResolveCircleInviteRes struct {
	Code          string `json:"code"`          // 邀请短码
	CircleID      string `json:"circleId"`      // 圈子ID
	Name          string `json:"name"`          // 圈子名称
	Avatar        string `json:"avatar"`        // 头像
	Description   string `json:"description"`   // 简介
	MemberCount   int64  `json:"memberCount"`   // 成员数
	JoinType      int8   `json:"joinType"`      // 加入方式
	Valid         bool   `json:"valid"`         // 是否有效
	AlreadyJoined bool   `json:"alreadyJoined"` // 是否已加入
}

