/*
 * Copyright (c) 2024-2026 Beaver IM Team
 * SPDX-License-Identifier: MIT
 * Project: beaver-server
 * https://github.com/wsrh8888/beaver-server
 *
 * 中文：
 * 本文件为海狸 IM（Beaver IM）开源项目源代码。
 * 版权所有 © 2024-2026 Beaver IM Team，基于 MIT 协议授权。
 * 禁止删除、篡改或替换本文件头部版权与许可声明。
 * 使用与商业授权说明：https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * English:
 * This file is part of the Beaver IM open-source project.
 * Copyright (c) 2024-2026 Beaver IM Team. Licensed under the MIT License.
 * Do not remove, alter, or replace this copyright and license header.
 * Usage & commercial licensing: https://wsrh8888.github.io/beaver-docs/community/license.html
 *
 * beaver-server-header-v1
 */

// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: circle_rpc.proto

package server

import (
	"context"

	"beaver/app/circle/circle_rpc/internal/logic"
	"beaver/app/circle/circle_rpc/internal/svc"
	"beaver/app/circle/circle_rpc/types/circle_rpc"
)

type CircleServer struct {
	svcCtx *svc.ServiceContext
	circle_rpc.UnimplementedCircleServer
}

func NewCircleServer(svcCtx *svc.ServiceContext) *CircleServer {
	return &CircleServer{
		svcCtx: svcCtx,
	}
}

// 获取圈子列表（支持按用户、关键词、ID过滤）
func (s *CircleServer) GetCircleList(ctx context.Context, in *circle_rpc.GetCircleListReq) (*circle_rpc.GetCircleListRes, error) {
	l := logic.NewGetCircleListLogic(ctx, s.svcCtx)
	return l.GetCircleList(in)
}

// 更新圈子状态（解散等）
func (s *CircleServer) UpdateCircle(ctx context.Context, in *circle_rpc.UpdateCircleReq) (*circle_rpc.UpdateCircleRes, error) {
	l := logic.NewUpdateCircleLogic(ctx, s.svcCtx)
	return l.UpdateCircle(in)
}

// 获取圈子成员列表
func (s *CircleServer) GetCircleMembers(ctx context.Context, in *circle_rpc.GetCircleMembersReq) (*circle_rpc.GetCircleMembersRes, error) {
	l := logic.NewGetCircleMembersLogic(ctx, s.svcCtx)
	return l.GetCircleMembers(in)
}

// 获取用户在圈子中的角色
func (s *CircleServer) GetUserCircleRole(ctx context.Context, in *circle_rpc.GetUserCircleRoleReq) (*circle_rpc.GetUserCircleRoleRes, error) {
	l := logic.NewGetUserCircleRoleLogic(ctx, s.svcCtx)
	return l.GetUserCircleRole(in)
}

// 获取用户加入的所有圈子ID
func (s *CircleServer) GetUserCircleIDs(ctx context.Context, in *circle_rpc.GetUserCircleIDsReq) (*circle_rpc.GetUserCircleIDsRes, error) {
	l := logic.NewGetUserCircleIDsLogic(ctx, s.svcCtx)
	return l.GetUserCircleIDs(in)
}

// 获取圈子版本变更（数据同步）
func (s *CircleServer) GetCircleVersions(ctx context.Context, in *circle_rpc.GetCircleVersionsReq) (*circle_rpc.GetCircleVersionsRes, error) {
	l := logic.NewGetCircleVersionsLogic(ctx, s.svcCtx)
	return l.GetCircleVersions(in)
}

// 获取圈子帖子列表（管理后台）
func (s *CircleServer) ListPosts(ctx context.Context, in *circle_rpc.ListPostsReq) (*circle_rpc.ListPostsRes, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

// 删除帖子（管理后台）
func (s *CircleServer) DeletePost(ctx context.Context, in *circle_rpc.DeletePostReq) (*circle_rpc.DeletePostRes, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 获取帖子评论列表（管理后台）
func (s *CircleServer) ListComments(ctx context.Context, in *circle_rpc.ListCommentsReq) (*circle_rpc.ListCommentsRes, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

// 删除评论（管理后台）
func (s *CircleServer) DeleteComment(ctx context.Context, in *circle_rpc.DeleteCommentReq) (*circle_rpc.DeleteCommentRes, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

// 移除圈子成员（管理后台）
func (s *CircleServer) RemoveCircleMembers(ctx context.Context, in *circle_rpc.RemoveCircleMembersReq) (*circle_rpc.RemoveCircleMembersRes, error) {
	l := logic.NewRemoveCircleMembersLogic(ctx, s.svcCtx)
	return l.RemoveCircleMembers(in)
}
