// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: datasync_rpc.proto

package server

import (
	"context"

	"beaver/app/datasync/datasync_rpc/internal/logic"
	"beaver/app/datasync/datasync_rpc/internal/svc"
	"beaver/app/datasync/datasync_rpc/types/types/datasync_rpc"
)

type DatasyncServer struct {
	svcCtx *svc.ServiceContext
	datasync_rpc.UnimplementedDatasyncServer
}

func NewDatasyncServer(svcCtx *svc.ServiceContext) *DatasyncServer {
	return &DatasyncServer{
		svcCtx: svcCtx,
	}
}

// 获取同步游标
func (s *DatasyncServer) GetSyncCursor(ctx context.Context, in *datasync_rpc.GetSyncCursorReq) (*datasync_rpc.GetSyncCursorRes, error) {
	l := logic.NewGetSyncCursorLogic(ctx, s.svcCtx)
	return l.GetSyncCursor(in)
}
