// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: emoji_rpc.proto

package emoji_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Emoji_GetUserEmojiSync_FullMethodName = "/emoji_rpc.emoji/GetUserEmojiSync"
)

// EmojiClient is the client API for Emoji service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmojiClient interface {
	// 用户表情数据同步接口（为微服务架构设计）
	GetUserEmojiSync(ctx context.Context, in *GetUserEmojiSyncReq, opts ...grpc.CallOption) (*GetUserEmojiSyncRes, error)
}

type emojiClient struct {
	cc grpc.ClientConnInterface
}

func NewEmojiClient(cc grpc.ClientConnInterface) EmojiClient {
	return &emojiClient{cc}
}

func (c *emojiClient) GetUserEmojiSync(ctx context.Context, in *GetUserEmojiSyncReq, opts ...grpc.CallOption) (*GetUserEmojiSyncRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEmojiSyncRes)
	err := c.cc.Invoke(ctx, Emoji_GetUserEmojiSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmojiServer is the server API for Emoji service.
// All implementations must embed UnimplementedEmojiServer
// for forward compatibility.
type EmojiServer interface {
	// 用户表情数据同步接口（为微服务架构设计）
	GetUserEmojiSync(context.Context, *GetUserEmojiSyncReq) (*GetUserEmojiSyncRes, error)
	mustEmbedUnimplementedEmojiServer()
}

// UnimplementedEmojiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmojiServer struct{}

func (UnimplementedEmojiServer) GetUserEmojiSync(context.Context, *GetUserEmojiSyncReq) (*GetUserEmojiSyncRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEmojiSync not implemented")
}
func (UnimplementedEmojiServer) mustEmbedUnimplementedEmojiServer() {}
func (UnimplementedEmojiServer) testEmbeddedByValue()               {}

// UnsafeEmojiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmojiServer will
// result in compilation errors.
type UnsafeEmojiServer interface {
	mustEmbedUnimplementedEmojiServer()
}

func RegisterEmojiServer(s grpc.ServiceRegistrar, srv EmojiServer) {
	// If the following call pancis, it indicates UnimplementedEmojiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Emoji_ServiceDesc, srv)
}

func _Emoji_GetUserEmojiSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEmojiSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmojiServer).GetUserEmojiSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emoji_GetUserEmojiSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmojiServer).GetUserEmojiSync(ctx, req.(*GetUserEmojiSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Emoji_ServiceDesc is the grpc.ServiceDesc for Emoji service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Emoji_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emoji_rpc.emoji",
	HandlerType: (*EmojiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserEmojiSync",
			Handler:    _Emoji_GetUserEmojiSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emoji_rpc.proto",
}
