// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: dictionary_rpc.proto

package dictionary_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 城市信息
type CityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId   string `protobuf:"bytes,1,opt,name=cityId,proto3" json:"cityId,omitempty"`     // 城市代码
	CityName string `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"` // 城市名称
}

func (x *CityInfo) Reset() {
	*x = CityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityInfo) ProtoMessage() {}

func (x *CityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityInfo.ProtoReflect.Descriptor instead.
func (*CityInfo) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *CityInfo) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CityInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

// 获取城市列表请求
type GetCitiesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCitiesReq) Reset() {
	*x = GetCitiesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesReq) ProtoMessage() {}

func (x *GetCitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesReq.ProtoReflect.Descriptor instead.
func (*GetCitiesReq) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{1}
}

// 获取城市列表响应
type GetCitiesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []*CityInfo `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"` // 城市列表
}

func (x *GetCitiesRes) Reset() {
	*x = GetCitiesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesRes) ProtoMessage() {}

func (x *GetCitiesRes) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesRes.ProtoReflect.Descriptor instead.
func (*GetCitiesRes) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetCitiesRes) GetCities() []*CityInfo {
	if x != nil {
		return x.Cities
	}
	return nil
}

// 平台信息
type PlatformInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformId   uint32 `protobuf:"varint,1,opt,name=platformId,proto3" json:"platformId,omitempty"`    // 平台ID
	PlatformName string `protobuf:"bytes,2,opt,name=platformName,proto3" json:"platformName,omitempty"` // 平台名称
	Description  string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`   // 平台描述
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PlatformInfo) GetPlatformId() uint32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *PlatformInfo) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *PlatformInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 架构信息
type ArchitectureInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchId      uint32 `protobuf:"varint,1,opt,name=archId,proto3" json:"archId,omitempty"`          // 架构ID
	ArchName    string `protobuf:"bytes,2,opt,name=archName,proto3" json:"archName,omitempty"`       // 架构名称
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 架构描述
	PlatformId  uint32 `protobuf:"varint,4,opt,name=platformId,proto3" json:"platformId,omitempty"`  // 所属平台ID
}

func (x *ArchitectureInfo) Reset() {
	*x = ArchitectureInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchitectureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchitectureInfo) ProtoMessage() {}

func (x *ArchitectureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchitectureInfo.ProtoReflect.Descriptor instead.
func (*ArchitectureInfo) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ArchitectureInfo) GetArchId() uint32 {
	if x != nil {
		return x.ArchId
	}
	return 0
}

func (x *ArchitectureInfo) GetArchName() string {
	if x != nil {
		return x.ArchName
	}
	return ""
}

func (x *ArchitectureInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArchitectureInfo) GetPlatformId() uint32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

// 获取平台列表请求
type GetPlatformsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlatformsReq) Reset() {
	*x = GetPlatformsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlatformsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformsReq) ProtoMessage() {}

func (x *GetPlatformsReq) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformsReq.ProtoReflect.Descriptor instead.
func (*GetPlatformsReq) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{5}
}

// 获取平台列表响应
type GetPlatformsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platforms []*PlatformInfo `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"` // 平台列表
}

func (x *GetPlatformsRes) Reset() {
	*x = GetPlatformsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlatformsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformsRes) ProtoMessage() {}

func (x *GetPlatformsRes) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformsRes.ProtoReflect.Descriptor instead.
func (*GetPlatformsRes) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlatformsRes) GetPlatforms() []*PlatformInfo {
	if x != nil {
		return x.Platforms
	}
	return nil
}

// 获取架构列表请求
type GetArchitecturesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformId uint32 `protobuf:"varint,1,opt,name=platformId,proto3" json:"platformId,omitempty"` // 平台ID，可选，不传则返回所有架构
}

func (x *GetArchitecturesReq) Reset() {
	*x = GetArchitecturesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchitecturesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchitecturesReq) ProtoMessage() {}

func (x *GetArchitecturesReq) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchitecturesReq.ProtoReflect.Descriptor instead.
func (*GetArchitecturesReq) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetArchitecturesReq) GetPlatformId() uint32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

// 获取架构列表响应
type GetArchitecturesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Architectures []*ArchitectureInfo `protobuf:"bytes,1,rep,name=architectures,proto3" json:"architectures,omitempty"` // 架构列表
}

func (x *GetArchitecturesRes) Reset() {
	*x = GetArchitecturesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArchitecturesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchitecturesRes) ProtoMessage() {}

func (x *GetArchitecturesRes) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchitecturesRes.ProtoReflect.Descriptor instead.
func (*GetArchitecturesRes) Descriptor() ([]byte, []int) {
	return file_dictionary_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *GetArchitecturesRes) GetArchitectures() []*ArchitectureInfo {
	if x != nil {
		return x.Architectures
	}
	return nil
}

var File_dictionary_rpc_proto protoreflect.FileDescriptor

var file_dictionary_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x3e, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x88,
	0x01, 0x0a, 0x10, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x72, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x72, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x22, 0x4d, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x3a, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x22, 0x35, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x64, 0x22, 0x5d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x0d, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x32, 0x85, 0x02, 0x0a, 0x0a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x47, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x1f, 0x2e, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x12, 0x5c, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12,
	0x23, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dictionary_rpc_proto_rawDescOnce sync.Once
	file_dictionary_rpc_proto_rawDescData = file_dictionary_rpc_proto_rawDesc
)

func file_dictionary_rpc_proto_rawDescGZIP() []byte {
	file_dictionary_rpc_proto_rawDescOnce.Do(func() {
		file_dictionary_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionary_rpc_proto_rawDescData)
	})
	return file_dictionary_rpc_proto_rawDescData
}

var file_dictionary_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dictionary_rpc_proto_goTypes = []interface{}{
	(*CityInfo)(nil),            // 0: dictionary_rpc.CityInfo
	(*GetCitiesReq)(nil),        // 1: dictionary_rpc.GetCitiesReq
	(*GetCitiesRes)(nil),        // 2: dictionary_rpc.GetCitiesRes
	(*PlatformInfo)(nil),        // 3: dictionary_rpc.PlatformInfo
	(*ArchitectureInfo)(nil),    // 4: dictionary_rpc.ArchitectureInfo
	(*GetPlatformsReq)(nil),     // 5: dictionary_rpc.GetPlatformsReq
	(*GetPlatformsRes)(nil),     // 6: dictionary_rpc.GetPlatformsRes
	(*GetArchitecturesReq)(nil), // 7: dictionary_rpc.GetArchitecturesReq
	(*GetArchitecturesRes)(nil), // 8: dictionary_rpc.GetArchitecturesRes
}
var file_dictionary_rpc_proto_depIdxs = []int32{
	0, // 0: dictionary_rpc.GetCitiesRes.cities:type_name -> dictionary_rpc.CityInfo
	3, // 1: dictionary_rpc.GetPlatformsRes.platforms:type_name -> dictionary_rpc.PlatformInfo
	4, // 2: dictionary_rpc.GetArchitecturesRes.architectures:type_name -> dictionary_rpc.ArchitectureInfo
	1, // 3: dictionary_rpc.dictionary.GetCities:input_type -> dictionary_rpc.GetCitiesReq
	5, // 4: dictionary_rpc.dictionary.GetPlatforms:input_type -> dictionary_rpc.GetPlatformsReq
	7, // 5: dictionary_rpc.dictionary.GetArchitectures:input_type -> dictionary_rpc.GetArchitecturesReq
	2, // 6: dictionary_rpc.dictionary.GetCities:output_type -> dictionary_rpc.GetCitiesRes
	6, // 7: dictionary_rpc.dictionary.GetPlatforms:output_type -> dictionary_rpc.GetPlatformsRes
	8, // 8: dictionary_rpc.dictionary.GetArchitectures:output_type -> dictionary_rpc.GetArchitecturesRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dictionary_rpc_proto_init() }
func file_dictionary_rpc_proto_init() {
	if File_dictionary_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionary_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchitectureInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlatformsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlatformsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchitecturesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArchitecturesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionary_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictionary_rpc_proto_goTypes,
		DependencyIndexes: file_dictionary_rpc_proto_depIdxs,
		MessageInfos:      file_dictionary_rpc_proto_msgTypes,
	}.Build()
	File_dictionary_rpc_proto = out.File
	file_dictionary_rpc_proto_rawDesc = nil
	file_dictionary_rpc_proto_goTypes = nil
	file_dictionary_rpc_proto_depIdxs = nil
}
