// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: open_rpc.proto

package open_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用授权码换取 Token 请求
type ExchangeTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // 应用 ID
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                // 授权码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenReq) Reset() {
	*x = ExchangeTokenReq{}
	mi := &file_open_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenReq) ProtoMessage() {}

func (x *ExchangeTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenReq.ProtoReflect.Descriptor instead.
func (*ExchangeTokenReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeTokenReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ExchangeTokenReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ExchangeTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // 访问令牌
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`         // 过期时间（秒）
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`          // Token 类型（Bearer）
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenRes) Reset() {
	*x = ExchangeTokenRes{}
	mi := &file_open_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenRes) ProtoMessage() {}

func (x *ExchangeTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenRes.ProtoReflect.Descriptor instead.
func (*ExchangeTokenRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeTokenRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeTokenRes) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeTokenRes) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeTokenRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取用户信息请求
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 访问令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_open_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetUserInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户 ID
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` // 昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                     // 头像 URL
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                       // 手机号
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                       // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRes) Reset() {
	*x = GetUserInfoRes{}
	mi := &file_open_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRes) ProtoMessage() {}

func (x *GetUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRes.ProtoReflect.Descriptor instead.
func (*GetUserInfoRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoRes) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetUserInfoRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoRes) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 验证 Token 请求
type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 访问令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_open_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                // 是否有效
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID（如果有效）
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`    // 应用 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRes) Reset() {
	*x = ValidateTokenRes{}
	mi := &file_open_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRes) ProtoMessage() {}

func (x *ValidateTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRes.ProtoReflect.Descriptor instead.
func (*ValidateTokenRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenRes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenRes) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 刷新 Token 请求
type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                      // 应用 ID
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 刷新令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_open_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // 新的访问令牌
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // 新的刷新令牌
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`         // 过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRes) Reset() {
	*x = RefreshTokenRes{}
	mi := &file_open_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRes) ProtoMessage() {}

func (x *RefreshTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRes.ProtoReflect.Descriptor instead.
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRes) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 创建推送机器人
type CreateBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 目标群组 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotReq) Reset() {
	*x = CreateBotReq{}
	mi := &file_open_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotReq) ProtoMessage() {}

func (x *CreateBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotReq.ProtoReflect.Descriptor instead.
func (*CreateBotReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBotReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type CreateBotRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 机器人 ID（open_bots.id）
	BotUserId     string                 `protobuf:"bytes,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`  // 机器人用户 ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // Webhook Token
	WebhookUrl    string                 `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"` // Webhook 基础 URL（不含 token）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotRes) Reset() {
	*x = CreateBotRes{}
	mi := &file_open_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotRes) ProtoMessage() {}

func (x *CreateBotRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotRes.ProtoReflect.Descriptor instead.
func (*CreateBotRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBotRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateBotRes) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

func (x *CreateBotRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateBotRes) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

// 删除推送机器人（软删除，设置 status=0）
type DeleteBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // open_bots.id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotReq) Reset() {
	*x = DeleteBotReq{}
	mi := &file_open_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotReq) ProtoMessage() {}

func (x *DeleteBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotReq.ProtoReflect.Descriptor instead.
func (*DeleteBotReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBotReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBotRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotRes) Reset() {
	*x = DeleteBotRes{}
	mi := &file_open_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotRes) ProtoMessage() {}

func (x *DeleteBotRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotRes.ProtoReflect.Descriptor instead.
func (*DeleteBotRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{11}
}

// 重置签名密钥
type ResetBotSecretReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBotSecretReq) Reset() {
	*x = ResetBotSecretReq{}
	mi := &file_open_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBotSecretReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBotSecretReq) ProtoMessage() {}

func (x *ResetBotSecretReq) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBotSecretReq.ProtoReflect.Descriptor instead.
func (*ResetBotSecretReq) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *ResetBotSecretReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResetBotSecretRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SignatureSecret string                 `protobuf:"bytes,1,opt,name=signature_secret,json=signatureSecret,proto3" json:"signature_secret,omitempty"` // 新密钥
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetBotSecretRes) Reset() {
	*x = ResetBotSecretRes{}
	mi := &file_open_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBotSecretRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBotSecretRes) ProtoMessage() {}

func (x *ResetBotSecretRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBotSecretRes.ProtoReflect.Descriptor instead.
func (*ResetBotSecretRes) Descriptor() ([]byte, []int) {
	return file_open_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ResetBotSecretRes) GetSignatureSecret() string {
	if x != nil {
		return x.SignatureSecret
	}
	return ""
}

var File_open_rpc_proto protoreflect.FileDescriptor

const file_open_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0eopen_rpc.proto\x12\bopen_rpc\"=\n" +
	"\x10ExchangeTokenReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xb1\x01\n" +
	"\x10ExchangeTokenRes\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"3\n" +
	"\x0eGetUserInfoReq\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x8a\x01\n" +
	"\x0eGetUserInfoRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"5\n" +
	"\x10ValidateTokenReq\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"X\n" +
	"\x10ValidateTokenRes\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\"M\n" +
	"\x0fRefreshTokenReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"x\n" +
	"\x0fRefreshTokenRes\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\")\n" +
	"\fCreateBotReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"u\n" +
	"\fCreateBotRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\vbot_user_id\x18\x02 \x01(\tR\tbotUserId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1f\n" +
	"\vwebhook_url\x18\x04 \x01(\tR\n" +
	"webhookUrl\"\x1e\n" +
	"\fDeleteBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x0e\n" +
	"\fDeleteBotRes\"#\n" +
	"\x11ResetBotSecretReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\">\n" +
	"\x11ResetBotSecretRes\x12)\n" +
	"\x10signature_secret\x18\x01 \x01(\tR\x0fsignatureSecret2\xe7\x03\n" +
	"\x04open\x12G\n" +
	"\rExchangeToken\x12\x1a.open_rpc.ExchangeTokenReq\x1a\x1a.open_rpc.ExchangeTokenRes\x12A\n" +
	"\vGetUserInfo\x12\x18.open_rpc.GetUserInfoReq\x1a\x18.open_rpc.GetUserInfoRes\x12G\n" +
	"\rValidateToken\x12\x1a.open_rpc.ValidateTokenReq\x1a\x1a.open_rpc.ValidateTokenRes\x12D\n" +
	"\fRefreshToken\x12\x19.open_rpc.RefreshTokenReq\x1a\x19.open_rpc.RefreshTokenRes\x12;\n" +
	"\tCreateBot\x12\x16.open_rpc.CreateBotReq\x1a\x16.open_rpc.CreateBotRes\x12;\n" +
	"\tDeleteBot\x12\x16.open_rpc.DeleteBotReq\x1a\x16.open_rpc.DeleteBotRes\x12J\n" +
	"\x0eResetBotSecret\x12\x1b.open_rpc.ResetBotSecretReq\x1a\x1b.open_rpc.ResetBotSecretResB\fZ\n" +
	"./open_rpcb\x06proto3"

var (
	file_open_rpc_proto_rawDescOnce sync.Once
	file_open_rpc_proto_rawDescData []byte
)

func file_open_rpc_proto_rawDescGZIP() []byte {
	file_open_rpc_proto_rawDescOnce.Do(func() {
		file_open_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_open_rpc_proto_rawDesc), len(file_open_rpc_proto_rawDesc)))
	})
	return file_open_rpc_proto_rawDescData
}

var file_open_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_open_rpc_proto_goTypes = []any{
	(*ExchangeTokenReq)(nil),  // 0: open_rpc.ExchangeTokenReq
	(*ExchangeTokenRes)(nil),  // 1: open_rpc.ExchangeTokenRes
	(*GetUserInfoReq)(nil),    // 2: open_rpc.GetUserInfoReq
	(*GetUserInfoRes)(nil),    // 3: open_rpc.GetUserInfoRes
	(*ValidateTokenReq)(nil),  // 4: open_rpc.ValidateTokenReq
	(*ValidateTokenRes)(nil),  // 5: open_rpc.ValidateTokenRes
	(*RefreshTokenReq)(nil),   // 6: open_rpc.RefreshTokenReq
	(*RefreshTokenRes)(nil),   // 7: open_rpc.RefreshTokenRes
	(*CreateBotReq)(nil),      // 8: open_rpc.CreateBotReq
	(*CreateBotRes)(nil),      // 9: open_rpc.CreateBotRes
	(*DeleteBotReq)(nil),      // 10: open_rpc.DeleteBotReq
	(*DeleteBotRes)(nil),      // 11: open_rpc.DeleteBotRes
	(*ResetBotSecretReq)(nil), // 12: open_rpc.ResetBotSecretReq
	(*ResetBotSecretRes)(nil), // 13: open_rpc.ResetBotSecretRes
}
var file_open_rpc_proto_depIdxs = []int32{
	0,  // 0: open_rpc.open.ExchangeToken:input_type -> open_rpc.ExchangeTokenReq
	2,  // 1: open_rpc.open.GetUserInfo:input_type -> open_rpc.GetUserInfoReq
	4,  // 2: open_rpc.open.ValidateToken:input_type -> open_rpc.ValidateTokenReq
	6,  // 3: open_rpc.open.RefreshToken:input_type -> open_rpc.RefreshTokenReq
	8,  // 4: open_rpc.open.CreateBot:input_type -> open_rpc.CreateBotReq
	10, // 5: open_rpc.open.DeleteBot:input_type -> open_rpc.DeleteBotReq
	12, // 6: open_rpc.open.ResetBotSecret:input_type -> open_rpc.ResetBotSecretReq
	1,  // 7: open_rpc.open.ExchangeToken:output_type -> open_rpc.ExchangeTokenRes
	3,  // 8: open_rpc.open.GetUserInfo:output_type -> open_rpc.GetUserInfoRes
	5,  // 9: open_rpc.open.ValidateToken:output_type -> open_rpc.ValidateTokenRes
	7,  // 10: open_rpc.open.RefreshToken:output_type -> open_rpc.RefreshTokenRes
	9,  // 11: open_rpc.open.CreateBot:output_type -> open_rpc.CreateBotRes
	11, // 12: open_rpc.open.DeleteBot:output_type -> open_rpc.DeleteBotRes
	13, // 13: open_rpc.open.ResetBotSecret:output_type -> open_rpc.ResetBotSecretRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_open_rpc_proto_init() }
func file_open_rpc_proto_init() {
	if File_open_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_open_rpc_proto_rawDesc), len(file_open_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_open_rpc_proto_goTypes,
		DependencyIndexes: file_open_rpc_proto_depIdxs,
		MessageInfos:      file_open_rpc_proto_msgTypes,
	}.Build()
	File_open_rpc_proto = out.File
	file_open_rpc_proto_goTypes = nil
	file_open_rpc_proto_depIdxs = nil
}
