
services:
  circle_api:
    image: wsrh8888/circle_api:1.0.0
    container_name: circle_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./circle.yaml:/etc/circle.yaml:ro
    restart: "no"
    pull_policy: always
